--------------------------------------------------------
--  DDL for Table AFP
--------------------------------------------------------

  CREATE TABLE "USR_TSI_SUITE"."AFP" 
   (	"ID_CIA" NUMBER, 
	"CODAFP" VARCHAR2(4 BYTE), 
	"NOMBRE" VARCHAR2(40 BYTE), 
	"CODCLA" VARCHAR2(20 BYTE), 
	"CODCTA" VARCHAR2(15 BYTE), 
	"DH" CHAR(1 BYTE), 
	"CODIGO" VARCHAR2(20 BYTE), 
	"ABREVI" VARCHAR2(2 BYTE), 
	"UCREAC" VARCHAR2(10 BYTE), 
	"UACTUA" VARCHAR2(10 BYTE), 
	"FCREAC" TIMESTAMP (6), 
	"FACTUA" TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_TSI_SUITE" ;
