--------------------------------------------------------
--  Ref Constraints for Table ARTICULOS_CLASE
--------------------------------------------------------

  ALTER TABLE "USR_TSI_SUITE"."ARTICULOS_CLASE" ADD CONSTRAINT "FK_ARTICULOS_CLASE_CLASE_CODIGO" FOREIGN KEY ("ID_CIA", "TIPINV", "CLASE", "CODIGO")
	  REFERENCES "USR_TSI_SUITE"."CLASE_CODIGO" ("ID_CIA", "TIPINV", "CLASE", "CODIGO") ENABLE;
  ALTER TABLE "USR_TSI_SUITE"."ARTICULOS_CLASE" ADD CONSTRAINT "FK_ARTICULOS_CLASE_ARTICULOS" FOREIGN KEY ("ID_CIA", "TIPINV", "CODART")
	  REFERENCES "USR_TSI_SUITE"."ARTICULOS" ("ID_CIA", "TIPINV", "CODART") ENABLE;
