--------------------------------------------------------
--  Constraints for Table ARTICULO_ESPECIFICACION
--------------------------------------------------------

  ALTER TABLE "USR_TSI_SUITE"."ARTICULO_ESPECIFICACION" MODIFY ("ID_CIA" NOT NULL ENABLE);
  ALTER TABLE "USR_TSI_SUITE"."ARTICULO_ESPECIFICACION" MODIFY ("TIPINV" NOT NULL ENABLE);
  ALTER TABLE "USR_TSI_SUITE"."ARTICULO_ESPECIFICACION" MODIFY ("CODART" NOT NULL ENABLE);
  ALTER TABLE "USR_TSI_SUITE"."ARTICULO_ESPECIFICACION" MODIFY ("CODESP" NOT NULL ENABLE);
  ALTER TABLE "USR_TSI_SUITE"."ARTICULO_ESPECIFICACION" ADD CONSTRAINT "PK_ARTICULO_ESPECIFICACION" PRIMARY KEY ("ID_CIA", "TIPINV", "CODART", "CODESP")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_TSI_SUITE"  ENABLE;
