--------------------------------------------------------
--  DDL for Table ARTICULOS_MOVIMIENTO
--------------------------------------------------------

  CREATE TABLE "USR_TSI_SUITE"."ARTICULOS_MOVIMIENTO" 
   (	"ID_CIA" NUMBER(*,0), 
	"LOCALI" NUMBER(*,0), 
	"ID" CHAR(1 BYTE), 
	"TIPDOC" NUMBER(*,0), 
	"NUMINT" NUMBER(*,0), 
	"NUMITE" NUMBER(*,0), 
	"CODCLI" VARCHAR2(20 BYTE), 
	"CODMOT" NUMBER(*,0), 
	"FDESDE" DATE, 
	"FHASTA" DATE, 
	"TIPINV" NUMBER(*,0), 
	"CODART" VARCHAR2(40 BYTE), 
	"SITUAC" CHAR(1 BYTE), 
	"FCREAC" TIMESTAMP (6), 
	"FACTUA" TIMESTAMP (6), 
	"USUARI" VARCHAR2(10 BYTE), 
	"SWACTI" CHAR(1 BYTE), 
	"OBSERV" VARCHAR2(1000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_TSI_SUITE" ;
