--------------------------------------------------------
--  Constraints for Table ARTICULO_INTERMEDIO
--------------------------------------------------------

  ALTER TABLE "USR_TSI_SUITE"."ARTICULO_INTERMEDIO" MODIFY ("ID_CIA" NOT NULL ENABLE);
  ALTER TABLE "USR_TSI_SUITE"."ARTICULO_INTERMEDIO" MODIFY ("TIPINV" NOT NULL ENABLE);
  ALTER TABLE "USR_TSI_SUITE"."ARTICULO_INTERMEDIO" MODIFY ("CODART" NOT NULL ENABLE);
  ALTER TABLE "USR_TSI_SUITE"."ARTICULO_INTERMEDIO" MODIFY ("CODINT" NOT NULL ENABLE);
  ALTER TABLE "USR_TSI_SUITE"."ARTICULO_INTERMEDIO" ADD CONSTRAINT "PK_ARTICULO_INTERMEDIO" PRIMARY KEY ("ID_CIA", "TIPINV", "CODART", "CODINT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_TSI_SUITE"  ENABLE;
