--------------------------------------------------------
--  DDL for Table ARTICULOS_COMBOS
--------------------------------------------------------

  CREATE TABLE "USR_TSI_SUITE"."ARTICULOS_COMBOS" 
   (	"ID_CIA" NUMBER(*,0), 
	"CODIGO" VARCHAR2(20 BYTE), 
	"TIPINV" NUMBER(*,0), 
	"CODART" VARCHAR2(40 BYTE), 
	"CODTIT" NUMBER(*,0), 
	"SITUAC" CHAR(1 BYTE), 
	"CANTID" NUMBER(16,5), 
	"TIPMON" VARCHAR2(5 BYTE), 
	"INCIGV" CHAR(1 BYTE), 
	"PREUNI" NUMBER(12,5), 
	"DESC01" NUMBER(9,5), 
	"DESC02" NUMBER(9,5), 
	"DESC03" NUMBER(9,5), 
	"DESC04" NUMBER(9,5)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_TSI_SUITE" ;
