--------------------------------------------------------
--  DDL for Table ARTICULOS_ALMACEN
--------------------------------------------------------

  CREATE TABLE "USR_TSI_SUITE"."ARTICULOS_ALMACEN" 
   (	"ID_CIA" NUMBER(*,0), 
	"TIPINV" NUMBER(*,0), 
	"CODART" VARCHAR2(40 BYTE), 
	"CODALM" NUMBER(*,0), 
	"PERIODO" NUMBER(*,0), 
	"INGRESO" NUMBER(16,4), 
	"SALIDA" NUMBER(16,4), 
	"COSING01" NUMBER(16,4), 
	"COSING02" NUMBER(16,4), 
	"COSSAL01" NUMBER(16,4), 
	"COSSAL02" NUMBER(16,4)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_TSI_SUITE" ;
