--------------------------------------------------------
--  DDL for Table ASISTENCIA_PLANILLA
--------------------------------------------------------

  CREATE TABLE "USR_TSI_SUITE"."ASISTENCIA_PLANILLA" 
   (	"ID_CIA" NUMBER, 
	"CODASIST" NUMBER, 
	"CODSUC" NUMBER, 
	"CODPER" VARCHAR2(20 CHAR), 
	"FECHA" DATE, 
	"HORA" TIMESTAMP (6), 
	"FREGIS" TIMESTAMP (6), 
	"TIPO" VARCHAR2(1 CHAR), 
	"CODMOT" NUMBER(*,0), 
	"ID_TURNO" NUMBER, 
	"FLAGMARCA" VARCHAR2(1 CHAR), 
	"SITUAC" VARCHAR2(1 CHAR), 
	"DIRECC" VARCHAR2(250 CHAR), 
	"LATITUD" NUMBER(*,0), 
	"LONGITUD" NUMBER(*,0), 
	"OBSERV" VARCHAR2(250 CHAR), 
	"UCREAC" VARCHAR2(10 CHAR), 
	"UACTUA" VARCHAR2(10 CHAR), 
	"FCREAC" TIMESTAMP (6), 
	"FACTUA" TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_TSI_SUITE" ;
