--------------------------------------------------------
--  DDL for Table ASISTENCIA_PLANILLA_TURNO
--------------------------------------------------------

  CREATE TABLE "USR_TSI_SUITE"."ASISTENCIA_PLANILLA_TURNO" 
   (	"ID_CIA" NUMBER, 
	"ID_TURNO" NUMBER, 
	"TIPTRA" VARCHAR2(1 BYTE), 
	"DESTURN" VARCHAR2(40 CHAR), 
	"HINGTUR" TIMESTAMP (6), 
	"HSALTUR" TIMESTAMP (6), 
	"MINTUR" NUMBER(*,0), 
	"TOLETUR" NUMBER(*,0), 
	"INCREF" VARCHAR2(1 BYTE), 
	"HINGREF" TIMESTAMP (6), 
	"HSALREF" TIMESTAMP (6), 
	"MINREF" NUMBER(*,0), 
	"TOLEREF" NUMBER(*,0), 
	"DIA" VARCHAR2(30 CHAR), 
	"EXTRA" VARCHAR2(1 CHAR), 
	"TIPOASIG" VARCHAR2(1 CHAR), 
	"UCREAC" VARCHAR2(10 CHAR), 
	"UACTUA" VARCHAR2(10 CHAR), 
	"FCREAC" TIMESTAMP (6), 
	"FACTUA" TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_TSI_SUITE" ;
