--------------------------------------------------------
--  Constraints for Table ASISTENCIA_PLANILLA
--------------------------------------------------------

  ALTER TABLE "USR_TSI_SUITE"."ASISTENCIA_PLANILLA" MODIFY ("CODSUC" NOT NULL ENABLE);
  ALTER TABLE "USR_TSI_SUITE"."ASISTENCIA_PLANILLA" MODIFY ("CODPER" NOT NULL ENABLE);
  ALTER TABLE "USR_TSI_SUITE"."ASISTENCIA_PLANILLA" MODIFY ("ID_TURNO" NOT NULL ENABLE);
  ALTER TABLE "USR_TSI_SUITE"."ASISTENCIA_PLANILLA" ADD CONSTRAINT "PK_ASISTENCIA_PLANILLA" PRIMARY KEY ("ID_CIA", "CODASIST")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_TSI_SUITE"  ENABLE;
