--------------------------------------------------------
--  DDL for Table ASISTENCIA
--------------------------------------------------------

  CREATE TABLE "USR_TSI_SUITE"."ASISTENCIA" 
   (	"ID_CIA" NUMBER(*,0), 
	"CODASIST" NUMBER(*,0), 
	"USUARI" VARCHAR2(10 BYTE), 
	"FCREAC" TIMESTAMP (6), 
	"DIRECCION" VARCHAR2(600 BYTE), 
	"LATITUD" NUMBER(*,0), 
	"LONGITUD" NUMBER(*,0), 
	"CODTURNO" NUMBER(*,0), 
	"CODSUC" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_TSI_SUITE" ;
