--------------------------------------------------------
--  Constraints for Table BANCOS_ESTADOCUENTA
--------------------------------------------------------

  ALTER TABLE "USR_TSI_SUITE"."BANCOS_ESTADOCUENTA" ADD CONSTRAINT "PK_BANCOS_ESTADOCUENTA" PRIMARY KEY ("ID_CIA", "B_CUENTA", "B_PERIODO", "B_MES", "B_NUMITE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_TSI_SUITE"  ENABLE;
