--------------------------------------------------------
--  DDL for Table C_PAGO
--------------------------------------------------------

  CREATE TABLE "USR_TSI_SUITE"."C_PAGO" 
   (	"ID_CIA" NUMBER(*,0), 
	"CODPAG" NUMBER(*,0), 
	"DESPAG" VARCHAR2(50 CHAR), 
	"DETALLE" VARCHAR2(1000 BYTE), 
	"DIAVEN" NUMBER(*,0), 
	"FCREAC" TIMESTAMP (6), 
	"FACTUA" TIMESTAMP (6), 
	"USUARI" VARCHAR2(10 BYTE), 
	"CANJLET" VARCHAR2(1 BYTE), 
	"CANTLET" NUMBER(*,0), 
	"PORDES" NUMBER(10,3), 
	"SWACTI" CHAR(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_TSI_SUITE" ;
