--------------------------------------------------------
--  DDL for Table CAJA_DET
--------------------------------------------------------

  CREATE TABLE "USR_TSI_SUITE"."CAJA_DET" 
   (	"ID_CIA" NUMBER(*,0), 
	"NUMCAJA" NUMBER(*,0), 
	"NUMITE" NUMBER(*,0), 
	"ID" VARCHAR2(1 BYTE), 
	"NUMINT" NUMBER(*,0), 
	"CODMOV" NUMBER(*,0), 
	"TIPMON" VARCHAR2(5 BYTE), 
	"IMPORTE" NUMBER(16,4), 
	"OBSERV" VARCHAR2(1000 BYTE), 
	"CODBAN" VARCHAR2(3 BYTE), 
	"CUENTA" VARCHAR2(20 BYTE), 
	"NUMERO" VARCHAR2(30 BYTE), 
	"FVENCE" DATE, 
	"CUOTAS" NUMBER(*,0), 
	"FCREAC" TIMESTAMP (6), 
	"FACTUA" TIMESTAMP (6), 
	"USUARI" VARCHAR2(10 BYTE), 
	"SWACTI" VARCHAR2(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_TSI_SUITE" ;
