--------------------------------------------------------
--  DDL for Table CCOTIZACIONES
--------------------------------------------------------

  CREATE TABLE "USR_TSI_SUITE"."CCOTIZACIONES" 
   (	"ID_CIA" NUMBER(*,0), 
	"SITUAC" VARCHAR2(1 BYTE), 
	"DESSIT" VARCHAR2(50 BYTE), 
	"NICOTI" NUMBER(*,0), 
	"NUMCOT" VARCHAR2(30 BYTE), 
	"NUMPED" VARCHAR2(30 BYTE), 
	"FEMISI" VARCHAR2(20 BYTE), 
	"PERIODO" NUMBER(*,0), 
	"MES" VARCHAR2(30 BYTE), 
	"MESID" NUMBER(*,0), 
	"DIAS" NUMBER(*,0), 
	"CODVEN" NUMBER(*,0), 
	"VENDEDOR" VARCHAR2(50 BYTE), 
	"CODCLI" VARCHAR2(20 BYTE), 
	"RUC" VARCHAR2(16 BYTE), 
	"CLIENTE" VARCHAR2(100 BYTE), 
	"NUMITE" NUMBER(*,0), 
	"TIPINVCOT" NUMBER(*,0), 
	"CODARTCOT" VARCHAR2(40 BYTE), 
	"DESCRICOT" VARCHAR2(100 BYTE), 
	"CANTIDCOT" NUMBER(16,5), 
	"FACCON" NUMBER(16,5), 
	"TONELACOT" NUMBER(16,5), 
	"COTIZASOL" NUMBER(16,2), 
	"COTIZADOL" NUMBER(16,2), 
	"TIPINVPED" NUMBER(*,0), 
	"CODARTPED" VARCHAR2(40 BYTE), 
	"CANTIDPED" NUMBER(16,5), 
	"PEDIDOSOL" NUMBER(16,2), 
	"PEDIDODOL" NUMBER(16,2), 
	"SWCOMPRA" VARCHAR2(1 BYTE), 
	"COMENT" VARCHAR2(1200 BYTE), 
	"USEMIT" VARCHAR2(10 BYTE), 
	"OBSERV" VARCHAR2(1200 BYTE), 
	"CODMOT" NUMBER(*,0), 
	"DESMOT" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_TSI_SUITE" ;
