--------------------------------------------------------
--  Constraints for Table CLASE_CODIGO_PERSONAL
--------------------------------------------------------

  ALTER TABLE "USR_TSI_SUITE"."CLASE_CODIGO_PERSONAL" MODIFY ("ID_CIA" NOT NULL ENABLE);
  ALTER TABLE "USR_TSI_SUITE"."CLASE_CODIGO_PERSONAL" MODIFY ("CLASE" NOT NULL ENABLE);
  ALTER TABLE "USR_TSI_SUITE"."CLASE_CODIGO_PERSONAL" MODIFY ("CODIGO" NOT NULL ENABLE);
  ALTER TABLE "USR_TSI_SUITE"."CLASE_CODIGO_PERSONAL" MODIFY ("DESCRI" NOT NULL ENABLE);
  ALTER TABLE "USR_TSI_SUITE"."CLASE_CODIGO_PERSONAL" ADD CONSTRAINT "PK_CLASE_CODIGO_PERSONAL" PRIMARY KEY ("ID_CIA", "CLASE", "CODIGO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_TSI_SUITE"  ENABLE;
