--------------------------------------------------------
--  DDL for Table CLASE_TIPO_FACTOR_PLANILLA
--------------------------------------------------------

  CREATE TABLE "USR_TSI_SUITE"."CLASE_TIPO_FACTOR_PLANILLA" 
   (	"ID_CIA" NUMBER(*,0), 
	"TIPCLA" NUMBER(*,0), 
	"DESTIPCLA" VARCHAR2(80 CHAR), 
	"VREAL" VARCHAR2(1 BYTE), 
	"VSTRG" VARCHAR2(1 BYTE), 
	"VCHAR" VARCHAR2(1 BYTE), 
	"VDATE" VARCHAR2(1 BYTE), 
	"VTIME" VARCHAR2(1 BYTE), 
	"VENTERO" VARCHAR2(1 BYTE), 
	"SWACTI" VARCHAR2(1 BYTE), 
	"OBLIGA" VARCHAR2(1 BYTE), 
	"UCREAC" VARCHAR2(10 BYTE), 
	"UACTUA" VARCHAR2(10 BYTE), 
	"FCREAC" TIMESTAMP (6), 
	"FACTUA" TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_TSI_SUITE" ;
