--------------------------------------------------------
--  Constraints for Table CLI_RECETA
--------------------------------------------------------

  ALTER TABLE "USR_TSI_SUITE"."CLI_RECETA" MODIFY ("ID_CIA" NOT NULL ENABLE);
  ALTER TABLE "USR_TSI_SUITE"."CLI_RECETA" MODIFY ("ID_REC" NOT NULL ENABLE);
  ALTER TABLE "USR_TSI_SUITE"."CLI_RECETA" MODIFY ("ID_CONS" NOT NULL ENABLE);
  ALTER TABLE "USR_TSI_SUITE"."CLI_RECETA" ADD CONSTRAINT "PK_CLI_RECETA" PRIMARY KEY ("ID_CIA", "ID_REC")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_TSI_SUITE"  ENABLE;
