--------------------------------------------------------
--  DDL for Table CLI_RECETA
--------------------------------------------------------

  CREATE TABLE "USR_TSI_SUITE"."CLI_RECETA" 
   (	"ID_CIA" NUMBER, 
	"ID_REC" NUMBER, 
	"ID_CONS" NUMBER, 
	"ID_PAC" NUMBER, 
	"ID_TRIA" NUMBER, 
	"ID_CITA" NUMBER, 
	"ID_DIAG" VARCHAR2(20 BYTE), 
	"ID_ARTI" VARCHAR2(20 BYTE), 
	"CANTIDAD" NUMBER, 
	"CODUSERCREA" VARCHAR2(10 BYTE), 
	"CODUSERACTU" VARCHAR2(10 BYTE), 
	"FCREAC" TIMESTAMP (6), 
	"FACTUA" TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_TSI_SUITE" ;
