--------------------------------------------------------
--  DDL for Table CLI_DIAGNOSTICO
--------------------------------------------------------

  CREATE TABLE "USR_TSI_SUITE"."CLI_DIAGNOSTICO" 
   (	"ID_CIA" NUMBER, 
	"ID_DIAG" VARCHAR2(20 BYTE), 
	"DESCRIPCION" VARCHAR2(200 BYTE), 
	"ESTADO" VARCHAR2(1 BYTE), 
	"CODUSERCREA" VARCHAR2(10 BYTE), 
	"CODUSERACTU" VARCHAR2(10 BYTE), 
	"FCREAC" TIMESTAMP (6), 
	"FACTUA" TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_TSI_SUITE" ;
