--------------------------------------------------------
--  DDL for Table CLI_MEDICO
--------------------------------------------------------

  CREATE TABLE "USR_TSI_SUITE"."CLI_MEDICO" 
   (	"ID_CIA" NUMBER, 
	"ID_MED" NUMBER, 
	"APEPAT" VARCHAR2(50 BYTE), 
	"APEMAT" VARCHAR2(50 BYTE), 
	"NOMBRES" VARCHAR2(50 BYTE), 
	"FNACIMI" DATE, 
	"SEXO" VARCHAR2(1 BYTE), 
	"CODECI" NUMBER(38,0), 
	"TIDENT" VARCHAR2(2 BYTE), 
	"DIDENT" VARCHAR2(20 BYTE), 
	"DIRECCION" VARCHAR2(100 BYTE), 
	"TELEFONO" VARCHAR2(50 BYTE), 
	"EMAIL" VARCHAR2(50 BYTE), 
	"CODESP" VARCHAR2(20 BYTE), 
	"UCREAC" VARCHAR2(10 BYTE), 
	"UACTUA" VARCHAR2(10 BYTE), 
	"FCREAC" TIMESTAMP (6), 
	"FACTUA" TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_TSI_SUITE" ;
