--------------------------------------------------------
--  DDL for Table CLI_TRIAGE
--------------------------------------------------------

  CREATE TABLE "USR_TSI_SUITE"."CLI_TRIAGE" 
   (	"ID_CIA" NUMBER, 
	"ID_TRIA" NUMBER, 
	"ID_PAC" VARCHAR2(20 BYTE), 
	"ID_CITA" NUMBER, 
	"ID_MED" NUMBER, 
	"POLIZA" VARCHAR2(50 BYTE), 
	"PARTER" NUMBER, 
	"TEMPER" NUMBER, 
	"FRESPI" NUMBER, 
	"FCARDI" NUMBER, 
	"SATURA" NUMBER, 
	"PESO" NUMBER(3,3), 
	"TALLA" NUMBER(1,3), 
	"ESTADO" VARCHAR2(1 BYTE), 
	"UCREAC" VARCHAR2(10 BYTE), 
	"UACTUA" VARCHAR2(10 BYTE), 
	"FCREAC" TIMESTAMP (6), 
	"FACTUA" TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_TSI_SUITE" ;
