--------------------------------------------------------
--  DDL for Table CLIENTES_CREDITO_LOG
--------------------------------------------------------

  CREATE TABLE "USR_TSI_SUITE"."CLIENTES_CREDITO_LOG" 
   (	"ID_CIA" NUMBER(*,0), 
	"CODCLI" VARCHAR2(20 BYTE), 
	"ITEM" NUMBER(*,0), 
	"CREDITO" NUMBER(*,0), 
	"FCREAC" TIMESTAMP (6), 
	"USUARI" VARCHAR2(10 BYTE), 
	"OBSERVA" VARCHAR2(1000 BYTE), 
	"DGRACIA" NUMBER(9,2), 
	"LIMCRED" NUMBER(9,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_TSI_SUITE" ;
