--------------------------------------------------------
--  DDL for Table CLIENTE_GARANTIA
--------------------------------------------------------

  CREATE TABLE "USR_TSI_SUITE"."CLIENTE_GARANTIA" 
   (	"ID_CIA" NUMBER(*,0), 
	"NUMINT" NUMBER(*,0), 
	"CODCLI" VARCHAR2(20 BYTE), 
	"FRECEP" DATE, 
	"FEMISI" DATE, 
	"FVENCI" DATE, 
	"TIPDOC" NUMBER(*,0), 
	"CODBAN" NUMBER(*,0), 
	"REFERENCIA" VARCHAR2(20 BYTE), 
	"IMPORTE" NUMBER(16,4), 
	"OBSERV" VARCHAR2(1000 BYTE), 
	"CODMON" VARCHAR2(5 BYTE), 
	"REFERENCIA2" VARCHAR2(20 BYTE), 
	"SWACTI" CHAR(1 BYTE), 
	"FDEVOL" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_TSI_SUITE" ;
