--------------------------------------------------------
--  DDL for Table COMPR005
--------------------------------------------------------

  CREATE TABLE "USR_TSI_SUITE"."COMPR005" 
   (	"ID_CIA" NUMBER(*,0), 
	"TIPO" NUMBER(*,0), 
	"DOCUME" NUMBER(*,0), 
	"TIDENT" CHAR(2 BYTE), 
	"DIDENT" VARCHAR2(16 BYTE), 
	"TDOCUM" CHAR(2 BYTE), 
	"NSERIE" VARCHAR2(6 BYTE), 
	"PREIMP" VARCHAR2(25 BYTE), 
	"FEMISI" TIMESTAMP (6), 
	"MONEDA" CHAR(3 BYTE), 
	"FACTOR" VARCHAR2(2 BYTE), 
	"VALFAC" NUMBER(14,6), 
	"IMPORT" NUMBER(16,2), 
	"IMPIGV" NUMBER(16,2), 
	"TCAM01" NUMBER(14,6), 
	"TCAM02" NUMBER(14,6), 
	"IMPO01" NUMBER(16,2), 
	"IMPO02" NUMBER(16,2), 
	"IGV01" NUMBER(16,2), 
	"IGV02" NUMBER(16,2), 
	"SITUAC" NUMBER(*,0), 
	"USUARI" VARCHAR2(10 BYTE), 
	"FCREAC" TIMESTAMP (6), 
	"FACTUA" TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_TSI_SUITE" ;
