--------------------------------------------------------
--  Constraints for Table COMPANIAS_CONFIG_EMAIL
--------------------------------------------------------

  ALTER TABLE "USR_TSI_SUITE"."COMPANIAS_CONFIG_EMAIL" MODIFY ("ID_CIA" NOT NULL ENABLE);
  ALTER TABLE "USR_TSI_SUITE"."COMPANIAS_CONFIG_EMAIL" MODIFY ("TIPO" NOT NULL ENABLE);
  ALTER TABLE "USR_TSI_SUITE"."COMPANIAS_CONFIG_EMAIL" ADD CONSTRAINT "PK_COMPANIAS_CONFIG_EMAIL" PRIMARY KEY ("ID_CIA", "TIPO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_TSI_SUITE"  ENABLE;
