--------------------------------------------------------
--  DDL for Table COMPR011
--------------------------------------------------------

  CREATE TABLE "USR_TSI_SUITE"."COMPR011" 
   (	"ID_CIA" NUMBER(*,0), 
	"TIPO" NUMBER(*,0), 
	"DOCUME" NUMBER(*,0), 
	"ITEM" NUMBER(*,0), 
	"FTREG" NUMBER(*,0), 
	"PERIODO" NUMBER(*,0), 
	"MES" NUMBER(*,0), 
	"MONEDA" CHAR(3 BYTE), 
	"CUENTA" VARCHAR2(16 BYTE), 
	"DH" CHAR(1 BYTE), 
	"CONCEP" VARCHAR2(40 BYTE), 
	"IMPORTE" NUMBER(16,2), 
	"IMPOR01" NUMBER(16,2), 
	"IMPOR02" NUMBER(16,2), 
	"TCAMB01" NUMBER(14,6), 
	"TCAMB02" NUMBER(14,6), 
	"DOCORI" NUMBER(*,0), 
	"CCOSTO" VARCHAR2(16 BYTE), 
	"PROYEC" VARCHAR2(16 BYTE), 
	"USUARI" VARCHAR2(10 BYTE), 
	"FCREAC" TIMESTAMP (6), 
	"FACTUA" TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_TSI_SUITE" ;
