--------------------------------------------------------
--  Ref Constraints for Table COMPANIA_BANCO
--------------------------------------------------------

  ALTER TABLE "USR_TSI_SUITE"."COMPANIA_BANCO" ADD CONSTRAINT "FK_COMPANIA_BANCO_E_FINANCIERA" FOREIGN KEY ("ID_CIA", "CODBAN")
	  REFERENCES "USR_TSI_SUITE"."E_FINANCIERA" ("ID_CIA", "CODIGO") ENABLE;
  ALTER TABLE "USR_TSI_SUITE"."COMPANIA_BANCO" ADD CONSTRAINT "FK_COMPANIA_BANCO_E_FINANCIERA_TIPO" FOREIGN KEY ("ID_CIA", "TIPCTA")
	  REFERENCES "USR_TSI_SUITE"."E_FINANCIERA_TIPO" ("ID_CIA", "TIPCTA") ENABLE;
