--------------------------------------------------------
--  DDL for Table COMPANIAS_GLOSA
--------------------------------------------------------

  CREATE TABLE "USR_TSI_SUITE"."COMPANIAS_GLOSA" 
   (	"ID_CIA" NUMBER(*,0), 
	"ITEM" NUMBER(*,0), 
	"NOMBRE" VARCHAR2(100 BYTE), 
	"GLOSA" VARCHAR2(3000 CHAR), 
	"GLOSA_FILE" BLOB, 
	"UCREAC" VARCHAR2(10 CHAR), 
	"UACTUA" VARCHAR2(10 CHAR), 
	"FACTUA" TIMESTAMP (6), 
	"FCREAC" TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_TSI_SUITE" 
 LOB ("GLOSA_FILE") STORE AS SECUREFILE (
  TABLESPACE "TBS_TSI_SUITE" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
