--------------------------------------------------------
--  DDL for Table COMPANIAS_CONFIG_EMAIL
--------------------------------------------------------

  CREATE TABLE "USR_TSI_SUITE"."COMPANIAS_CONFIG_EMAIL" 
   (	"ID_CIA" NUMBER(*,0), 
	"TIPO" NUMBER(*,0), 
	"EMAIL" VARCHAR2(150 BYTE), 
	"PWD" VARCHAR2(500 BYTE), 
	"SMTP" VARCHAR2(100 BYTE), 
	"PORT" VARCHAR2(10 BYTE), 
	"EMAILCC" VARCHAR2(300 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_TSI_SUITE" ;
