--------------------------------------------------------
--  DDL for Table COMPR040
--------------------------------------------------------

  CREATE TABLE "USR_TSI_SUITE"."COMPR040" 
   (	"ID_CIA" NUMBER(*,0), 
	"TIPO" NUMBER(*,0), 
	"DOCUME" NUMBER(*,0), 
	"FEMISI" DATE, 
	"CODPER" VARCHAR2(20 CHAR), 
	"CONCEP" VARCHAR2(75 CHAR), 
	"MOTIVO" NUMBER(*,0), 
	"MONEDA" CHAR(3 BYTE), 
	"CODAREA" NUMBER(*,0), 
	"REFEREN" VARCHAR2(20 BYTE), 
	"CCOSTO" VARCHAR2(16 BYTE), 
	"APROBADO" CHAR(1 BYTE), 
	"CAPROB" VARCHAR2(10 BYTE), 
	"FAPROB" DATE, 
	"TIPPAGO" NUMBER(*,0), 
	"CTAPAGO" VARCHAR2(16 BYTE), 
	"SITUAC" NUMBER(*,0), 
	"USUARI" VARCHAR2(10 BYTE), 
	"FCREAC" TIMESTAMP (6), 
	"FACTUA" TIMESTAMP (6), 
	"PERIODO" NUMBER(*,0), 
	"MES" NUMBER(*,0), 
	"LIBRO" VARCHAR2(3 BYTE), 
	"ASIENTO" NUMBER(*,0), 
	"LIBROP" VARCHAR2(3 BYTE), 
	"ASIENTOP" NUMBER(*,0), 
	"TCAMBIO" NUMBER(14,6), 
	"FONDO" NUMBER(16,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_TSI_SUITE" ;
