--------------------------------------------------------
--  DDL for Table COMPR010_DOCORIGEN
--------------------------------------------------------

  CREATE TABLE "USR_TSI_SUITE"."COMPR010_DOCORIGEN" 
   (	"ID_CIA" NUMBER, 
	"TIPO" NUMBER, 
	"DOCUME" NUMBER, 
	"ITEM" NUMBER, 
	"CODPRO" VARCHAR2(20 BYTE), 
	"TDOCUM" VARCHAR2(20 BYTE), 
	"SERIE" VARCHAR2(20 BYTE), 
	"NUMERO" VARCHAR2(20 BYTE), 
	"IMPORTE" NUMBER(16,2), 
	"FEMISI" DATE, 
	"TIPCAM" NUMBER(16,4), 
	"IMPOR01" NUMBER(16,2), 
	"IMPOR02" NUMBER(16,2), 
	"UCREAC" VARCHAR2(10 BYTE), 
	"UACTUA" VARCHAR2(10 BYTE), 
	"FCREAC" DATE, 
	"FACTUA" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_TSI_SUITE" ;
