--------------------------------------------------------
--  DDL for Table COMPR010DOCREL
--------------------------------------------------------

  CREATE TABLE "USR_TSI_SUITE"."COMPR010DOCREL" 
   (	"ID_CIA" NUMBER(*,0), 
	"KIND" NUMBER(*,0), 
	"TIPO" NUMBER(*,0), 
	"DOCUME" NUMBER(*,0), 
	"TIPOREL" NUMBER(*,0), 
	"DOCUMEREL" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_TSI_SUITE" ;
