--------------------------------------------------------
--  DDL for Table COMPANIAS_GRUPO
--------------------------------------------------------

  CREATE TABLE "USR_TSI_SUITE"."COMPANIAS_GRUPO" 
   (	"ID_GRUP" NUMBER, 
	"GRUPO" VARCHAR2(100 CHAR), 
	"ID_CIA" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_TSI_SUITE" ;
