--------------------------------------------------------
--  Ref Constraints for Table CONCEPTO
--------------------------------------------------------

  ALTER TABLE "USR_TSI_SUITE"."CONCEPTO" ADD CONSTRAINT "FK_CONCEPTO_CONCEPTOS_PDT" FOREIGN KEY ("ID_CIA", "CODPDT")
	  REFERENCES "USR_TSI_SUITE"."CONCEPTOS_PDT" ("ID_CIA", "CODPDT") ENABLE;
  ALTER TABLE "USR_TSI_SUITE"."CONCEPTO" ADD CONSTRAINT "FK_CONCEPTO_PCUENTAS_CODCTA" FOREIGN KEY ("ID_CIA", "CODCTA")
	  REFERENCES "USR_TSI_SUITE"."PCUENTAS" ("ID_CIA", "CUENTA") ENABLE;
