--------------------------------------------------------
--  DDL for Table CONCEPTO_CLASE
--------------------------------------------------------

  CREATE TABLE "USR_TSI_SUITE"."CONCEPTO_CLASE" 
   (	"ID_CIA" NUMBER, 
	"CODCON" VARCHAR2(5 BYTE), 
	"CLASE" NUMBER, 
	"CODIGO" VARCHAR2(20 BYTE), 
	"VSTRG" VARCHAR2(30 BYTE), 
	"VRESULT" VARCHAR2(100 CHAR), 
	"VPOSITION" VARCHAR2(1 BYTE), 
	"VPREFIJO" VARCHAR2(100 CHAR), 
	"VSUFIJO" VARCHAR2(100 CHAR), 
	"CODFOR" NUMBER, 
	"UCREAC" VARCHAR2(100 CHAR), 
	"UACTUA" VARCHAR2(100 CHAR), 
	"FCREAC" TIMESTAMP (6), 
	"FACTUA" TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_TSI_SUITE" ;
