--------------------------------------------------------
--  Constraints for Table CONCEPTO_CLASE
--------------------------------------------------------

  ALTER TABLE "USR_TSI_SUITE"."CONCEPTO_CLASE" MODIFY ("ID_CIA" NOT NULL ENABLE);
  ALTER TABLE "USR_TSI_SUITE"."CONCEPTO_CLASE" MODIFY ("CODCON" NOT NULL ENABLE);
  ALTER TABLE "USR_TSI_SUITE"."CONCEPTO_CLASE" MODIFY ("CLASE" NOT NULL ENABLE);
  ALTER TABLE "USR_TSI_SUITE"."CONCEPTO_CLASE" ADD CONSTRAINT "PK_CONCEPTO_CLASE" PRIMARY KEY ("ID_CIA", "CODCON", "CLASE", "CODIGO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_TSI_SUITE"  ENABLE;
