--------------------------------------------------------
--  Ref Constraints for Table CONCEPTO_FUNCION
--------------------------------------------------------

  ALTER TABLE "USR_TSI_SUITE"."CONCEPTO_FUNCION" ADD CONSTRAINT "FK_CONCEPTO_FUNCION_FUNCION_PLANILLA" FOREIGN KEY ("ID_CIA", "CODFUN")
	  REFERENCES "USR_TSI_SUITE"."FUNCION_PLANILLA" ("ID_CIA", "CODFUN") ENABLE;
  ALTER TABLE "USR_TSI_SUITE"."CONCEPTO_FUNCION" ADD CONSTRAINT "FK_CONCEPTO_FUNCION_CONCEPTO" FOREIGN KEY ("ID_CIA", "CONORI")
	  REFERENCES "USR_TSI_SUITE"."CONCEPTO" ("ID_CIA", "CODCON") ENABLE;
