--------------------------------------------------------
--  DDL for Table CONTACTO
--------------------------------------------------------

  CREATE TABLE "USR_TSI_SUITE"."CONTACTO" 
   (	"ID_CIA" NUMBER(*,0), 
	"CODCONT" NUMBER(*,0), 
	"NOMCONT" VARCHAR2(100 CHAR), 
	"DIRECCION" VARCHAR2(100 CHAR), 
	"EMAIL" VARCHAR2(100 BYTE), 
	"TELEFONO" VARCHAR2(30 CHAR), 
	"HOBBY" VARCHAR2(30 BYTE), 
	"PALABRACLAVE" VARCHAR2(30 CHAR), 
	"OBSERVACION" VARCHAR2(1000 BYTE), 
	"CARGO" VARCHAR2(100 BYTE), 
	"FELICITACION" TIMESTAMP (6), 
	"CODDECI" NUMBER(*,0), 
	"CODPRO" NUMBER(*,0), 
	"CODTRA" NUMBER(*,0), 
	"CODREL" NUMBER(*,0), 
	"CODDEP" VARCHAR2(2 BYTE), 
	"CODPRV" VARCHAR2(2 BYTE), 
	"CODDIS" VARCHAR2(2 BYTE), 
	"FCREAC" TIMESTAMP (6), 
	"FACTUA" TIMESTAMP (6), 
	"USUARI" VARCHAR2(10 BYTE), 
	"SWACTI" CHAR(1 BYTE), 
	"DIDENT" VARCHAR2(20 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_TSI_SUITE" ;
