--------------------------------------------------------
--  DDL for Table CUENTAS_X_PAGAR
--------------------------------------------------------

  CREATE TABLE "USR_TSI_SUITE"."CUENTAS_X_PAGAR" 
   (	"ID_CIA" NUMBER(*,0), 
	"CODIGO" VARCHAR2(20 BYTE), 
	"CLIENTE" VARCHAR2(100 BYTE), 
	"TIPDOC" CHAR(50 BYTE), 
	"DOCUME" VARCHAR2(25 BYTE), 
	"REFERE01" VARCHAR2(25 BYTE), 
	"MES" VARCHAR2(25 BYTE), 
	"PERIODO" NUMBER(*,0), 
	"MESID" NUMBER(*,0), 
	"FEMISI" VARCHAR2(20 BYTE), 
	"FVENCI" VARCHAR2(20 BYTE), 
	"FECING" VARCHAR2(20 BYTE), 
	"DIAS" NUMBER(*,0), 
	"MONEDA" VARCHAR2(3 BYTE), 
	"IMPORTE" FLOAT(126), 
	"SALDO" FLOAT(126)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_TSI_SUITE" ;
