--------------------------------------------------------
--  DDL for Table CVENTAS_MES
--------------------------------------------------------

  CREATE TABLE "USR_TSI_SUITE"."CVENTAS_MES" 
   (	"ID_CIA" NUMBER(*,0), 
	"TIPDOC" VARCHAR2(50 BYTE), 
	"SUCURSAL" VARCHAR2(50 BYTE), 
	"MES" VARCHAR2(50 BYTE), 
	"PERIODO" NUMBER(*,0), 
	"MESID" NUMBER(*,0), 
	"SERIES" VARCHAR2(10 BYTE), 
	"NUMDOC" NUMBER(*,0), 
	"FEMISI" TIMESTAMP (6), 
	"TIPCAM" NUMBER(8,4), 
	"CODCLI" VARCHAR2(20 BYTE), 
	"CLIENTE" VARCHAR2(100 BYTE), 
	"RUC" VARCHAR2(50 BYTE), 
	"DESPAG" VARCHAR2(50 BYTE), 
	"VENDEDOR" VARCHAR2(50 BYTE), 
	"MONEDA" VARCHAR2(50 BYTE), 
	"CANTI" NUMBER(16,4), 
	"FACCON" NUMBER(12,5), 
	"TONELADAS" NUMBER(10,3), 
	"VNTSOL" NUMBER(16,2), 
	"VNTDOL" NUMBER(16,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_TSI_SUITE" ;
