--------------------------------------------------------
--  DDL for Table DCTA100_LOG
--------------------------------------------------------

  CREATE TABLE "USR_TSI_SUITE"."DCTA100_LOG" 
   (	"ID_CIA" NUMBER(*,0), 
	"NUMINTORI" NUMBER(*,0), 
	"NUMINTDES" NUMBER(*,0), 
	"OBSERV" VARCHAR2(1000 BYTE), 
	"FCREAC" TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_TSI_SUITE" ;
