--------------------------------------------------------
--  DDL for Table DCTA100_ORI
--------------------------------------------------------

  CREATE TABLE "USR_TSI_SUITE"."DCTA100_ORI" 
   (	"ID_CIA" NUMBER(*,0), 
	"NUMINT" NUMBER(*,0), 
	"OPERAC" NUMBER(*,0), 
	"CODBAN" NUMBER(*,0), 
	"NUMBCO" VARCHAR2(50 BYTE), 
	"PROTES" NUMBER(*,0), 
	"SALDO" NUMBER(16,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_TSI_SUITE" ;
