--------------------------------------------------------
--  DDL for Table DCTA104
--------------------------------------------------------

  CREATE TABLE "USR_TSI_SUITE"."DCTA104" 
   (	"ID_CIA" NUMBER(*,0), 
	"LIBRO" VARCHAR2(3 BYTE), 
	"PERIODO" NUMBER(*,0), 
	"MES" NUMBER(*,0), 
	"SECUENCIA" NUMBER(*,0), 
	"ITEM" NUMBER(*,0), 
	"TIPDEP" NUMBER(*,0), 
	"DOCCAN" VARCHAR2(15 BYTE), 
	"CUENTA" VARCHAR2(16 BYTE), 
	"DH" CHAR(1 BYTE), 
	"TIPMON" VARCHAR2(5 BYTE), 
	"CODBAN" VARCHAR2(6 BYTE), 
	"OP" VARCHAR2(20 BYTE), 
	"AGENCIA" VARCHAR2(20 BYTE), 
	"TIPCAM" NUMBER(9,6), 
	"DEPOSITO" NUMBER(9,2), 
	"TCAMB01" NUMBER(14,6), 
	"TCAMB02" NUMBER(16,6), 
	"IMPOR01" NUMBER(16,2), 
	"IMPOR02" NUMBER(16,2), 
	"PAGOMN" NUMBER(16,2), 
	"PAGOME" NUMBER(16,2), 
	"SITUAC" CHAR(1 BYTE), 
	"CONCEP" VARCHAR2(150 BYTE), 
	"CODIGO" VARCHAR2(20 CHAR), 
	"RAZON" VARCHAR2(100 CHAR), 
	"TDOCUM" VARCHAR2(2 CHAR), 
	"SERIE" VARCHAR2(20 CHAR), 
	"NUMERO" VARCHAR2(20 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_TSI_SUITE" ;
