--------------------------------------------------------
--  DDL for Table DCTA106
--------------------------------------------------------

  CREATE TABLE "USR_TSI_SUITE"."DCTA106" 
   (	"ID_CIA" NUMBER(*,0), 
	"NUMINT" NUMBER(*,0), 
	"NUMINTAP" NUMBER(*,0), 
	"ITEM" NUMBER(*,0), 
	"ID" CHAR(1 BYTE), 
	"CODCLI" VARCHAR2(20 BYTE), 
	"TIPDOC" NUMBER(*,0), 
	"DOCUME" VARCHAR2(25 BYTE), 
	"PERIODO" NUMBER(*,0), 
	"MES" NUMBER(*,0), 
	"FEMISI" DATE, 
	"FVENCI" DATE, 
	"FCANCE" DATE, 
	"REFERE01" VARCHAR2(25 BYTE), 
	"REFERE02" VARCHAR2(25 BYTE), 
	"TIPMON" VARCHAR2(5 BYTE), 
	"IMPORTE" NUMBER(16,2), 
	"IMPORTEMN" NUMBER(16,2), 
	"IMPORTEME" NUMBER(16,2), 
	"CONCPAG" NUMBER(*,0), 
	"CODVEN" NUMBER(*,0), 
	"CODSUC" NUMBER(*,0), 
	"FCREAC" DATE, 
	"FACTUA" DATE, 
	"USUARI" VARCHAR2(10 BYTE), 
	"SITUAC" CHAR(1 BYTE), 
	"TIPCAM" NUMBER(14,6), 
	"OPERAC" NUMBER(*,0), 
	"CODUBI" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_TSI_SUITE" ;
