--------------------------------------------------------
--  DDL for Table DCTA105
--------------------------------------------------------

  CREATE TABLE "USR_TSI_SUITE"."DCTA105" 
   (	"ID_CIA" NUMBER(*,0), 
	"TIPDOC" NUMBER(*,0), 
	"SERIES" VARCHAR2(20 BYTE), 
	"NUMDOC" NUMBER(*,0), 
	"LIBRO" VARCHAR2(3 BYTE), 
	"PERIODO" NUMBER(*,0), 
	"MES" NUMBER(*,0), 
	"SECUENCIA" NUMBER(*,0), 
	"CODCLI" VARCHAR2(20 BYTE), 
	"FEMISI" DATE, 
	"FVENCI" DATE, 
	"REFERE" VARCHAR2(25 BYTE), 
	"TIPMON" VARCHAR2(5 BYTE), 
	"TIPCAM" NUMBER(16,6), 
	"IMPORTE" NUMBER(16,2), 
	"IMPORTEMN" NUMBER(16,2), 
	"IMPORTEME" NUMBER(16,2), 
	"TCAMB01" NUMBER(16,6), 
	"TCAMB02" NUMBER(16,6), 
	"IMPOR01" NUMBER(16,2), 
	"IMPOR02" NUMBER(16,2), 
	"CODCOB" NUMBER(*,0), 
	"COMISI" NUMBER(14,4), 
	"CODSUC" NUMBER(*,0), 
	"FCREAC" DATE, 
	"FACTUA" DATE, 
	"USUARI" VARCHAR2(10 BYTE), 
	"SITUAC" CHAR(1 BYTE), 
	"CUENTA" VARCHAR2(16 BYTE), 
	"DH" CHAR(1 BYTE), 
	"CODBAN" VARCHAR2(3 BYTE), 
	"NUMINT" NUMBER(*,0), 
	"CODVEN" NUMBER(*,0), 
	"OBSERV" VARCHAR2(1000 BYTE), 
	"TIPCAN" NUMBER(*,0), 
	"REFERE02" VARCHAR2(25 BYTE), 
	"CONCEP" VARCHAR2(150 BYTE), 
	"CODAVAL01" VARCHAR2(20 BYTE), 
	"CODAVAL02" VARCHAR2(20 BYTE), 
	"CODAVAL03" VARCHAR2(20 BYTE), 
	"OPERAC" NUMBER(*,0), 
	"CODACEP" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_TSI_SUITE" ;
