--------------------------------------------------------
--  DDL for Table DCTA102_CAJA_CAB
--------------------------------------------------------

  CREATE TABLE "USR_TSI_SUITE"."DCTA102_CAJA_CAB" 
   (	"ID_CIA" NUMBER(*,0), 
	"NUMCAJA" NUMBER(*,0), 
	"CODUSER" VARCHAR2(10 BYTE), 
	"FINICIO" DATE, 
	"FTERMINO" DATE, 
	"TIPCAMCOM" NUMBER(10,6), 
	"TIPCAMVEN" NUMBER(10,6), 
	"FCREAC" TIMESTAMP (6), 
	"FACTUA" TIMESTAMP (6), 
	"CODUSERCREA" VARCHAR2(10 BYTE), 
	"CODUSERACTU" VARCHAR2(10 BYTE), 
	"SITUAC" NUMBER(*,0), 
	"CODSUC" NUMBER(*,0), 
	"OBSERV" VARCHAR2(3000 BYTE), 
	"CAJUBI" NUMBER(*,0), 
	"CODTUR" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_TSI_SUITE" ;
