--------------------------------------------------------
--  DDL for Table DCTA101
--------------------------------------------------------

  CREATE TABLE "USR_TSI_SUITE"."DCTA101" 
   (	"ID_CIA" NUMBER(*,0), 
	"NUMINT" NUMBER(*,0), 
	"NUMITE" NUMBER(*,0), 
	"FPROCE" DATE, 
	"LIBRO" VARCHAR2(3 BYTE), 
	"PERIODO" NUMBER(*,0), 
	"MES" NUMBER(*,0), 
	"SECUENCIA" NUMBER(*,0), 
	"ITEM" NUMBER(*,0), 
	"TIPCAN" NUMBER(*,0), 
	"DOCCAN" VARCHAR2(25 BYTE), 
	"OPERAC" VARCHAR2(2 BYTE), 
	"CODBAN" NUMBER(*,0), 
	"NUMBCO" VARCHAR2(50 BYTE), 
	"CODCOB" NUMBER(*,0), 
	"TIPOPE" NUMBER(*,0), 
	"CUENTA" VARCHAR2(16 BYTE), 
	"DH" CHAR(1 BYTE), 
	"TIPMON" VARCHAR2(5 BYTE), 
	"IMPORTE" NUMBER(16,2), 
	"IMPOR01" NUMBER(16,2), 
	"IMPOR02" NUMBER(16,2), 
	"TCAMB01" NUMBER(14,6), 
	"TCAMB02" NUMBER(16,6), 
	"DIFCAM" NUMBER(16,2), 
	"COMISI" NUMBER(16,2), 
	"CODSUC" NUMBER(*,0), 
	"FCREAC" DATE, 
	"FACTUA" DATE, 
	"USUARI" VARCHAR2(10 BYTE), 
	"SITUAC" CHAR(1 BYTE), 
	"FEMISI" DATE, 
	"CODCLI" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_TSI_SUITE" ;
