--------------------------------------------------------
--  DDL for Trigger DESPUES_INSERTAR_MOVIMIENTOS
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "USR_TSI_SUITE"."DESPUES_INSERTAR_MOVIMIENTOS" 
AFTER INSERT ON "USR_TSI_SUITE".MOVIMIENTOS 
FOR EACH ROW
DECLARE
  WCCOSTO    VARCHAR(16);
  WCUENTA    VARCHAR(16);
  WDESTIND   VARCHAR(16);
  WDESTINH   VARCHAR(16);
  SWDESTINO  VARCHAR(1);
  SWCCOSTO   VARCHAR(1);
  WSITEM     INTEGER;
  WFECING    TIMESTAMP;
  WFECSAL    TIMESTAMP;
  WNOGENDES  VARCHAR(1);

  V_ITEM NUMBER;

BEGIN

    -- EL TRIGGER SE IMPLEMENTO EN UN PROCEDIMIENTO CON EL MISMO NOMBRE POR EL PROBLEMA GENERADO ( BLUCE INFINITO )
    -- PROCEDURE DESPUES_INSERTAR_MOVIMIENTOS 

    NULL;

END;

/
ALTER TRIGGER "USR_TSI_SUITE"."DESPUES_INSERTAR_MOVIMIENTOS" ENABLE;
