--------------------------------------------------------
--  DDL for Table DOCUMENTOS_CAB_ENVIO_SUNAT_LOG
--------------------------------------------------------

  CREATE TABLE "USR_TSI_SUITE"."DOCUMENTOS_CAB_ENVIO_SUNAT_LOG" 
   (	"ID_CIA" NUMBER, 
	"LOCALI" NUMBER, 
	"NUMINT" NUMBER, 
	"FENVIO" TIMESTAMP (6), 
	"FRESPUESTA" TIMESTAMP (6), 
	"ESTADO" NUMBER(*,0), 
	"NUMTICKET" VARCHAR2(100 CHAR), 
	"FCREAC" TIMESTAMP (6), 
	"MENSAJE" VARCHAR2(1000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_TSI_SUITE" ;
