--------------------------------------------------------
--  DDL for Table DOCUMENTOS
--------------------------------------------------------

  CREATE TABLE "USR_TSI_SUITE"."DOCUMENTOS" 
   (	"ID_CIA" NUMBER(*,0), 
	"CODIGO" NUMBER(*,0), 
	"SERIES" VARCHAR2(5 BYTE), 
	"TIPINV" NUMBER(*,0), 
	"CODALM" NUMBER(*,0), 
	"CODSUC" NUMBER(*,0), 
	"LIBRO" VARCHAR2(3 BYTE), 
	"CUENTA" VARCHAR2(16 BYTE), 
	"DOCID" NUMBER(*,0), 
	"DOCDEF" CHAR(1 BYTE), 
	"DESCRI" VARCHAR2(30 BYTE), 
	"CORREL" NUMBER(*,0), 
	"NOMSER" VARCHAR2(40 BYTE), 
	"SWCORR" CHAR(1 BYTE), 
	"USUARI" VARCHAR2(10 BYTE), 
	"FCREAC" TIMESTAMP (6), 
	"FACTUA" TIMESTAMP (6), 
	"SWACTI" CHAR(1 BYTE), 
	"LPT" NUMBER(*,0), 
	"COMPAGO" CHAR(1 BYTE), 
	"KARDEX" CHAR(1 BYTE), 
	"CANITEM" NUMBER(*,0), 
	"FILART" VARCHAR2(5 BYTE), 
	"VISACHKCRED" VARCHAR2(1 BYTE), 
	"DESPOBLAPRO" VARCHAR2(1 BYTE), 
	"ACTCORR" NUMBER(*,0), 
	"DOCELEC" CHAR(1 BYTE), 
	"TIPIMP" VARCHAR2(3 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_TSI_SUITE" ;
