--------------------------------------------------------
--  DDL for Table DOCUMENTOS_CAB_LOG
--------------------------------------------------------

  CREATE TABLE "USR_TSI_SUITE"."DOCUMENTOS_CAB_LOG" 
   (	"ID_CIA" NUMBER(*,0), 
	"LOCALI" NUMBER(*,0), 
	"NUMINT" NUMBER(*,0), 
	"TIPDOC" NUMBER(*,0), 
	"SERIES" VARCHAR2(5 BYTE), 
	"NUMDOC" NUMBER(*,0), 
	"FEMISI" DATE, 
	"SITUAC" CHAR(1 BYTE), 
	"CODCLI" VARCHAR2(20 BYTE), 
	"TIPMON" VARCHAR2(5 BYTE), 
	"TIPCAM" NUMBER(10,6), 
	"TOTBRU" NUMBER(16,2), 
	"DESCUE" NUMBER(16,2), 
	"DESESP" NUMBER(16,2), 
	"MONAFE" NUMBER(16,2), 
	"MONINA" NUMBER(16,2), 
	"PORIGV" NUMBER(16,2), 
	"MONIGV" NUMBER(16,2), 
	"PREVEN" NUMBER(16,2), 
	"FCREAC" TIMESTAMP (6), 
	"USUARI" VARCHAR2(10 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_TSI_SUITE" ;
