--------------------------------------------------------
--  DDL for Table DOCUMENTOS_CAB_FACTOR_TIPCAM
--------------------------------------------------------

  CREATE TABLE "USR_TSI_SUITE"."DOCUMENTOS_CAB_FACTOR_TIPCAM" 
   (	"ID_CIA" NUMBER(*,0), 
	"NUMINT" NUMBER(*,0), 
	"TIPMON" VARCHAR2(5 BYTE), 
	"TIPCAM" NUMBER(14,6), 
	"FACTOR" NUMBER(14,6), 
	"FECHA" DATE, 
	"REFERE" VARCHAR2(20 BYTE), 
	"CONCEP" VARCHAR2(100 BYTE), 
	"NEWTIPCAM" NUMBER(12,6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_TSI_SUITE" ;
