--------------------------------------------------------
--  Ref Constraints for Table DSCTOPRESTAMO
--------------------------------------------------------

  ALTER TABLE "USR_TSI_SUITE"."DSCTOPRESTAMO" ADD CONSTRAINT "FK_DSCTOPRESTAMO_PRESTAMO" FOREIGN KEY ("ID_CIA", "ID_PRE")
	  REFERENCES "USR_TSI_SUITE"."PRESTAMO" ("ID_CIA", "ID_PRE") ENABLE;
  ALTER TABLE "USR_TSI_SUITE"."DSCTOPRESTAMO" ADD CONSTRAINT "FK_DSCTOPRESTAMO_PERSONAL" FOREIGN KEY ("ID_CIA", "CODPER")
	  REFERENCES "USR_TSI_SUITE"."PERSONAL" ("ID_CIA", "CODPER") ENABLE;
