--------------------------------------------------------
--  DDL for Table DW_CVENTAS_VENDEDOR_CARTERA_X_DIA
--------------------------------------------------------

  CREATE TABLE "USR_TSI_SUITE"."DW_CVENTAS_VENDEDOR_CARTERA_X_DIA" 
   (	"ID_CIA" NUMBER(*,0), 
	"CODVEN" NUMBER(*,0), 
	"VENDEDOR" VARCHAR2(100 BYTE), 
	"ABREVI" VARCHAR2(10 BYTE), 
	"TIPDOC" NUMBER(*,0), 
	"TIPODOCUMENTO" VARCHAR2(100 BYTE), 
	"CODSUC" NUMBER(*,0), 
	"SUCURSAL" VARCHAR2(100 BYTE), 
	"PERIODO" NUMBER(*,0), 
	"MES" VARCHAR2(25 BYTE), 
	"DIASEMANA" VARCHAR2(25 BYTE), 
	"IDMES" NUMBER(*,0), 
	"MESID" NUMBER(*,0), 
	"FEMISI" DATE, 
	"CANTID" NUMBER(24,8), 
	"TONELADAS" NUMBER(24,8) DEFAULT 0, 
	"CSTSOL" NUMBER(24,8) DEFAULT 0, 
	"CSTDOL" NUMBER(24,8) DEFAULT 0, 
	"VNTSOL" NUMBER(24,8) DEFAULT 0, 
	"VNTDOL" NUMBER(24,8) DEFAULT 0, 
	"IGVSOL" NUMBER(24,8), 
	"IGVDOL" NUMBER(24,8)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_TSI_SUITE" ;
