--------------------------------------------------------
--  DDL for Table DW_CVENTAS_MENSUAL_META
--------------------------------------------------------

  CREATE TABLE "USR_TSI_SUITE"."DW_CVENTAS_MENSUAL_META" 
   (	"ID_CIA" NUMBER, 
	"CODSUC" NUMBER(*,0), 
	"PERIODO" NUMBER, 
	"MES" VARCHAR2(25 BYTE), 
	"IDMES" NUMBER(*,0), 
	"MESID" NUMBER(*,0), 
	"META01" NUMBER(20,8) DEFAULT 0, 
	"META02" NUMBER(20,8) DEFAULT 0, 
	"UCREAC" VARCHAR2(10 BYTE), 
	"UACTUA" VARCHAR2(10 BYTE), 
	"FCREAC" TIMESTAMP (6), 
	"FACTUA" TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_TSI_SUITE" ;
