--------------------------------------------------------
--  DDL for Table DW_TIPODOCUMENTO
--------------------------------------------------------

  CREATE TABLE "USR_TSI_SUITE"."DW_TIPODOCUMENTO" 
   (	"TIPDOC" NUMBER, 
	"DESDOC" VARCHAR2(250 CHAR), 
	"SIGNO" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_TSI_SUITE" ;
