--------------------------------------------------------
--  DDL for Table ETIQUETAS_ACTIVAS_2
--------------------------------------------------------

  CREATE TABLE "USR_TSI_SUITE"."ETIQUETAS_ACTIVAS_2" 
   (	"ID_CIA" NUMBER(*,0), 
	"TIPINV" NUMBER(*,0), 
	"DTIPINV" VARCHAR2(50 BYTE), 
	"CODART" VARCHAR2(40 BYTE), 
	"DESART" VARCHAR2(100 BYTE), 
	"ETIQUETA" VARCHAR2(100 BYTE), 
	"CANTD_ORI" NUMBER(11,4), 
	"STOCK" NUMBER(11,4), 
	"CODALM" NUMBER(*,0), 
	"DESALM" VARCHAR2(50 BYTE), 
	"UBICA" VARCHAR2(10 BYTE), 
	"DESUBICA" VARCHAR2(50 BYTE), 
	"CODADD01" VARCHAR2(20 BYTE), 
	"DCODADD01" VARCHAR2(100 BYTE), 
	"CODADD02" VARCHAR2(20 BYTE), 
	"DCODADD02" VARCHAR2(100 BYTE), 
	"FINGRESO" DATE, 
	"FSALIDA" DATE, 
	"FCOMPRA" DATE, 
	"FVENTA" DATE, 
	"FCONSUMO" DATE, 
	"DIAS_ULTMOV" NUMBER(*,0), 
	"MOT_ULTMOV" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_TSI_SUITE" ;
