--------------------------------------------------------
--  DDL for Table EXCELDINAMICO
--------------------------------------------------------

  CREATE TABLE "USR_TSI_SUITE"."EXCELDINAMICO" 
   (	"ID_CIA" NUMBER(*,0), 
	"CODIGO" NUMBER(*,0), 
	"DESCRI" VARCHAR2(200 CHAR) DEFAULT NULL, 
	"CADSQL" LONG, 
	"OBSERV" VARCHAR2(3000 BYTE), 
	"NLIBRO" VARCHAR2(200 CHAR) DEFAULT NULL, 
	"TIPBD" NUMBER(*,0) DEFAULT 0, 
	"PARAMS" VARCHAR2(1600 BYTE), 
	"SWTABD" CHAR(1 BYTE) DEFAULT 'N', 
	"SWSISTEMA" VARCHAR2(1 BYTE) DEFAULT 'N'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_TSI_SUITE" ;
