--------------------------------------------------------
--  DDL for Table FACTOR_AFP
--------------------------------------------------------

  CREATE TABLE "USR_TSI_SUITE"."FACTOR_AFP" 
   (	"ID_CIA" NUMBER, 
	"ANIO" NUMBER(*,0), 
	"MES" NUMBER(*,0), 
	"CODFAC" VARCHAR2(3 BYTE), 
	"CODAFP" VARCHAR2(4 BYTE), 
	"VALFA1" NUMBER(15,4), 
	"VALFA2" NUMBER(15,4), 
	"FCREAC" TIMESTAMP (6), 
	"FACTUA" TIMESTAMP (6), 
	"UCREAC" VARCHAR2(10 BYTE), 
	"UACTUA" VARCHAR2(10 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_TSI_SUITE" ;
