--------------------------------------------------------
--  DDL for Table FACTOR_PLANILLA
--------------------------------------------------------

  CREATE TABLE "USR_TSI_SUITE"."FACTOR_PLANILLA" 
   (	"ID_CIA" NUMBER, 
	"CODFAC" VARCHAR2(3 BYTE), 
	"NOMBRE" VARCHAR2(50 BYTE), 
	"VALFA1" NUMBER(15,4), 
	"VALFA2" NUMBER(15,4), 
	"TIPFAC" VARCHAR2(1 BYTE), 
	"INDAFP" VARCHAR2(1 BYTE), 
	"UCREAC" VARCHAR2(10 BYTE), 
	"UACTUA" VARCHAR2(10 BYTE), 
	"FCREAC" TIMESTAMP (6), 
	"FACTUA" TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_TSI_SUITE" ;
