--------------------------------------------------------
--  Constraints for Table FACTOR_AFP
--------------------------------------------------------

  ALTER TABLE "USR_TSI_SUITE"."FACTOR_AFP" MODIFY ("ID_CIA" NOT NULL ENABLE);
  ALTER TABLE "USR_TSI_SUITE"."FACTOR_AFP" MODIFY ("ANIO" NOT NULL ENABLE);
  ALTER TABLE "USR_TSI_SUITE"."FACTOR_AFP" MODIFY ("MES" NOT NULL ENABLE);
  ALTER TABLE "USR_TSI_SUITE"."FACTOR_AFP" MODIFY ("CODFAC" NOT NULL ENABLE);
  ALTER TABLE "USR_TSI_SUITE"."FACTOR_AFP" MODIFY ("CODAFP" NOT NULL ENABLE);
  ALTER TABLE "USR_TSI_SUITE"."FACTOR_AFP" ADD CONSTRAINT "PK_FACTOR_AFP" PRIMARY KEY ("ID_CIA", "ANIO", "MES", "CODFAC", "CODAFP")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_TSI_SUITE"  ENABLE;
