--------------------------------------------------------
--  DDL for Table GUIA_CAB
--------------------------------------------------------

  CREATE TABLE "USR_TSI_SUITE"."GUIA_CAB" 
   (	"ID_CIA" NUMBER(*,0), 
	"TIPDOC" NUMBER(*,0), 
	"SERIES" VARCHAR2(5 BYTE), 
	"NUMINT" NUMBER(*,0), 
	"NUMITE" NUMBER(*,0), 
	"NUMDOC" NUMBER(*,0), 
	"FEMISI" DATE, 
	"ID" NUMBER(*,0), 
	"MOTIVO" NUMBER(*,0), 
	"CODALM" NUMBER(*,0), 
	"ALMDES" NUMBER(*,0), 
	"CODCLI" VARCHAR2(20 BYTE), 
	"RUC" VARCHAR2(15 BYTE), 
	"RAZONC" VARCHAR2(50 BYTE), 
	"DIREC1" VARCHAR2(50 BYTE), 
	"CODENV" NUMBER(*,0), 
	"CODPAG" NUMBER(*,0), 
	"CODTRA" NUMBER(*,0), 
	"DESCUE" NUMBER(11,4), 
	"DESESP" NUMBER(11,4), 
	"PORIGV" NUMBER(11,4), 
	"MONIGV" NUMBER(11,4), 
	"PREVEN" NUMBER(11,4), 
	"TIPMON" NUMBER(11,4), 
	"OBSERV" VARCHAR2(1000 BYTE), 
	"FCREAC" TIMESTAMP (6), 
	"FACTUA" TIMESTAMP (6), 
	"USUARI" VARCHAR2(10 BYTE), 
	"SWACTI" CHAR(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_TSI_SUITE" ;
