--------------------------------------------------------
--  DDL for Table HISTOSTO
--------------------------------------------------------

  CREATE TABLE "USR_TSI_SUITE"."HISTOSTO" 
   (	"ID_CIA" NUMBER(*,0), 
	"NUMINTORI" NUMBER(*,0), 
	"NUMITEORI" NUMBER(*,0), 
	"CARGO" VARCHAR2(10 BYTE), 
	"CODART" VARCHAR2(40 BYTE), 
	"TIPO" NUMBER(*,0), 
	"NUMINTDES" NUMBER(*,0), 
	"NUMITEDES" NUMBER(*,0), 
	"ORDEN" VARCHAR2(10 BYTE), 
	"SECCION" VARCHAR2(3 BYTE), 
	"CANTID" NUMBER(11,3), 
	"FECPRO" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_TSI_SUITE" ;
