--------------------------------------------------------
--  DDL for Index IDX_ETIQUETA_BUSCAR
--------------------------------------------------------

  CREATE UNIQUE INDEX "USR_TSI_SUITE"."IDX_ETIQUETA_BUSCAR" ON "USR_TSI_SUITE"."KARDEX001" ("ID_CIA", "ETIQUETA", "TIPINV", "CODART", "CODADD01", "CODADD02", "CODALM", "UBICA", "ANCHO", "LARGO", "INGRESO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_TSI_SUITE" ;
