--------------------------------------------------------
--  DDL for Table KANBAN_DET_CODADD
--------------------------------------------------------

  CREATE TABLE "USR_TSI_SUITE"."KANBAN_DET_CODADD" 
   (	"ID_CIA" NUMBER(*,0), 
	"CODKAN" VARCHAR2(20 BYTE), 
	"TIPINV" NUMBER(*,0), 
	"CODART" VARCHAR2(40 BYTE), 
	"CODADD01" VARCHAR2(10 BYTE), 
	"CODADD02" VARCHAR2(10 BYTE), 
	"CODALM" NUMBER(*,0), 
	"CANTID" NUMBER(16,4), 
	"CANTIDMIN" NUMBER(16,4), 
	"CANTIDMAX" NUMBER(16,4), 
	"SWACTI" CHAR(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_TSI_SUITE" ;
