--------------------------------------------------------
--  DDL for Table KARDEX000
--------------------------------------------------------

  CREATE TABLE "USR_TSI_SUITE"."KARDEX000" 
   (	"ID_CIA" NUMBER(*,0), 
	"ETIQUETA" VARCHAR2(100 BYTE), 
	"LOCALI" NUMBER(*,0), 
	"TIPINV" NUMBER(*,0), 
	"CODART" VARCHAR2(40 BYTE), 
	"CODALM" NUMBER(*,0), 
	"CANTID" NUMBER(16,4), 
	"COSTOT01" NUMBER(16,2), 
	"COSTOT02" NUMBER(16,2), 
	"NUMINT" NUMBER(*,0), 
	"NUMITE" NUMBER(*,0), 
	"CODMOT" NUMBER(*,0), 
	"FINGRESO" TIMESTAMP (6), 
	"CODUSERCREA" VARCHAR2(10 BYTE), 
	"CODUSERACTU" VARCHAR2(10 BYTE), 
	"FCREAC" TIMESTAMP (6), 
	"FACTUA" TIMESTAMP (6), 
	"CANTID_AP" NUMBER(16,4), 
	"COSTOT01_AP" NUMBER(16,2), 
	"COSTOT02_AP" NUMBER(16,2), 
	"DAM" VARCHAR2(25 BYTE) DEFAULT NULL, 
	"PLACA" VARCHAR2(10 BYTE) DEFAULT NULL, 
	"DAM_ITEM" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_TSI_SUITE" ;
