--------------------------------------------------------
--  DDL for Table KARDEX002
--------------------------------------------------------

  CREATE TABLE "USR_TSI_SUITE"."KARDEX002" 
   (	"ID_CIA" NUMBER(*,0), 
	"TIPINV" NUMBER(*,0), 
	"CODART" VARCHAR2(40 BYTE), 
	"ETIQUETA" VARCHAR2(100 BYTE), 
	"FINGRE" DATE, 
	"NUMINT" NUMBER(*,0), 
	"SERIE" VARCHAR2(5 BYTE), 
	"NUMDOC" NUMBER(*,0), 
	"CANTINI" NUMBER(11,4), 
	"ROYOINI" NUMBER(11,4), 
	"COSINI01" NUMBER(16,5), 
	"COSINI02" NUMBER(16,5), 
	"COSAJU01" NUMBER(16,5), 
	"COSAJU02" NUMBER(16,5), 
	"CONTROL" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_TSI_SUITE" ;
