--------------------------------------------------------
--  DDL for Table KARDEX001
--------------------------------------------------------

  CREATE TABLE "USR_TSI_SUITE"."KARDEX001" 
   (	"ID_CIA" NUMBER(*,0), 
	"TIPINV" NUMBER(*,0), 
	"CODART" VARCHAR2(40 BYTE), 
	"CODALM" NUMBER(*,0), 
	"ETIQUETA" VARCHAR2(100 BYTE), 
	"SUCURSAL" NUMBER(*,0), 
	"OPNUMDOC" VARCHAR2(30 BYTE), 
	"OPTRAMO" NUMBER(*,0), 
	"CODCLI" VARCHAR2(20 BYTE), 
	"INGRESO" NUMBER(11,4), 
	"SALIDA" NUMBER(11,4), 
	"FINGRESO" TIMESTAMP (6), 
	"FSALIDA" TIMESTAMP (6), 
	"KANBAN" VARCHAR2(50 BYTE), 
	"NUMINT" NUMBER(*,0), 
	"NUMITE" NUMBER(*,0), 
	"ROYOING" NUMBER(16,5), 
	"ROYOSAL" NUMBER(16,5), 
	"UBICA" VARCHAR2(10 BYTE), 
	"SWACTI" NUMBER(*,0), 
	"CANTID_ORI" NUMBER(11,4), 
	"SWINGORI" NUMBER(*,0), 
	"CODADD01" VARCHAR2(10 BYTE), 
	"CODADD02" VARCHAR2(10 BYTE), 
	"LOTE" VARCHAR2(20 BYTE), 
	"NROCARRETE" VARCHAR2(20 BYTE), 
	"COMBINA" VARCHAR2(20 BYTE), 
	"EMPALME" VARCHAR2(20 BYTE), 
	"ANCHO" NUMBER(9,3), 
	"DISENO" VARCHAR2(20 BYTE), 
	"ACABADO" VARCHAR2(20 BYTE), 
	"FVENCI" DATE, 
	"FMANUF" DATE, 
	"LARGO" NUMBER(9,3), 
	"CHASIS" VARCHAR2(20 CHAR), 
	"MOTOR" VARCHAR2(20 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_TSI_SUITE" ;
