--------------------------------------------------------
--  DDL for Table LIQUIHEA
--------------------------------------------------------

  CREATE TABLE "USR_TSI_SUITE"."LIQUIHEA" 
   (	"ID_CIA" NUMBER(*,0), 
	"TIPO" NUMBER(*,0), 
	"DOCUME" NUMBER(*,0), 
	"ANNO" NUMBER(*,0), 
	"MES" NUMBER(*,0), 
	"CODIGO" VARCHAR2(20 BYTE), 
	"NOMBRE" VARCHAR2(120 BYTE), 
	"MOTIVO" CHAR(3 BYTE), 
	"CONCEP" VARCHAR2(150 BYTE), 
	"FECHA" TIMESTAMP (6), 
	"FECINI" TIMESTAMP (6), 
	"FECFIN" TIMESTAMP (6), 
	"MONEDA" CHAR(3 BYTE), 
	"TCAMBIO01" NUMBER(14,6), 
	"TCAMBIO02" NUMBER(14,6), 
	"OBSERVA" VARCHAR2(1000 BYTE), 
	"CUENTA" VARCHAR2(16 BYTE), 
	"IMPORTE" NUMBER(16,2), 
	"ACUENTA" NUMBER(16,2), 
	"TOTAL" NUMBER(16,2), 
	"LINEAS" NUMBER(*,0), 
	"APROBA" VARCHAR2(10 BYTE), 
	"FAPROBA" TIMESTAMP (6), 
	"SITUAC" CHAR(1 BYTE), 
	"USROWN" VARCHAR2(10 BYTE), 
	"USUARI" VARCHAR2(10 BYTE), 
	"FCREAC" TIMESTAMP (6), 
	"FACTUA" TIMESTAMP (6), 
	"USRLCK" VARCHAR2(10 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_TSI_SUITE" ;
