--------------------------------------------------------
--  DDL for Table LIQUIDET
--------------------------------------------------------

  CREATE TABLE "USR_TSI_SUITE"."LIQUIDET" 
   (	"ID_CIA" NUMBER(*,0), 
	"TIPO" NUMBER(*,0), 
	"DOCUME" NUMBER(*,0), 
	"ITEM" NUMBER(*,0), 
	"ANNO" NUMBER(*,0), 
	"MES" NUMBER(*,0), 
	"CONCEP" VARCHAR2(75 BYTE), 
	"FECHA" TIMESTAMP (6), 
	"CODPRO" VARCHAR2(20 BYTE), 
	"RAZON" VARCHAR2(75 BYTE), 
	"TIDENT" CHAR(2 BYTE), 
	"DIDENT" VARCHAR2(16 BYTE), 
	"TDOCUM" CHAR(2 BYTE), 
	"SERIE" VARCHAR2(4 BYTE), 
	"NUMERO" VARCHAR2(12 BYTE), 
	"FEMISI" TIMESTAMP (6), 
	"DIAS" NUMBER(*,0), 
	"FVENCI" TIMESTAMP (6), 
	"OCOMPRA" VARCHAR2(20 BYTE), 
	"OBSERVA" VARCHAR2(1000 BYTE), 
	"DESTINO" NUMBER(*,0), 
	"MONEDA" CHAR(3 BYTE), 
	"FACTOR" VARCHAR2(11 BYTE), 
	"IMPORTE" NUMBER(16,2), 
	"IMPOR01" NUMBER(16,2), 
	"IMPOR02" NUMBER(16,2), 
	"TCAMBIO01" NUMBER(14,6), 
	"TCAMBIO02" NUMBER(14,6), 
	"CODIGV" CHAR(1 BYTE), 
	"PORIGV" NUMBER(6,2), 
	"IGV" NUMBER(16,2), 
	"IGV01" NUMBER(16,2), 
	"IGV02" NUMBER(16,2), 
	"LIBRO" CHAR(3 BYTE), 
	"ASIENTO" NUMBER(*,0), 
	"DH" CHAR(1 BYTE), 
	"CUENTA" VARCHAR2(16 BYTE), 
	"CCOSTO" VARCHAR2(16 BYTE), 
	"PROYEC" VARCHAR2(16 BYTE), 
	"SITUAC" CHAR(1 BYTE), 
	"USUARI" VARCHAR2(10 BYTE), 
	"FCREAC" TIMESTAMP (6), 
	"FACTUA" TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_TSI_SUITE" ;
