--------------------------------------------------------
--  DDL for Table M_PAGO
--------------------------------------------------------

  CREATE TABLE "USR_TSI_SUITE"."M_PAGO" 
   (	"ID_CIA" NUMBER(*,0), 
	"CODIGO" NUMBER(*,0), 
	"DESCRI" VARCHAR2(50 BYTE), 
	"ABREVI" VARCHAR2(5 BYTE), 
	"SITUAC" CHAR(1 BYTE), 
	"TIPMON" VARCHAR2(3 BYTE), 
	"USUARI" VARCHAR2(10 BYTE), 
	"FCREAC" TIMESTAMP (6), 
	"FACTUA" TIMESTAMP (6), 
	"DH" VARCHAR2(1 BYTE), 
	"LIBRO" VARCHAR2(3 BYTE), 
	"DH2" VARCHAR2(1 BYTE), 
	"FILTRO" VARCHAR2(30 BYTE), 
	"SIGNO" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_TSI_SUITE" ;
