--------------------------------------------------------
--  DDL for Table MATERIALES_ESTANDAR
--------------------------------------------------------

  CREATE TABLE "USR_TSI_SUITE"."MATERIALES_ESTANDAR" 
   (	"ID_CIA" NUMBER(*,0), 
	"TIPINVPRO" NUMBER(*,0), 
	"CODARTPRO" VARCHAR2(40 BYTE), 
	"CODCLASE" VARCHAR2(20 BYTE), 
	"CODADD01PRO" VARCHAR2(10 BYTE), 
	"CODADD02PRO" VARCHAR2(10 BYTE), 
	"ITEM" NUMBER(*,0), 
	"TIPINVSTD" NUMBER(*,0), 
	"CODARTSTD" VARCHAR2(40 BYTE), 
	"ETAPA" NUMBER(*,0), 
	"ETAPAUSO" NUMBER(*,0), 
	"ACABADO" NUMBER(*,0), 
	"LARGO" NUMBER(9,3), 
	"ANCHO" NUMBER(9,3), 
	"FACTOR" NUMBER(9,5), 
	"CANTID" NUMBER(16,5), 
	"GLOSA" VARCHAR2(1000 BYTE), 
	"CODAUX" VARCHAR2(3 BYTE), 
	"SWACTI" VARCHAR2(1 BYTE), 
	"FCREAC" TIMESTAMP (6), 
	"FACTUA" TIMESTAMP (6), 
	"USUARI" VARCHAR2(10 BYTE), 
	"CANT_OJO" NUMBER(*,0), 
	"CANT_OJO_GCABLE" NUMBER(*,0), 
	"CODADD01STD" VARCHAR2(10 BYTE), 
	"CODADD02STD" VARCHAR2(10 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_TSI_SUITE" ;
