--------------------------------------------------------
--  DDL for Table MODULOS
--------------------------------------------------------

  CREATE TABLE "USR_TSI_SUITE"."MODULOS" 
   (	"ID_CIA" NUMBER(*,0), 
	"CODMOD" NUMBER(*,0), 
	"DESCRI" VARCHAR2(40 BYTE), 
	"SWACTI" CHAR(1 BYTE), 
	"DESEXE" VARCHAR2(30 BYTE), 
	"DETMOD" VARCHAR2(150 CHAR), 
	"VERSION" NUMBER(9,4)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_TSI_SUITE" ;
