--------------------------------------------------------
--  DDL for Table MOTIVOS
--------------------------------------------------------

  CREATE TABLE "USR_TSI_SUITE"."MOTIVOS" 
   (	"ID_CIA" NUMBER(*,0), 
	"TIPDOC" NUMBER(*,0), 
	"ID" CHAR(1 BYTE), 
	"CODMOT" NUMBER(*,0), 
	"DESMOT" VARCHAR2(50 BYTE), 
	"ABREVI" VARCHAR2(6 BYTE), 
	"COSTEA" CHAR(1 BYTE), 
	"COSPRO" CHAR(1 BYTE), 
	"GENING" CHAR(1 BYTE), 
	"GENSAL" CHAR(1 BYTE), 
	"REQPRE" CHAR(1 BYTE), 
	"FCREAC" TIMESTAMP (6), 
	"FACTUA" TIMESTAMP (6), 
	"USUARI" VARCHAR2(10 BYTE), 
	"SWACTI" CHAR(1 BYTE), 
	"TIPCLI" CHAR(1 BYTE), 
	"DOCAYUDA" NUMBER(*,0), 
	"FILTRODOCU" VARCHAR2(40 BYTE), 
	"OBSERV" VARCHAR2(1000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_TSI_SUITE" ;
