--------------------------------------------------------
--  Constraints for Table MOTIVOS_CLASE
--------------------------------------------------------

  ALTER TABLE "USR_TSI_SUITE"."MOTIVOS_CLASE" ADD CONSTRAINT "PK_MOTIVOS_CLASE" PRIMARY KEY ("ID_CIA", "TIPDOC", "ID", "CODMOT", "CODIGO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_TSI_SUITE"  ENABLE;
