--------------------------------------------------------
--  DDL for Table MOVIMIENTO_CTA_CTE_CAB
--------------------------------------------------------

  CREATE TABLE "USR_TSI_SUITE"."MOVIMIENTO_CTA_CTE_CAB" 
   (	"ID_CIA" NUMBER(*,0), 
	"TIPDOC" NUMBER(*,0), 
	"NUMINT" NUMBER(*,0), 
	"SERIES" VARCHAR2(5 BYTE), 
	"NUMDOC" NUMBER(*,0), 
	"NUMITE" NUMBER(*,0), 
	"FEMISI" DATE, 
	"FVENCIM" DATE, 
	"FPROCES" DATE, 
	"TIPMON" VARCHAR2(5 BYTE), 
	"IMPORTE_ORIGINAL" NUMBER(9,2), 
	"SALDO_ANTERIOR" NUMBER(9,2), 
	"SALDO_ACTUAL" NUMBER(9,2), 
	"PORCOMISI" NUMBER(9,2), 
	"COMISI" NUMBER(9,2), 
	"CODPAG" NUMBER(*,0), 
	"TIPCAM" NUMBER(9,2), 
	"CODVEN" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_TSI_SUITE" ;
