--------------------------------------------------------
--  DDL for Table MOVIMIENTOS_CONCILIACION_A
--------------------------------------------------------

  CREATE TABLE "USR_TSI_SUITE"."MOVIMIENTOS_CONCILIACION_A" 
   (	"ID_CIA" NUMBER(*,0), 
	"PERIODO" NUMBER(*,0), 
	"MES" NUMBER(*,0), 
	"CUENTA" VARCHAR2(16 BYTE), 
	"DEBE01" NUMBER(16,2), 
	"DEBE02" NUMBER(16,2), 
	"HABER01" NUMBER(16,2), 
	"HABER02" NUMBER(16,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_TSI_SUITE" ;
