--------------------------------------------------------
--  Ref Constraints for Table NOTIFICACION_PROGRAMADA_ADJUNTO
--------------------------------------------------------

  ALTER TABLE "USR_TSI_SUITE"."NOTIFICACION_PROGRAMADA_ADJUNTO" ADD CONSTRAINT "FK_NOTIFICACION_PROGRAMADA_ADJUNTO_NOTIFICACION_PROGRAMADA" FOREIGN KEY ("ID_CIA", "NUMINT")
	  REFERENCES "USR_TSI_SUITE"."NOTIFICACION_PROGRAMADA" ("ID_CIA", "NUMINT") ENABLE;
