--------------------------------------------------------
--  DDL for Table NOTICIAS
--------------------------------------------------------

  CREATE TABLE "USR_TSI_SUITE"."NOTICIAS" 
   (	"ID_CIA" NUMBER(*,0), 
	"NUMINT" NUMBER(*,0), 
	"TITULO" VARCHAR2(45 BYTE), 
	"ENCABEZADO" VARCHAR2(100 BYTE), 
	"INFORMACION" VARCHAR2(1000 BYTE), 
	"IMAGEN" BLOB, 
	"DESIMG" VARCHAR2(100 BYTE), 
	"FIRMA" VARCHAR2(60 BYTE), 
	"FDESDE" TIMESTAMP (6), 
	"FHASTA" TIMESTAMP (6), 
	"FEMISI" TIMESTAMP (6), 
	"USUARI" VARCHAR2(45 BYTE), 
	"SWACTI" VARCHAR2(5 BYTE), 
	"SWPOPUP" VARCHAR2(5 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_TSI_SUITE" 
 LOB ("IMAGEN") STORE AS SECUREFILE (
  TABLESPACE "TBS_TSI_SUITE" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
