--------------------------------------------------------
--  DDL for Table OPERACIONES
--------------------------------------------------------

  CREATE TABLE "USR_TSI_SUITE"."OPERACIONES" 
   (	"ID_CIA" NUMBER(*,0), 
	"CODIGO" NUMBER(*,0), 
	"DESCRI" VARCHAR2(30 BYTE), 
	"ABREVI" VARCHAR2(6 BYTE), 
	"DH" VARCHAR2(1 BYTE), 
	"LIBRO" VARCHAR2(3 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_TSI_SUITE" ;
