--------------------------------------------------------
--  DDL for Table OPERARIOS
--------------------------------------------------------

  CREATE TABLE "USR_TSI_SUITE"."OPERARIOS" 
   (	"ID_CIA" NUMBER(*,0), 
	"CODOPE" NUMBER(*,0), 
	"NOMBRE" VARCHAR2(30 BYTE), 
	"APELLIDO" VARCHAR2(30 BYTE), 
	"CODCAT" NUMBER(*,0), 
	"JORNAL" NUMBER(5,3), 
	"CODETA" NUMBER(*,0), 
	"FINGRES" DATE, 
	"FREINGR" DATE, 
	"FCREAC" TIMESTAMP (6), 
	"FACTUA" TIMESTAMP (6), 
	"USUARI" VARCHAR2(10 BYTE), 
	"SWACTI" CHAR(1 BYTE), 
	"EBANIS" CHAR(1 BYTE), 
	"ABREVI" CHAR(6 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_TSI_SUITE" ;
