--------------------------------------------------------
--  DDL for Table OPRODCOSTO
--------------------------------------------------------

  CREATE TABLE "USR_TSI_SUITE"."OPRODCOSTO" 
   (	"ID_CIA" NUMBER(*,0), 
	"NUMINT" NUMBER(*,0), 
	"NUMITE" NUMBER(*,0), 
	"TIPDOC" NUMBER(*,0), 
	"SERIES" VARCHAR2(5 BYTE), 
	"NUMDOC" NUMBER(*,0), 
	"CARGO" VARCHAR2(10 BYTE), 
	"PREVTA" NUMBER(9,4), 
	"COSHOR" NUMBER(9,4), 
	"COSTER" NUMBER(9,4), 
	"COSMAT" NUMBER(9,4), 
	"GIF" NUMBER(9,4)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_TSI_SUITE" ;
