--------------------------------------------------------
--  DDL for Package PACK_REPORTES_TRAZABILIDAD2
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "USR_TSI_SUITE"."PACK_REPORTES_TRAZABILIDAD2" AS
    TYPE datarecord_reqcompra IS RECORD (
        tipdoc           documentos_cab.tipdoc%TYPE,
        numint           documentos_cab.numint%TYPE,
        series           documentos_cab.series%TYPE,
        numdoc           documentos_cab.numdoc%TYPE,
        femisi           documentos_cab.femisi%TYPE,
        codcli           documentos_cab.codcli%TYPE,
        razonc           documentos_cab.razonc%TYPE,
        direc1           documentos_cab.direc1%TYPE,
        ruc              documentos_cab.ruc%TYPE,
        tipcam           documentos_cab.tipcam%TYPE,
        descue           documentos_cab.descue%TYPE,
        totbru           documentos_cab.totbru%TYPE,
        monafe           documentos_cab.monafe%TYPE,
        monina           documentos_cab.monina%TYPE,
        moneto           documentos_cab.monafe%TYPE,
        monigv           documentos_cab.monigv%TYPE,
        preven           documentos_cab.preven%TYPE,
        porigv           documentos_cab.porigv%TYPE,
        incigv           documentos_cab.incigv%TYPE,
        codsuc           documentos_cab.codsuc%TYPE,
        numped           documentos_cab.numped%TYPE,
        codmot           documentos_cab.codmot%TYPE,
        situac           documentos_cab.situac%TYPE,
        obscab           documentos_cab.observ%TYPE,
        fentreg          documentos_cab.fentreg%TYPE,
        codarea          documentos_cab.codarea%TYPE,
        coduso           documentos_cab.coduso%TYPE,
        totcan           documentos_cab.totcan%TYPE,
        horing           documentos_cab.horing%TYPE,
        fecter           documentos_cab.fecter%TYPE,
        horter           documentos_cab.horter%TYPE,
        codtec           documentos_cab.codtec%TYPE,
        opnumdoc         documentos_cab.opnumdoc%TYPE,
        ordcom           documentos_cab.ordcom%TYPE,
        guiarefe         documentos_cab.guiarefe%TYPE,
        numvale          documentos_cab.numvale%TYPE,
        fecvale          documentos_cab.fecvale%TYPE,
        codsec           documentos_cab.codsec%TYPE,
        destin           documentos_cab.destin%TYPE,
        tipmon           documentos_cab.tipmon%TYPE,
        desmot           motivos.desmot%TYPE,
        dessit           situacion.dessit%TYPE,
        aliassit         VARCHAR2(250 CHAR),
        despagcom        c_pago.despag%TYPE,
        simbolo          tmoneda.simbolo%TYPE,
        desmon           tmoneda.desmon%TYPE,
        dircli1          cliente.direc1%TYPE,
        dircli2          cliente.direc2%TYPE,
        faxcli           cliente.fax%TYPE,
        tlfcli           cliente.telefono%TYPE,
        codenv           documentos_cab_almacen.codenv%TYPE,
        desenv01         documentos_cab_almacen.direc1%TYPE,
        desenv02         documentos_cab_almacen.direc2%TYPE,
        atenci           documentos_cab_contacto.atenci%TYPE,
        emailcon         documentos_cab_contacto.email%TYPE,
        plaent           documentos_cab_contacto.plaent%TYPE,
        valide           documentos_cab_contacto.valide%TYPE,
        dessuc           VARCHAR2(250 CHAR),
        direcc           sucursal.direcc%TYPE,
        dissuc           sucursal.nomdis%TYPE,
        desven           vendedor.desven%TYPE,
        carven           vendedor.cargo%TYPE,
        mailven          vendedor.email%TYPE,
        celuven          vendedor.celular%TYPE,
        tlfven           vendedor.telefo%TYPE,
        comiven          vendedor.comisi%TYPE,
        codvendedor      vendedor.codven%TYPE,
        destra           transportista.descri%TYPE,
        dirtra           transportista.domici%TYPE,
        ructra           transportista.ruc%TYPE,
        punpartra        transportista.punpar%TYPE,
        dd_numite        documentos_det.numite%TYPE,
        dd_tipinv        documentos_det.tipinv%TYPE,
        dd_codart        documentos_det.codart%TYPE,
        dd_codalm        documentos_det.codalm%TYPE,
        dd_codund        documentos_det.codund%TYPE,
        dd_diseno        documentos_det.diseno%TYPE,
        dd_acabado       documentos_det.acabado%TYPE,
        dd_cantid        documentos_det.cantid%TYPE,
        dd_piezas        documentos_det.piezas%TYPE,
        dd_largo         documentos_det.largo%TYPE,
        dd_preuni        documentos_det.preuni%TYPE,
        dd_cosuni        documentos_det.cosuni%TYPE,
        dd_ancho         documentos_det.ancho%TYPE,
        dd_importe_bruto documentos_det.importe%TYPE,
        dd_importe       documentos_det.importe%TYPE,
        dd_descdet       documentos_det.importe%TYPE,
        dd_obsdet        documentos_det.observ%TYPE,
        dd_pordes1       documentos_det.pordes1%TYPE,
        dd_pordes2       documentos_det.pordes2%TYPE,
        dd_pordes3       documentos_det.pordes3%TYPE,
        dd_pordes4       documentos_det.pordes4%TYPE,
        dd_proart        articulos.proart%TYPE,
        dd_desart        articulos.descri%TYPE,
        dd_desartclase   VARCHAR2(250 CHAR),
        dd_codlin        articulos.codlin%TYPE,
        dd_faccon        articulos.faccon%TYPE,
        dd_desarea       areas.desarea%TYPE,
        dd_desalm        almacen.descri%TYPE,
        dd_desuso        usos.desuso%TYPE,
        dd_pesdet        articulos.faccon%TYPE,
			-- NOMDIS,
			-- PLAZA,
			-- SUCURSAL,
			-- DTIPINV,
        sku              listaprecios.sku%TYPE,
        dd_desart_sku    VARCHAR2(250 CHAR),
			-- GPIEPA,
			-- CUENTA01PROV,
			-- CUENTA02PROV,
			-- CIARAZONC,
			-- CIARUC,
			-- CIAFAX,
			-- CIATELEFO,
        dd_codcalid      VARCHAR2(250 CHAR),
        dd_dcalidad      VARCHAR2(250 CHAR),
        dd_dcolor        VARCHAR2(250 CHAR),
        dd_glosxdes      VARCHAR2(250 CHAR),
        desdoc           documentos.descri%TYPE,
        nomser           documentos.nomser%TYPE,
        glosadoc         documentos_glosa.observ%TYPE,
        formato          documentos_formatos.formato%TYPE
    );
    TYPE datatable_reqcompra IS
        TABLE OF datarecord_reqcompra;
    TYPE datarecord_ordenproduccion IS RECORD (
        id_cia           documentos_cab.id_cia%TYPE,
        numint           documentos_cab.numint%TYPE,
        numite           documentos_det.numite%TYPE,
        series           documentos_cab.series%TYPE,
        numdoc           documentos_cab.numdoc%TYPE,
        femisi           documentos_cab.femisi%TYPE,
        codsuc           documentos_cab.codsuc%TYPE,
        opnumdoc         documentos_cab.opnumdoc%TYPE,
        razonc           documentos_cab.razonc%TYPE,
        direc1           documentos_cab.direc1%TYPE,
        ruc              documentos_cab.ruc%TYPE,
        tipmon           documentos_cab.tipmon%TYPE,
        fentreg          documentos_cab.fentreg%TYPE,
        fecter           documentos_cab.fecter%TYPE,
        horter           documentos_cab.horter%TYPE,
        obscab           documentos_cab.observ%TYPE,
        comentario       documentos_cab.presen%TYPE,
        monafe           documentos_cab.monafe%TYPE,
        monina           documentos_cab.monina%TYPE,
        monneto          documentos_cab.monina%TYPE,
        monexo           documentos_cab.monexo%TYPE,
        monigv           documentos_cab.monigv%TYPE,
        monisc           documentos_cab.monisc%TYPE,
        monotr           documentos_cab.monotr%TYPE,
        preven           documentos_cab.preven%TYPE,
        percep           documentos_cab_clase.vreal%TYPE,
        totpag           documentos_cab.preven%TYPE,
        porigv           documentos_cab.porigv%TYPE,
        incigv           documentos_cab.incigv%TYPE,
        desesp           documentos_cab.desesp%TYPE,
        faxcli           cliente.fax%TYPE,
        tlfcli           cliente.telefono%TYPE,
        numped           documentos_cab.numped%TYPE,
        glosxdes         articulos_clase.codigo%TYPE,
        desenv01         documentos_cab_almacen.direc1%TYPE,
        destra           transportista.descri%TYPE,
        destra2          transportista.descri%TYPE,
        atenci           documentos_cab_contacto.atenci%TYPE,
        desven           vendedor.desven%TYPE,
        aliassit         VARCHAR2(50), --r
        dessit           situacion.dessit%TYPE,
        desmot           motivos.desmot%TYPE,
        tipimp           documentos.tipimp%TYPE,
        tipimpformato    documentos_formatos.formato%TYPE,
        tipinv           documentos_det.tipinv%TYPE,
        codart           documentos_det.codart%TYPE,
        desart           articulos.descri%TYPE,
        consto           articulos.consto%TYPE,
        codalm           documentos_det.codalm%TYPE,
        obsdet           documentos_det.observ%TYPE,
        monafedet        documentos_det.monafe%TYPE,
        moninadet        documentos_det.monina%TYPE,
        moniscdet        documentos_det.monisc%TYPE,
        monigvdet        documentos_det.monigv%TYPE,
        monotrdet        documentos_det.monotr%TYPE,
        codunddet        documentos_det.codund%TYPE,
        codund           articulos.coduni%TYPE,
        cantid           documentos_det.cantid%TYPE,
        piezas           documentos_det.piezas%TYPE,
        largo            documentos_det.largo%TYPE,
        ancho            documentos_det.ancho%TYPE,
        preuni           documentos_det.preuni%TYPE,
        importe          documentos_det.importe%TYPE,
        importe_bruto    documentos_det.importe_bruto%TYPE,
        pordes1          documentos_det.pordes1%TYPE,
        pordes2          documentos_det.pordes2%TYPE,
        pordes3          documentos_det.pordes3%TYPE,
        pordes4          documentos_det.pordes4%TYPE,
        opronumdoc       documentos_det.opronumdoc%TYPE,
        etiqueta         documentos_det.etiqueta%TYPE,
        nrocarrete       documentos_det.nrocarrete%TYPE,
        acabado          documentos_det.acabado%TYPE,
        chasis           documentos_det.chasis%TYPE,
        motor            documentos_det.motor%TYPE,
        lote             documentos_det.lote%TYPE,
        fvenci           documentos_det.fvenci%TYPE,
        stockk001        kardex001.ingreso%TYPE,
        saldok001        kardex001.ingreso%TYPE,
        simbolo          tmoneda.simbolo%TYPE,
        desmon           tmoneda.desmon%TYPE,
        porpercep        VARCHAR2(20),
        swdocpercep      VARCHAR2(20),
        astpercep        VARCHAR2(20),
        glosagar         companias_glosa.glosa%TYPE,
        glosagap         companias_glosa.glosa%TYPE,
        glosagfp         companias_glosa.glosa%TYPE,
        codpiepagforf01  documentos_clase.vstrg%TYPE,
        codpiepagforf02  documentos_clase.vstrg%TYPE,
        valundaltven     NUMBER(16, 2),
        c_visadopor      VARCHAR2(500),
        visadopor        VARCHAR2(500),
        c_emitidopor     VARCHAR2(500),
        emitidopor       VARCHAR2(500),
        c_aprobadopor    VARCHAR2(500),
        aprobadopor      VARCHAR2(500),
        situac_aprob     VARCHAR2(500),
        ubigeo           VARCHAR2(500),
        ubigeo_b         VARCHAR2(500),
        fecha_dcorcom    documentos_cab_ordcom.fecha%TYPE,
        numero_dcorcom   documentos_cab_ordcom.numero%TYPE,
        contacto_dcorcom documentos_cab_ordcom.contacto%TYPE,
        abrunidad        unidad.abrevi%TYPE,
        codadd01         documentos_det.codadd01%TYPE,
        descodadd01      VARCHAR2(500),
        codadd02         documentos_det.codadd02%TYPE,
        descodadd02      VARCHAR2(500),
        formato          documentos_formatos.formato%TYPE
    );
    TYPE datatable_ordenproduccion IS
        TABLE OF datarecord_ordenproduccion;
    TYPE datarecord_ordenpedido IS RECORD (
        id_cia           documentos_cab.id_cia%TYPE,
        numint           documentos_cab.numint%TYPE,
        numite           documentos_det.numite%TYPE,
        series           documentos_cab.series%TYPE,
        numdoc           documentos_cab.numdoc%TYPE,
        femisi           documentos_cab.femisi%TYPE,
        codsuc           documentos_cab.codsuc%TYPE,
        opnumdoc         documentos_cab.opnumdoc%TYPE,
        razonc           documentos_cab.razonc%TYPE,
        direc1           documentos_cab.direc1%TYPE,
        ruc              documentos_cab.ruc%TYPE,
        tipmon           documentos_cab.tipmon%TYPE,
        fentreg          documentos_cab.fentreg%TYPE,
        fecter           documentos_cab.fecter%TYPE,
        horter           documentos_cab.horter%TYPE,
        obscab           documentos_cab.observ%TYPE,
        monafe           documentos_cab.monafe%TYPE,
        monina           documentos_cab.monina%TYPE,
        monneto          documentos_cab.monina%TYPE,
        monexo           documentos_cab.monexo%TYPE,
        monigv           documentos_cab.monigv%TYPE,
        monisc           documentos_cab.monisc%TYPE,
        monotr           documentos_cab.monotr%TYPE,
        preven           documentos_cab.preven%TYPE,
        costo            documentos_cab.costo%TYPE,
        percep           documentos_cab_clase.vreal%TYPE,
        totpag           documentos_cab.preven%TYPE,
        porigv           documentos_cab.porigv%TYPE,
        incigv           documentos_cab.incigv%TYPE,
        desesp           documentos_cab.desesp%TYPE,
        faxcli           cliente.fax%TYPE,
        tlfcli           cliente.telefono%TYPE,
        numped           documentos_cab.numped%TYPE,
        glosxdes         articulos_clase.codigo%TYPE,
        desenv01         documentos_cab_almacen.direc1%TYPE,
        destra           transportista.descri%TYPE,
        destra2          transportista.descri%TYPE,
        atenci           documentos_cab_contacto.atenci%TYPE,
        desven           vendedor.desven%TYPE,
        aliassit         VARCHAR2(50), --r
        dessit           situacion.dessit%TYPE,
        desmot           motivos.desmot%TYPE,
        tipimp           documentos.tipimp%TYPE,
        tipimpformato    documentos_formatos.formato%TYPE,
        tipinv           documentos_det.tipinv%TYPE,
        codart           documentos_det.codart%TYPE,
        desart           articulos.descri%TYPE,
        consto           articulos.consto%TYPE,
        codalm           documentos_det.codalm%TYPE,
        obsdet           documentos_det.observ%TYPE,
        monafedet        documentos_det.monafe%TYPE,
        moninadet        documentos_det.monina%TYPE,
        moniscdet        documentos_det.monisc%TYPE,
        monigvdet        documentos_det.monigv%TYPE,
        monotrdet        documentos_det.monotr%TYPE,
        codunddet        documentos_det.codund%TYPE,
        codund           articulos.coduni%TYPE,
        cantid           documentos_det.cantid%TYPE,
        piezas           documentos_det.piezas%TYPE,
        largo            documentos_det.largo%TYPE,
        ancho            documentos_det.ancho%TYPE,
        preuni           documentos_det.preuni%TYPE,
        cosuni           documentos_det.cosuni%TYPE,
        margen           documentos_det.cosuni%TYPE,
        importe          documentos_det.importe%TYPE,
        importe_bruto    documentos_det.importe_bruto%TYPE,
        pordes1          documentos_det.pordes1%TYPE,
        pordes2          documentos_det.pordes2%TYPE,
        pordes3          documentos_det.pordes3%TYPE,
        pordes4          documentos_det.pordes4%TYPE,
        opronumdoc       documentos_det.opronumdoc%TYPE,
        etiqueta         documentos_det.etiqueta%TYPE,
        nrocarrete       documentos_det.nrocarrete%TYPE,
        acabado          documentos_det.acabado%TYPE,
        chasis           documentos_det.chasis%TYPE,
        motor            documentos_det.motor%TYPE,
        lote             documentos_det.lote%TYPE,
        fvenci           documentos_det.fvenci%TYPE,
        stockk001        kardex001.ingreso%TYPE,
        saldok001        kardex001.ingreso%TYPE,
        simbolo          tmoneda.simbolo%TYPE,
        desmon           tmoneda.desmon%TYPE,
        porpercep        VARCHAR2(20),
        swdocpercep      VARCHAR2(20),
        astpercep        VARCHAR2(20),
        glosagar         companias_glosa.glosa%TYPE,
        glosagap         companias_glosa.glosa%TYPE,
        glosagfp         companias_glosa.glosa%TYPE,
        codpiepagforf01  documentos_clase.vstrg%TYPE,
        codpiepagforf02  documentos_clase.vstrg%TYPE,
        valundaltven     NUMBER(16, 2),
        c_visadopor      VARCHAR2(500),
        visadopor        VARCHAR2(500),
        c_emitidopor     VARCHAR2(500),
        emitidopor       VARCHAR2(500),
        c_aprobadopor    VARCHAR2(500),
        aprobadopor      VARCHAR2(500),
        situac_aprob     VARCHAR2(500),
        ubigeo           VARCHAR2(500),
        ubigeo_b         VARCHAR2(500),
        fecha_dcorcom    documentos_cab_ordcom.fecha%TYPE,
        numero_dcorcom   documentos_cab_ordcom.numero%TYPE,
        contacto_dcorcom documentos_cab_ordcom.contacto%TYPE,
        abrunidad        unidad.abrevi%TYPE,
        codadd01         documentos_det.codadd01%TYPE,
        descodadd01      VARCHAR2(500),
        codadd02         documentos_det.codadd02%TYPE,
        descodadd02      VARCHAR2(500),
        formato          documentos_formatos.formato%TYPE
    );
    TYPE datatable_ordenpedido IS
        TABLE OF datarecord_ordenpedido;
    TYPE datarecord_cotizacion IS RECORD (
        id_cia       documentos_cab.id_cia%TYPE,
        tipdoc       documentos_cab.tipdoc%TYPE,
        nomdoc       documentos.descri%TYPE,
        codsuc       documentos_cab.codsuc%TYPE,
        numint       documentos_cab.numint%TYPE,
        numite       documentos_det.numite%TYPE,
        series       documentos_cab.series%TYPE,
        numdoc       documentos_cab.numdoc%TYPE,
        femisi       documentos_cab.femisi%TYPE,
        codcli       documentos_cab.codcli%TYPE,
        razonc       documentos_cab.razonc%TYPE,
        direc1       documentos_cab.direc1%TYPE,
        ruc          documentos_cab.ruc%TYPE,
        tipcam       documentos_cab.tipcam%TYPE,
        tipmon       documentos_cab.tipmon%TYPE,
        situac       documentos_cab.situac%TYPE,
        obscab       documentos_cab.observ%TYPE,
        fentreg      documentos_cab.fentreg%TYPE,
        ffacpro      documentos_cab.ffacpro%TYPE,
        ordcom       documentos_cab.ordcom%TYPE,
        guiarefe     documentos_cab.guiarefe%TYPE,
        marcas       documentos_cab.marcas%TYPE,
        tipinv       documentos_det.tipinv%TYPE,
        codart       documentos_det.codart%TYPE,
        positi       documentos_det.positi%TYPE,
        codunddet    documentos_det.codund%TYPE,
        cantid       documentos_det.cantid%TYPE,
        preuni       documentos_det.preuni%TYPE,
        cosuni       documentos_det.cosuni%TYPE,
        margen       documentos_det.cosuni%TYPE,
        importe      documentos_det.importe%TYPE,
        pordes1      documentos_det.pordes1%TYPE,
        pordes2      documentos_det.pordes2%TYPE,
        pordes3      documentos_det.pordes3%TYPE,
        pordes4      documentos_det.pordes4%TYPE,
        ubica        documentos_det.ubica%TYPE,
        descdet      documentos_det.importe%TYPE,
        obsdet       documentos_det.observ%TYPE,
        swacti       documentos_det.swacti%TYPE,
        monneto      documentos_cab.monafe%TYPE,
        monigv       documentos_cab.monigv%TYPE,
        preven       documentos_cab.preven%TYPE,
        costo        documentos_cab.costo%TYPE,
        descue       documentos_cab.descue%TYPE,
        totbru       documentos_cab.totbru%TYPE,
        percep       documentos_cab_clase.vreal%TYPE,
        totpag       documentos_cab.preven%TYPE,
        porigv       documentos_cab.porigv%TYPE,
        incigv       documentos_cab.incigv%TYPE,
        atenci       documentos_cab_contacto.atenci%TYPE,
        plaent       documentos_cab_contacto.plaent%TYPE,
        valide       documentos_cab_contacto.valide%TYPE,
        mailcont     documentos_cab_contacto.email%TYPE,
        numped       documentos_cab.numped%TYPE,
        desart       articulos.descri%TYPE,
        codund       articulos.coduni%TYPE,
        codlin       articulos.codlin%TYPE,
        faccon       articulos.faccon%TYPE,
        conesp       articulos.conesp%TYPE,
        pesdet       NUMBER(16, 5),
        codcpag      documentos_cab.codcpag%TYPE,
        despagven    c_pago.despag%TYPE,
        glosxdes     articulos_clase.codigo%TYPE,
        codven       vendedor.codven%TYPE,
        desven       vendedor.desven%TYPE,
        carven       vendedor.cargo%TYPE,
        mailven      vendedor.email%TYPE,
        celuven      vendedor.celular%TYPE,
        tlfven       vendedor.telefo%TYPE,
        simbolo      tmoneda.simbolo%TYPE,
        desmon       tmoneda.desmon%TYPE,
        aliassit     situacion.alias%TYPE,
        especialidad clase_vendedor_codigo.descri%TYPE,
        swdocpercep  VARCHAR2(20),
        astpercep    VARCHAR2(20),
        glosagar     companias_glosa.glosa%TYPE,
        glosagap     companias_glosa.glosa%TYPE,
        glosagfp     companias_glosa.glosa%TYPE,
        porpercep    VARCHAR2(25), --r
        gnotas       companias_glosa.glosa%TYPE,
        valundaltven NUMBER(12, 6),
        ubigeo       VARCHAR2(500),
        ubigeo_b     VARCHAR2(500),
        abrunidad    unidad.abrevi%TYPE,
        desenv01     documentos_cab_almacen.direc1%TYPE,
        destra       transportista.descri%TYPE,
        ruccia       companias.ruc%TYPE,
        formato      documentos_formatos.formato%TYPE
    );
    TYPE datatable_cotizacion IS
        TABLE OF datarecord_cotizacion;
    FUNCTION sp_reqcompra (
        pin_id_cia NUMBER,
        pin_numint NUMBER
    ) RETURN datatable_reqcompra
        PIPELINED;

    FUNCTION sp_ordenproduccion (
        pin_id_cia NUMBER,
        pin_numint NUMBER
    ) RETURN datatable_ordenproduccion
        PIPELINED;

    FUNCTION sp_ordentrabajo (
        pin_id_cia NUMBER,
        pin_numint NUMBER
    ) RETURN datatable_ordenproduccion
        PIPELINED;

    FUNCTION sp_ordenpedido (
        pin_id_cia NUMBER,
        pin_numint NUMBER
    ) RETURN datatable_ordenpedido
        PIPELINED;

    FUNCTION sp_cotizacion (
        pin_id_cia NUMBER,
        pin_numint NUMBER
    ) RETURN datatable_cotizacion
        PIPELINED;

END;

/
