--------------------------------------------------------
--  DDL for Package PACK_DOCUMENTO_GENERICO
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "USR_TSI_SUITE"."PACK_DOCUMENTO_GENERICO" AS
    TYPE datarecord_documento_generico IS RECORD (
        id_cia                 NUMBER(38),
        numint                 NUMBER(38),
        tipdoc                 NUMBER(38),
        series                 VARCHAR2(5),
        numdoc                 NUMBER(38),
        femisi                 DATE,
        lugemi                 NUMBER(38),
        situac                 CHAR(1),
        id                     CHAR(1),
        codmot                 NUMBER(38),
        motdoc                 NUMBER(38),
        codalm                 NUMBER(38),
        almdes                 NUMBER(38),
        codcli                 VARCHAR2(20),
        tident                 VARCHAR2(2),
        ruc                    VARCHAR2(20),
        razonc                 VARCHAR2(80 CHAR),
        direc1                 VARCHAR2(100 CHAR),
        codenv                 NUMBER(38),
        codcpag                NUMBER(38),
        codtra                 NUMBER(38),
        codven                 NUMBER(38),
        comisi                 NUMBER(9, 3),
        incigv                 CHAR(1),
        destin                 NUMBER(38),
        totbru                 NUMBER(16, 2),
        descue                 NUMBER(16, 2),
        desesp                 NUMBER(16, 2),
        monafe                 NUMBER(16, 2),
        monina                 NUMBER(16, 2),
        porigv                 NUMBER(16, 2),
        monigv                 NUMBER(16, 2),
        preven                 NUMBER(16, 2),
        costo                  NUMBER(16, 2),
        tipmon                 VARCHAR2(5),
        tipcam                 NUMBER(10, 6),
        atenci                 VARCHAR2(50),
        valide                 VARCHAR2(50),
        plaent                 VARCHAR2(50),
        ordcom                 VARCHAR2(20),
        numped                 VARCHAR2(60),
        gasvin                 NUMBER(16, 2),
        seguro                 NUMBER(16, 2),
        flete                  NUMBER(16, 2),
        desfle                 VARCHAR2(50),
        desexp                 NUMBER(16, 2),
        gasadu                 NUMBER(16, 2),
        pesbru                 NUMBER(16, 2),
        pesnet                 NUMBER(16, 2),
        bultos                 NUMBER(38),
        presen                 VARCHAR2(200 CHAR),
        marcas                 VARCHAR2(50),
        numdue                 VARCHAR2(25),
        fnumdue                DATE,
        fembarq                DATE,
        fentreg                DATE,
        valfob                 NUMBER(16, 2),
        guipro                 VARCHAR2(20),
        fguipro                DATE,
        facpro                 VARCHAR2(20),
        ffacpro                DATE,
        cargo                  VARCHAR2(10),
        codsuc                 NUMBER(38),
        fcreac                 TIMESTAMP(6),
        factua                 TIMESTAMP(6),
        acuenta                NUMBER(16, 2),
        ucreac                 VARCHAR2(10),
        usuari                 VARCHAR2(10),
        swacti                 CHAR(1),
        codarea                NUMBER(38),
        coduso                 NUMBER(38),
        opnumdoc               NUMBER(38),
        opcargo                VARCHAR2(10),
        opnumite               NUMBER(38),
        opcodart               VARCHAR2(40),
        optipinv               NUMBER(38),
        totcan                 NUMBER(16, 5),
        fordcom                DATE,
        ordcomni               NUMBER(38),
        motvarios              NUMBER(38),
        horing                 TIMESTAMP(6),
        fecter                 DATE,
        horter                 TIMESTAMP(6),
        codtec                 NUMBER(38),
        guiarefe               VARCHAR2(15),
        desenv                 VARCHAR2(60 CHAR),
        codaux                 VARCHAR2(3),
        codetapauso            NUMBER(38),
        codsec                 NUMBER(38),
        numvale                NUMBER(38),
        fecvale                DATE,
        swtrans                NUMBER(38),
        desseg                 VARCHAR2(50),
        desgasa                VARCHAR2(50),
        desnetx                VARCHAR2(50),
        despreven              VARCHAR2(50),
        codcob                 NUMBER(38),
        codveh                 NUMBER(38),
        codpunpar              NUMBER(38),
        ubigeopar              VARCHAR2(10),
        direccpar              VARCHAR2(100 CHAR),
        monisc                 NUMBER(16, 2),
        monotr                 NUMBER(16, 2),
        monexo                 NUMBER(16, 2),
        observ                 VARCHAR2(3000 CHAR),
        proyec                 VARCHAR2(16),
        montgr                 NUMBER(16, 2),
        countadj               NUMBER(38),
        numintper              NUMBER(38),
        moncredito             documentos_cab.moncredito%TYPE,
        swmigra                documentos_cab.swmigra%TYPE,
        monicbper               documentos_cab.monicbper%TYPE,
        dessituac              situacion.dessit%TYPE,
        dd_codcli              documentos_det.codcli%TYPE,
        dd_numint              documentos_det.numint%TYPE,
        dd_numite              documentos_det.numite%TYPE,
        dd_tipinv              documentos_det.tipinv%TYPE,
        dd_codart              documentos_det.codart%TYPE,
        dd_desart              articulos.descri%TYPE,
        dd_preuni              documentos_det.preuni%TYPE,
        dd_importe             documentos_det.importe%TYPE,
        dd_observ              documentos_det.observ%TYPE,
        dd_cantid              documentos_det.cantid%TYPE,
        dd_acabado             documentos_det.acabado%TYPE,
        dd_nrocarrete          documentos_det.nrocarrete%TYPE,
        dd_chasis              documentos_det.chasis%TYPE,
        dd_motor               documentos_det.motor%TYPE,
        dd_codadd01            documentos_det.codadd01%TYPE,
        dd_descodadd01         cliente_articulos_clase.descri%TYPE,
        dd_codadd02            documentos_det.codadd02%TYPE,
        dd_descodadd02         cliente_articulos_clase.descri%TYPE,
        dd_etiqueta            documentos_det.etiqueta%TYPE,
        descodcpag             c_pago.despag%TYPE,
        desven                 vendedor.desven%TYPE,
        simbolo                tmoneda.simbolo%TYPE,
        usuario                usuarios.nombres%TYPE,
        situacioncredito       documentos_aprobacion.situac%TYPE,
        situacioncreditonombre VARCHAR2(15),
        dam                    kardex000.dam%TYPE,
        placa                  kardex000.placa%TYPE
    );
    TYPE datatable_documento_generico IS
        TABLE OF datarecord_documento_generico;
    FUNCTION sp_obtener (
        pin_id_cia IN NUMBER,
        pin_numint IN NUMBER
    ) RETURN datatable_documento_generico
        PIPELINED;

END;

/
