--------------------------------------------------------
--  DDL for Package PACK_DOCUMENTOS_CAB
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE PACKAGE "USR_TSI_SUITE"."PACK_DOCUMENTOS_CAB" AS 

  /* TODO enter package declarations (types, exceptions, methods etc) here */
    TYPE t_doccab IS
        TABLE OF documentos_cab%rowtype;
    TYPE datarecord_cotizaciones_padre IS RECORD (
        numint     documentos_cab.numint%TYPE,
        codsuc     documentos_cab.codsuc%TYPE,
        sucursal   VARCHAR2(100),
        tipdoc     documentos_cab.tipdoc%TYPE,
        series     documentos_cab.series%TYPE,
        numdoc     documentos_cab.numdoc%TYPE,
        femisi     documentos_cab.femisi%TYPE,
        numped     documentos_cab.numped%TYPE,
        presen     documentos_cab.presen%TYPE,
        tipmon     documentos_cab.tipmon%TYPE,
        preven     documentos_cab.preven%TYPE,
        codcli     documentos_cab.codcli%TYPE,
        razonc     documentos_cab.razonc%TYPE,
        situac     documentos_cab.situac%TYPE,
        situacdesc situacion.dessit%TYPE,
        docrelpen  VARCHAR2(10),
        despagven  c_pago.despag%TYPE,
        codmot     documentos_cab.codmot%TYPE,
        desmot     motivos.desmot%TYPE
    );
    TYPE datatable_cotizaciones_padre IS
        TABLE OF datarecord_cotizaciones_padre;
    TYPE datarecord_guias_remision_padre IS RECORD (
        numint               documentos_cab.numint%TYPE,
        series               documentos_cab.series%TYPE,
        numdoc               documentos_cab.numdoc%TYPE,
        tident               documentos_cab.tident%TYPE,
        ruc                  documentos_cab.ruc%TYPE,
        codcli               documentos_cab.codcli%TYPE,
        razonc               documentos_cab.razonc%TYPE,
        direc1               documentos_cab.direc1%TYPE,
        telefono             cliente.telefono%TYPE,
        femisi               documentos_cab.femisi%TYPE,
        fentreg              documentos_cab.fentreg%TYPE,
        lugemi               documentos_cab.lugemi%TYPE,
        situac               documentos_cab.situac%TYPE,
        situacnombre         situacion.dessit%TYPE,
        id                   documentos_cab.id%TYPE,
        codmot               documentos_cab.codmot%TYPE,
        codven               documentos_cab.codven%TYPE,
        codsuc               documentos_cab.codsuc%TYPE,
        moneda               documentos_cab.tipmon%TYPE,
        tipcam               documentos_cab.tipcam%TYPE,
        fecter               documentos_cab.fecter%TYPE,
        horapactada          documentos_cab.horter%TYPE,
        observacion          documentos_cab.observ%TYPE,
        codigovehiculo       documentos_cab.codveh%TYPE,
        codalm               documentos_cab.codalm%TYPE,
        codalmdestino        documentos_cab.almdes%TYPE,
        codigopuntopartida   documentos_cab.codpunpar%TYPE,
        ubigeopuntopartida   documentos_cab.ubigeopar%TYPE,
        direccpuntopartida   documentos_cab.direccpar%TYPE,
        comentario           documentos_cab.presen%TYPE,
        codigotransportista1 documentos_cab.codtra%TYPE,
        codigotransportista2 documentos_cab.codtec%TYPE,
        porigv               documentos_cab.porigv%TYPE,
        referencia           documentos_cab.numped%TYPE,
        importebruto         documentos_cab.totbru%TYPE,
        importe              documentos_cab.preven%TYPE,
        cantidadtotal        documentos_cab.totcan%TYPE,
        fordcom              documentos_cab.fordcom%TYPE,
        ordcom               documentos_cab.ordcom%TYPE,
        condicionpago        c_pago.despag%TYPE,
        vendedor             VARCHAR2(100),
        codcpag              documentos_cab.codcpag%TYPE,
        coduser              documentos_cab.usuari%TYPE,
        usuario              usuarios.nombres%TYPE,
        incigv               VARCHAR2(10),
        sucursal             VARCHAR2(100),
        motivo               motivos.desmot%TYPE
    );
    TYPE datatable_guias_remision_padre IS
        TABLE OF datarecord_guias_remision_padre;
    TYPE datarecord_ordenes_pedido_padre IS RECORD (
        numint     documentos_cab.numint%TYPE,
        codsuc     documentos_cab.codsuc%TYPE,
        sucursal   VARCHAR2(100),
        tipdoc     documentos_cab.tipdoc%TYPE,
        series     documentos_cab.series%TYPE,
        numdoc     documentos_cab.numdoc%TYPE,
        femisi     documentos_cab.femisi%TYPE,
        numped     documentos_cab.numped%TYPE,
        presen     documentos_cab.presen%TYPE,
        tipmon     documentos_cab.tipmon%TYPE,
        preven     documentos_cab.preven%TYPE,
        codcli     documentos_cab.codcli%TYPE,
        razonc     documentos_cab.razonc%TYPE,
        situac     documentos_cab.situac%TYPE,
        situacdesc situacion.dessit%TYPE,
        docrelpen  VARCHAR2(10),
        despagven  c_pago.despag%TYPE,
        codmot     documentos_cab.codmot%TYPE,
        desmot     motivos.desmot%TYPE
    );
    TYPE datatable_ordenes_pedido_padre IS
        TABLE OF datarecord_ordenes_pedido_padre;
    TYPE datarecord_facturas_padre IS RECORD (
        numint     documentos_cab.numint%TYPE,
        codsuc     documentos_cab.codsuc%TYPE,
        sucursal   VARCHAR2(100),
        tipdoc     documentos_cab.tipdoc%TYPE,
        serie      documentos_cab.series%TYPE,
        numero     documentos_cab.numdoc%TYPE,
        femisi     documentos_cab.femisi%TYPE,
        numped     documentos_cab.numped%TYPE,
        presen     documentos_cab.presen%TYPE,
        moneda     documentos_cab.tipmon%TYPE,
        importe    documentos_cab.preven%TYPE,
        codcli     documentos_cab.codcli%TYPE,
        razonc     documentos_cab.razonc%TYPE,
        situac     documentos_cab.situac%TYPE,
        situacdesc situacion.dessit%TYPE,
        docrelpen  VARCHAR2(10),
        despagven  c_pago.despag%TYPE,
        codmot     documentos_cab.codmot%TYPE,
        monisc     documentos_cab.monisc%TYPE,
        desmot     motivos.desmot%TYPE
    );
    TYPE datatable_facturas_padre IS
        TABLE OF datarecord_facturas_padre;
    TYPE datarecord_boleta_padre IS RECORD (
        numint     documentos_cab.numint%TYPE,
        codsuc     documentos_cab.codsuc%TYPE,
        sucursal   VARCHAR2(100),
        tipdoc     documentos_cab.tipdoc%TYPE,
        serie      documentos_cab.series%TYPE,
        numero     documentos_cab.numdoc%TYPE,
        femisi     documentos_cab.femisi%TYPE,
        numped     documentos_cab.numped%TYPE,
        presen     documentos_cab.presen%TYPE,
        moneda     documentos_cab.tipmon%TYPE,
        importe    documentos_cab.preven%TYPE,
        codcli     documentos_cab.codcli%TYPE,
        razonc     documentos_cab.razonc%TYPE,
        situac     documentos_cab.situac%TYPE,
        situacdesc situacion.dessit%TYPE,
        docrelpen  VARCHAR2(10),
        despagven  c_pago.despag%TYPE,
        codmot     documentos_cab.codmot%TYPE,
        desmot     motivos.desmot%TYPE
    );
    TYPE datatable_boleta_padre IS
        TABLE OF datarecord_boleta_padre;
    TYPE datarecord_req_compras_padre IS RECORD (
        numint     documentos_cab.numint%TYPE,
        codsuc     documentos_cab.codsuc%TYPE,
        sucursal   VARCHAR2(100),
        tipdoc     documentos_cab.tipdoc%TYPE,
        series     documentos_cab.series%TYPE,
        numdoc     documentos_cab.numdoc%TYPE,
        femisi     documentos_cab.femisi%TYPE,
        numped     documentos_cab.numped%TYPE,
        presen     documentos_cab.presen%TYPE,
        tipmon     documentos_cab.tipmon%TYPE,
        preven     documentos_cab.preven%TYPE,
        codcli     documentos_cab.codcli%TYPE,
        razonc     documentos_cab.razonc%TYPE,
        situac     documentos_cab.situac%TYPE,
        situacdesc situacion.dessit%TYPE,
        docrelpen  VARCHAR2(10),
        despagven  c_pago.despag%TYPE,
        codmot     documentos_cab.codmot%TYPE,
        desmot     motivos.desmot%TYPE
    );
    TYPE datatable_req_compras_padre IS
        TABLE OF datarecord_req_compras_padre;
    TYPE datarecord_orden_compras_padre IS RECORD (
        numint     documentos_cab.numint%TYPE,
        codsuc     documentos_cab.codsuc%TYPE,
        sucursal   VARCHAR2(100),
        tipdoc     documentos_cab.tipdoc%TYPE,
        series     documentos_cab.series%TYPE,
        numdoc     documentos_cab.numdoc%TYPE,
        femisi     documentos_cab.femisi%TYPE,
        numped     documentos_cab.numped%TYPE,
        presen     documentos_cab.presen%TYPE,
        tipmon     documentos_cab.tipmon%TYPE,
        preven     documentos_cab.preven%TYPE,
        codcli     documentos_cab.codcli%TYPE,
        razonc     documentos_cab.razonc%TYPE,
        situac     documentos_cab.situac%TYPE,
        situacdesc situacion.dessit%TYPE,
        docrelpen  VARCHAR2(10),
        despagven  c_pago.despag%TYPE,
        codmot     documentos_cab.codmot%TYPE,
        desmot     motivos.desmot%TYPE
    );
    TYPE datatable_orden_compras_padre IS
        TABLE OF datarecord_orden_compras_padre;
    TYPE datarecord_guias_interna_padre IS RECORD (
        numint        documentos_cab.numint%TYPE,
        series        documentos_cab.series%TYPE,
        numdoc        documentos_cab.numdoc%TYPE,
        tident        documentos_cab.tident%TYPE,
        ruc           documentos_cab.ruc%TYPE,
        codcli        documentos_cab.codcli%TYPE,
        razonsocial   documentos_cab.razonc%TYPE,
        direccion     documentos_cab.direc1%TYPE,
        fentreg       documentos_cab.fentreg%TYPE,
        femisi        documentos_cab.femisi%TYPE,
        lugemi        documentos_cab.lugemi%TYPE,
        situac        documentos_cab.situac%TYPE,
        situacnombre  situacion.dessit%TYPE,
        id            documentos_cab.id%TYPE,
        codmot        documentos_cab.codmot%TYPE,
        codven        documentos_cab.codven%TYPE,
        codsuc        documentos_cab.codsuc%TYPE,
        moneda        documentos_cab.tipmon%TYPE,
        monisc        documentos_cab.monisc%TYPE,
        tipcam        documentos_cab.tipcam%TYPE,
        coc_numint    documentos_cab_ordcom.numint%TYPE,
        coc_fecha     documentos_cab_ordcom.fecha%TYPE,
        coc_numero    documentos_cab_ordcom.numero%TYPE,
        coc_contacto  documentos_cab_ordcom.contacto%TYPE,
        condicionpago c_pago.despag%TYPE,
        vendedor      VARCHAR(100),
        codcpag       documentos_cab.codcpag%TYPE,
        coduser       documentos_cab.usuari%TYPE,
        nombres       usuarios.nombres%TYPE,
        incigv        VARCHAR2(10),
        porigv        documentos_cab.porigv%TYPE,
        referencia    documentos_cab.numped%TYPE,
        observacion   documentos_cab.observ%TYPE,
        monafe        documentos_cab.monafe%TYPE,
        monina        documentos_cab.monina%TYPE,
        monigv        documentos_cab.monigv%TYPE,
        preven        documentos_cab.preven%TYPE,
        importebruto  documentos_cab.totbru%TYPE,
        importe       documentos_cab.preven%TYPE,
        situacimp     documentos_cab_clase.vchar%TYPE,
        dessituacimp  VARCHAR2(15),
        flete         documentos_cab.flete%TYPE,
        countadj      documentos_cab.countadj%TYPE,
        seguro        documentos_cab.seguro%TYPE
    );
    TYPE datatable_guias_interna_padre IS
        TABLE OF datarecord_guias_interna_padre;
    TYPE datarecord_obtener_comprobante IS RECORD (
        tipdoc        documentos_cab.tipdoc%TYPE,
        nomdoc        documentos.descri%TYPE,
        numint        documentos_cab.numint%TYPE,
        numite        documentos_det.numite%TYPE,
        series        documentos_cab.series%TYPE,
        numdoc        documentos_cab.numdoc%TYPE,
        femisi        documentos_cab.femisi%TYPE,
        codcli        documentos_cab.codcli%TYPE,
        razonc        documentos_cab.razonc%TYPE,
        direc1        documentos_cab.direc1%TYPE,
        codsuc        documentos_cab.codsuc%TYPE,
        ruc           documentos_cab.ruc%TYPE,
        dircli1       cliente.direc1%TYPE,
        dircli2       cliente.direc2%TYPE,
        tlfcli        cliente.telefono%TYPE,
        faxcli        cliente.fax%TYPE,
        dident        cliente.dident%TYPE,
        tident_cab    documentos_cab.tident%TYPE,
        destident     identidad.descri%TYPE,
        abrevi        identidad.abrevi%TYPE,
        nrodni        cliente_tpersona.nrodni%TYPE,
        guiarefe      documentos_cab.guiarefe%TYPE,
        almdes        documentos_cab.almdes%TYPE,
        desalmdes     almacen.descri%TYPE,
        abralmdes     almacen.abrevi%TYPE,
        marcas        documentos_cab.marcas%TYPE,
        presen        documentos_cab.presen%TYPE,
        codsec        documentos_cab.codsec%TYPE,
        facpro        documentos_cab.facpro%TYPE,
        ffacpro       documentos_cab.ffacpro%TYPE,
        codven        documentos_cab.codven%TYPE,
        observ        documentos_cab.observ%TYPE,
        tipcam        documentos_cab.tipcam%TYPE,
        tipmon        documentos_cab.tipmon%TYPE,
        totbru        documentos_cab.totbru%TYPE,
        desesp        documentos_cab.desesp%TYPE,
        descue        documentos_cab.descue%TYPE,
        monafe        documentos_cab.monafe%TYPE,
        monina        documentos_cab.monina%TYPE,
        monneto       documentos_cab.monina%TYPE,
        monigv        documentos_cab.monigv%TYPE,
        preven        documentos_cab.preven%TYPE,
        percep        NUMBER(18, 6),
        totpag        NUMBER(18, 6),
        relcossalprod motivos_clase.valor%TYPE,
        flete         documentos_cab.flete%TYPE,
        seguro        documentos_cab.seguro%TYPE,
        porigv        documentos_cab.porigv%TYPE,
        comiven       documentos_cab.comisi%TYPE,
        codmot        documentos_cab.codmot%TYPE,
        numped        documentos_cab.numped%TYPE,
        despagven     c_pago.despag%TYPE,
        enctacte      c_pago_clase.valor%TYPE,
        ordcom        documentos_cab.ordcom%TYPE,
        fordcom       documentos_cab.fordcom%TYPE,
        simbolo       tmoneda.simbolo%TYPE,
        desmon        tmoneda.desmon%TYPE,
        opnumdoc      documentos_cab.opnumdoc%TYPE,
        horing        documentos_cab.horing%TYPE,
        fecter        documentos_cab.fecter%TYPE,
        horter        documentos_cab.horter%TYPE,
        desnetx       documentos_cab.desnetx%TYPE,
        despreven     documentos_cab.despreven%TYPE,
        desfle        documentos_cab.desfle%TYPE,
        desseg        documentos_cab.desseg%TYPE,
        desgasa       documentos_cab.desgasa%TYPE,
        gasadu        documentos_cab.gasadu%TYPE,
        situac        documentos_cab.situac%TYPE,
        destin        documentos_cab.destin%TYPE,
        id            documentos_cab.id%TYPE,
        desmot        motivos.desmot%TYPE,
        docayuda      motivos.docayuda%TYPE,
        swdocpercep   VARCHAR2(1),
        porpercep     VARCHAR2(20),
        exoimp        VARCHAR2(1),
        diaven        c_pago.diaven%TYPE,
        dessuc        sucursal.sucursal%TYPE,
        dissuc        sucursal.nomdis%TYPE,
        desven        vendedor.desven%TYPE,
        destra        transportista.descri%TYPE,
        dirtra        transportista.domici%TYPE,
        ructra        transportista.ruc%TYPE,
        punpartra     transportista.punpar%TYPE,
        desenv01      documentos_cab_almacen.direc1%TYPE,
        desenv02      documentos_cab_almacen.direc2%TYPE,
        codalm        documentos_det.codalm%TYPE,
        desalm        almacen.descri%TYPE,
        tipinv        documentos_det.tipinv%TYPE,
        codart        documentos_det.codart%TYPE,
        desart        articulos.descri%TYPE,
        faccon        articulos.faccon%TYPE,
        consto        articulos.consto%TYPE,
        peslar        articulos.faccon%TYPE,
        pesdet        NUMBER(16, 8),
        taraadic      clase_codigo.abrevi%TYPE,
        coddesart     VARCHAR2(200),
        desglosa      articulos_glosa.observ%TYPE,
            --numite documentos_det.numite%type,
        cantid        documentos_det.cantid%TYPE,
        canref        documentos_det.canref%TYPE,
        piezas        documentos_det.piezas%TYPE,
        tara          documentos_det.tara%TYPE,
        largo         documentos_det.largo%TYPE,
        etiqueta      documentos_det.etiqueta%TYPE,
        etiqeuta2     documentos_det.etiqueta2%TYPE,
        codund        articulos.coduni%TYPE,
        codadd01      documentos_det.codadd01%TYPE,
        codadd02      documentos_det.codadd02%TYPE,
        dopronumdoc   documentos_det.opronumdoc%TYPE,
        dopnumdoc     documentos_det.opnumdoc%TYPE,
        dopcargo      documentos_det.opcargo%TYPE,
        dopnumite     documentos_det.opnumite%TYPE,
        preuni        documentos_det.preuni%TYPE,
        importe_bruto documentos_det.importe_bruto%TYPE,
        importe       documentos_det.importe%TYPE,
        descdet       documentos_det.importe%TYPE,
        preuni02      documentos_det.preuni%TYPE,
        preunireal    documentos_det.preuni%TYPE,
        importereal   documentos_det.importe%TYPE,
        codunidet     documentos_det.codund%TYPE,
        pordes1       documentos_det.pordes1%TYPE,
        pordes2       documentos_det.pordes2%TYPE,
        pordes3       documentos_det.pordes3%TYPE,
        pordes4       documentos_det.pordes4%TYPE,
        monlinneto    documentos_det.monafe%TYPE,
        monafedet     documentos_det.monafe%TYPE,
        mopnigvdet    documentos_det.monigv%TYPE,
        moniscdet     documentos_det.monisc%TYPE,
        monotrdet     documentos_det.monotr%TYPE,
        nrocarrete    documentos_det.nrocarrete%TYPE,
        acabado       documentos_det.acabado%TYPE,
        lote          documentos_det.lote%TYPE,
        fvenci        documentos_det.fvenci%TYPE,
        ancho         documentos_det.ancho%TYPE,
        astpercep     VARCHAR2(1),
        monuni        NUMBER(16, 8),
        obsdet        documentos_det.observ%TYPE
    );
    TYPE datatable_obtener_comprobante IS
        TABLE OF datarecord_obtener_comprobante;
    TYPE datarecord_obtener_factura IS RECORD (
        tipdoc        documentos_cab.tipdoc%TYPE,
        nomdoc        documentos.descri%TYPE,
        numint        documentos_cab.numint%TYPE,
        numite        documentos_det.numite%TYPE,
        series        documentos_cab.series%TYPE,
        numdoc        documentos_cab.numdoc%TYPE,
        femisi        documentos_cab.femisi%TYPE,
        codcli        documentos_cab.codcli%TYPE,
        razonc        documentos_cab.razonc%TYPE,
        direc1        documentos_cab.direc1%TYPE,
        codsuc        documentos_cab.codsuc%TYPE,
        ruc           documentos_cab.ruc%TYPE,
        dircli1       cliente.direc1%TYPE,
        dircli2       cliente.direc2%TYPE,
        tlfcli        cliente.telefono%TYPE,
        faxcli        cliente.fax%TYPE,
        dident        cliente.dident%TYPE,
        tident_cab    documentos_cab.tident%TYPE,
        destident     identidad.descri%TYPE,
        abrevi        identidad.abrevi%TYPE,
        nrodni        cliente_tpersona.nrodni%TYPE,
        guiarefe      documentos_cab.guiarefe%TYPE,
        almdes        documentos_cab.almdes%TYPE,
        desalmdes     almacen.descri%TYPE,
        abralmdes     almacen.abrevi%TYPE,
        marcas        documentos_cab.marcas%TYPE,
        presen        documentos_cab.presen%TYPE,
        codsec        documentos_cab.codsec%TYPE,
        facpro        documentos_cab.facpro%TYPE,
        ffacpro       documentos_cab.ffacpro%TYPE,
        codven        documentos_cab.codven%TYPE,
        observ        documentos_cab.observ%TYPE,
        tipcam        documentos_cab.tipcam%TYPE,
        tipmon        documentos_cab.tipmon%TYPE,
        totbru        documentos_cab.totbru%TYPE,
        desesp        documentos_cab.desesp%TYPE,
        descue        documentos_cab.descue%TYPE,
        monafe        documentos_cab.monafe%TYPE,
        monina        documentos_cab.monina%TYPE,
        monneto       documentos_cab.monina%TYPE,
        monigv        documentos_cab.monigv%TYPE,
        preven        documentos_cab.preven%TYPE,
        percep        NUMBER(18, 6),
        totpag        NUMBER(18, 6),
        relcossalprod motivos_clase.valor%TYPE,
        flete         documentos_cab.flete%TYPE,
        seguro        documentos_cab.seguro%TYPE,
        porigv        documentos_cab.porigv%TYPE,
        comiven       documentos_cab.comisi%TYPE,
        codmot        documentos_cab.codmot%TYPE,
        numped        documentos_cab.numped%TYPE,
        despagven     c_pago.despag%TYPE,
        enctacte      c_pago_clase.valor%TYPE,
        ordcom        documentos_cab.ordcom%TYPE,
        fordcom       documentos_cab.fordcom%TYPE,
        simbolo       tmoneda.simbolo%TYPE,
        desmon        tmoneda.desmon%TYPE,
        opnumdoc      documentos_cab.opnumdoc%TYPE,
        horing        documentos_cab.horing%TYPE,
        fecter        documentos_cab.fecter%TYPE,
        horter        documentos_cab.horter%TYPE,
        desnetx       documentos_cab.desnetx%TYPE,
        despreven     documentos_cab.despreven%TYPE,
        desfle        documentos_cab.desfle%TYPE,
        desseg        documentos_cab.desseg%TYPE,
        desgasa       documentos_cab.desgasa%TYPE,
        gasadu        documentos_cab.gasadu%TYPE,
        situac        documentos_cab.situac%TYPE,
        destin        documentos_cab.destin%TYPE,
        id            documentos_cab.id%TYPE,
        desmot        motivos.desmot%TYPE,
        docayuda      motivos.docayuda%TYPE,
        swdocpercep   VARCHAR2(1),
        porpercep     VARCHAR2(20),---
        exoimp        VARCHAR2(1),
        diaven        c_pago.diaven%TYPE,
        dessuc        sucursal.sucursal%TYPE,
        dissuc        sucursal.nomdis%TYPE,
        desven        vendedor.desven%TYPE,
        destra        transportista.descri%TYPE,
        dirtra        transportista.domici%TYPE,
        ructra        transportista.ruc%TYPE,
        punpartra     transportista.punpar%TYPE,
        desenv01      documentos_cab_almacen.direc1%TYPE,
        desenv02      documentos_cab_almacen.direc2%TYPE,
        codalm        documentos_det.codalm%TYPE,
        desalm        almacen.descri%TYPE,
        tipinv        documentos_det.tipinv%TYPE,
        codart        documentos_det.codart%TYPE,
        desart        articulos.descri%TYPE,
        faccon        articulos.faccon%TYPE,
        consto        articulos.consto%TYPE,
        peslar        articulos.faccon%TYPE,
        pesdet        NUMBER(16, 8),
        taraadic      clase_codigo.abrevi%TYPE,
        coddesart     VARCHAR2(200),
        desglosa      articulos_glosa.observ%TYPE,
            --numite documentos_det.numite%type,
        cantid        documentos_det.cantid%TYPE,
        canref        documentos_det.canref%TYPE,
        piezas        documentos_det.piezas%TYPE,
        tara          documentos_det.tara%TYPE,
        largo         documentos_det.largo%TYPE,
        etiqueta      documentos_det.etiqueta%TYPE,
        etiqeuta2     documentos_det.etiqueta2%TYPE,
        codund        articulos.coduni%TYPE,
        codadd01      documentos_det.codadd01%TYPE,
        codadd02      documentos_det.codadd02%TYPE,
        dopronumdoc   documentos_det.opronumdoc%TYPE,
        dopnumdoc     documentos_det.opnumdoc%TYPE,
        dopcargo      documentos_det.opcargo%TYPE,
        dopnumite     documentos_det.opnumite%TYPE,
        preuni        documentos_det.preuni%TYPE,
        importe_bruto documentos_det.importe_bruto%TYPE,
        importe       documentos_det.importe%TYPE,
        descdet       documentos_det.importe%TYPE,
        preuni02      documentos_det.preuni%TYPE,
        preunireal    documentos_det.preuni%TYPE,
        importereal   documentos_det.importe%TYPE,
        codunidet     documentos_det.codund%TYPE,
        pordes1       documentos_det.pordes1%TYPE,
        pordes2       documentos_det.pordes2%TYPE,
        pordes3       documentos_det.pordes3%TYPE,
        pordes4       documentos_det.pordes4%TYPE,
        monlinneto    documentos_det.monafe%TYPE,
        monafedet     documentos_det.monafe%TYPE,
        mopnigvdet    documentos_det.monigv%TYPE,
        moniscdet     documentos_det.monisc%TYPE,
        monotrdet     documentos_det.monotr%TYPE,
        nrocarrete    documentos_det.nrocarrete%TYPE,
        acabado       documentos_det.acabado%TYPE,
        lote          documentos_det.lote%TYPE,
        fvenci        documentos_det.fvenci%TYPE,
        ancho         documentos_det.ancho%TYPE,
        astpercep     VARCHAR2(1),---
        monuni        NUMBER(16, 8),
        obsdet        documentos_det.observ%TYPE
    );
    TYPE datatable_obtener_factura IS
        TABLE OF datarecord_obtener_factura;
    TYPE datarecord_obtener_cotizacion IS RECORD (
        tipdoc       documentos_cab.tipdoc%TYPE,
        numint       documentos_cab.numint%TYPE,
        series       documentos_cab.series%TYPE,
        numdoc       documentos_cab.numdoc%TYPE,
        femisi       documentos_cab.femisi%TYPE,
        codcli       documentos_cab.codcli%TYPE,
        razonc       documentos_cab.razonc%TYPE,
        direc1       documentos_cab.direc1%TYPE,
        ruc          documentos_cab.ruc%TYPE,
        tipmon       documentos_cab.tipmon%TYPE,
        tipcam       documentos_cab.tipcam%TYPE,
        numite       documentos_det.numite%TYPE,
        positi       documentos_det.positi%TYPE,
        codunddet    documentos_det.codund%TYPE,
        cantid       documentos_det.cantid%TYPE,
        preuni       documentos_det.preuni%TYPE,
        importe      documentos_det.importe%TYPE,
        pordes1      documentos_det.pordes1%TYPE,
        pordes2      documentos_det.pordes2%TYPE,
        pordes3      documentos_det.pordes3%TYPE,
        pordes4      documentos_det.pordes4%TYPE,
        ubica        documentos_det.ubica%TYPE,
        descdet      documentos_det.importe%TYPE,
        obsdet       documentos_det.observ%TYPE,
        swacti       documentos_det.swacti%TYPE,
        monneto      documentos_cab.monina%TYPE,
        monigv       documentos_cab.monigv%TYPE,
        preven       documentos_cab.preven%TYPE,
        percep       NUMBER(18, 6),
        totpag       NUMBER(18, 6),
        porigv       documentos_cab.porigv%TYPE,
        atenci       documentos_cab_contacto.atenci%TYPE,
        incigv       documentos_cab.incigv%TYPE,
        plaent       documentos_cab_contacto.plaent%TYPE,
        valide       documentos_cab_contacto.valide%TYPE,
        mailcont     documentos_cab_contacto.email%TYPE,
        numped       documentos_cab.numped%TYPE,
        situac       documentos_cab.situac%TYPE,
        obscab       documentos_cab.observ%TYPE,
        fentreg      documentos_cab.fentreg%TYPE,
        ffacpro      documentos_cab.ffacpro%TYPE,
        ordcom       documentos_cab.ordcom%TYPE,
        guiarefe     documentos_cab.guiarefe%TYPE,
        marcas       documentos_cab.marcas%TYPE,
        desart       articulos.descri%TYPE,
        codund       articulos.coduni%TYPE,
        codlin       articulos.codlin%TYPE,
        faccon       articulos.faccon%TYPE,
        conesp       articulos.conesp%TYPE,
        pesdet       NUMBER(16, 8),
        codcpag      documentos_cab.codcpag%TYPE,
        despagven    c_pago.despag%TYPE,
        glosxdes     VARCHAR2(20),
        desven       vendedor.desven%TYPE,
        carven       vendedor.cargo%TYPE,
        mailven      vendedor.email%TYPE,
        celuven      vendedor.celular%TYPE,
        tlfven       vendedor.telefo%TYPE,
        codvendedor  vendedor.codven%TYPE,
        simbolo      tmoneda.simbolo%TYPE,
        desmon       tmoneda.desmon%TYPE,
        aliassit     situacion.alias%TYPE,
        especialidad clase_vendedor_codigo.descri%TYPE,
        swdocpercep  VARCHAR2(20),
        astpercep    VARCHAR2(1),
        glosagar     companias_glosa.glosa%TYPE,
        glosagap     companias_glosa.glosa%TYPE,
        glosagfp     companias_glosa.glosa%TYPE,
        porpercep    VARCHAR2(20),
        gnotas       companias_glosa.glosa%TYPE,
        valundaltven NUMBER(18, 6),--
        ubigeo       VARCHAR(500),
        ubigeob      VARCHAR(500),
        codart       documentos_det.codart%TYPE,
        desdoc       documentos.descri%TYPE,
        abrevi       unidad.abrevi%TYPE,
        desenv01     documentos_cab_almacen.direc1%TYPE,
        destra       transportista.descri%TYPE,
        ruccia       companias.ruc%TYPE,
        codsuc       documentos_cab.codsuc%TYPE
    );
    TYPE datatable_obtener_cotizacion IS
        TABLE OF datarecord_obtener_cotizacion;
    TYPE datarecord_obtener_guia_remision IS RECORD (
        tipdoc             documentos_cab.tipdoc%TYPE,
        nomdoc             documentos.descri%TYPE,
        numint             documentos_cab.numint%TYPE,
        id                 documentos_cab.id%TYPE,
        series             documentos_cab.series%TYPE,
        numdoc             documentos_cab.numdoc%TYPE,
        femisi             documentos_cab.femisi%TYPE,
        destin             documentos_cab.destin%TYPE,
        codcli             documentos_cab.codcli%TYPE,
        razonc             documentos_cab.razonc%TYPE,
        direc1             documentos_cab.direc1%TYPE,
        ruc                documentos_cab.ruc%TYPE,
        tipcam             documentos_cab.tipcam%TYPE,
        tipmon             documentos_cab.tipmon%TYPE,
        codven             documentos_cab.codven%TYPE,
        numite             documentos_det.numite%TYPE,
        positi             documentos_det.positi%TYPE,
        tipinv             documentos_det.tipinv%TYPE,
        codart             documentos_det.codart%TYPE,
        obsdet             documentos_det.observ%TYPE,
        codund             documentos_det.codund%TYPE,
        codunidet          documentos_det.codund%TYPE,
        cantid             documentos_det.cantid%TYPE,
        cantidbase         documentos_det.cantid%TYPE,
        canref             documentos_det.canref%TYPE,
        preuni             documentos_det.preuni%TYPE,
        importe_bruto      documentos_det.importe_bruto%TYPE,
        importe            documentos_det.importe%TYPE,
        descdet            documentos_det.importe%TYPE,
        opronumdoc         documentos_det.opronumdoc%TYPE,
        swacti             documentos_det.swacti%TYPE,
        piezas             documentos_det.piezas%TYPE,
        largo              documentos_det.largo%TYPE,
        ancho              documentos_det.ancho%TYPE,
        altura             documentos_det.altura%TYPE,
        etiqueta           documentos_det.etiqueta%TYPE,
        etiqueta2          documentos_det.etiqueta2%TYPE,
        --codunidet documentos_det.codund%type,
        tara               documentos_det.tara%TYPE,
        royos              documentos_det.royos%TYPE,
        pordes1            documentos_det.pordes1%TYPE,
        pordes2            documentos_det.pordes2%TYPE,
        pordes3            documentos_det.pordes3%TYPE,
        pordes4            documentos_det.pordes4%TYPE,
        dopnumdoc          documentos_cab.opnumdoc%TYPE,
        dopcargo           documentos_det.opcargo%TYPE,
        dopnumite          documentos_det.opnumite%TYPE,
        codalm             documentos_det.codalm%TYPE,
        monafedet          documentos_det.monafe%TYPE,
        monigvdet          documentos_det.monigv%TYPE,
        lote               documentos_det.lote%TYPE,
        fvenci             documentos_det.fvenci%TYPE,
        nrocarrete         documentos_det.nrocarrete%TYPE,
        acabado            documentos_det.acabado%TYPE,
        descue             documentos_cab.descue%TYPE,
        totbru             documentos_cab.totbru%TYPE,
        monafe             documentos_cab.monafe%TYPE,
        monina             documentos_cab.monina%TYPE,
        monneto            documentos_det.monina%TYPE,
        monigv             documentos_cab.monigv%TYPE,
        preven             documentos_cab.preven%TYPE,
        porigv             documentos_cab.porigv%TYPE,
        codsuc             documentos_cab.codsuc%TYPE,
        incigv             documentos_cab.incigv%TYPE,
        numped             documentos_cab.numped%TYPE,
        codmot             documentos_cab.codmot%TYPE,
        situac             documentos_cab.situac%TYPE,
        obscab             documentos_cab.observ%TYPE,
        fentreg            documentos_cab.fentreg%TYPE,
        codarea            documentos_cab.codarea%TYPE,
        coduso             documentos_cab.coduso%TYPE,
        totcam             documentos_cab.totcan%TYPE,
        codenv             documentos_cab_almacen.codenv%TYPE,
        horing             documentos_cab.horing%TYPE,
        fecter             documentos_cab.fecter%TYPE,
        horter             documentos_cab.horter%TYPE,
        codtec             documentos_cab.codtec%TYPE,
        opnumdoc           documentos_cab.opnumdoc%TYPE,
        ordcom             documentos_cab.ordcom%TYPE,
        fordcom            documentos_cab.fordcom%TYPE,
        guiarefe           documentos_cab.guiarefe%TYPE,
        desenv01           documentos_cab_almacen.direc1%TYPE,
        desenv02           documentos_cab_almacen.direc2%TYPE,
        marcas             documentos_cab.marcas%TYPE,
        presen             documentos_cab.presen%TYPE,
        codsec             documentos_cab.codsec%TYPE,
        facpro             documentos_cab.facpro%TYPE,
        ffacpro            documentos_cab.ffacpro%TYPE,
        numvale            documentos_cab.numvale%TYPE,
        fecvale            documentos_cab.fecvale%TYPE,
        desnetx            documentos_cab.desnetx%TYPE,
        despreven          documentos_cab.despreven%TYPE,
        desfle             documentos_cab.desfle%TYPE,
        flete              documentos_cab.flete%TYPE,
        desseg             documentos_cab.desseg%TYPE,
        seguro             documentos_cab.seguro%TYPE,
        desgasa            documentos_cab.desgasa%TYPE,
        gasadu             documentos_cab.gasadu%TYPE,
        desart             articulos.descri%TYPE,
        codbar             articulos.codbar%TYPE,
        coddesart          VARCHAR2(300),
        codlin             articulos.codlin%TYPE,
        faccon             articulos.faccon%TYPE,
        consto             articulos.consto%TYPE,
        peslar             articulos.faccon%TYPE,
        pesdet             NUMBER(16, 8),
        taraadic           clase_codigo.abrevi%TYPE,
        despagven          c_pago.despag%TYPE,
        enctacte           c_pago_clase.valor%TYPE,
        diaven             c_pago.diaven%TYPE,
        dessuc             sucursal.sucursal%TYPE,
        dissuc             sucursal.nomdis%TYPE,
        dircli1            cliente.direc1%TYPE,
        dircli2            cliente.direc2%TYPE,
        emailcli           cliente.email%TYPE,
        faxcli             cliente.fax%TYPE,
        tlfcli             cliente.telefono%TYPE,
        dident             cliente.dident%TYPE,
        tident             cliente.tident%TYPE,
        desven             vendedor.desven%TYPE,
        comiven            documentos_cab.comisi%TYPE,
        codvendedor        vendedor.codven%TYPE,
        simbolo            tmoneda.simbolo%TYPE,
        desmon             tmoneda.desmon%TYPE,
        codtra             documentos_cab.codtra%TYPE,
        swdattra           transportista.swdattra%TYPE,
        razonctra          transportista.razonc%TYPE,
        destra             transportista.descri%TYPE,
        distra             transportista.domici%TYPE,
        ructra             transportista.ruc%TYPE,
        punpartra          transportista.punpar%TYPE,
        licenciatra        transportista.licenc%TYPE,
        placatra           transportista.placa%TYPE,
        certiftra          transportista.certif%TYPE,
        fonotra            transportista.telef1%TYPE,
        desveh             vehiculos.descri%TYPE,
        tipoveh            vehiculos.tipo%TYPE,
        marcaveh           vehiculos.marca%TYPE,
        placaveh           vehiculos.placa%TYPE,
        desmot             motivos.desmot%TYPE,
        direccpar          documentos_cab.direccpar%TYPE,
        ubigeopar          documentos_cab.ubigeopar%TYPE,
        tidentr            transportista.ruc%TYPE,
        tidentconductor    transportista.chofer_tident%TYPE,
        destidentconductor VARCHAR2(20)
    );
    TYPE datatable_obtener_guia_remision IS
        TABLE OF datarecord_obtener_guia_remision;
    TYPE datarecord_obtener_pedido IS RECORD (
        numint           documentos_cab.numint%TYPE,
        numite           documentos_det.numite%TYPE,
        series           documentos_cab.series%TYPE,
        numdoc           documentos_cab.numdoc%TYPE,
        femisi           documentos_cab.femisi%TYPE,
        opnumdoc         documentos_cab.opnumdoc%TYPE,
        razonc           documentos_cab.razonc%TYPE,
        direc1           documentos_cab.direc1%TYPE,
        ruc              documentos_cab.ruc%TYPE,
        tipmon           documentos_cab.tipmon%TYPE,
        fentreg          documentos_cab.fentreg%TYPE,
        fecter           documentos_cab.fecter%TYPE,
        horter           documentos_cab.horter%TYPE,
        obscab           documentos_cab.observ%TYPE,
        monafe           documentos_cab.monafe%TYPE,
        monina           documentos_cab.monina%TYPE,
        monneto          documentos_cab.monina%TYPE,
        monexo           documentos_cab.monexo%TYPE,
        monigv           documentos_cab.monigv%TYPE,
        monisc           documentos_cab.monisc%TYPE,
        monotr           documentos_cab.monotr%TYPE,
        preven           documentos_cab.preven%TYPE,
        percep           NUMBER(18, 6),
        totpag           NUMBER(18, 6),
        porigv           documentos_cab.porigv%TYPE,
        desesp           documentos_cab.desesp%TYPE,
        faxcli           cliente.fax%TYPE,
        tlfcli           cliente.telefono%TYPE,
        numped           documentos_cab.numped%TYPE,
        glosxdes         VARCHAR2(20),
        desenv01         documentos_cab_almacen.direc1%TYPE,
        destra           transportista.descri%TYPE,
        destra2          transportista.descri%TYPE,
        atenci           documentos_cab_contacto.atenci%TYPE,
        desven           vendedor.desven%TYPE,
        aliassit         VARCHAR2(50),
        dessit           situacion.dessit%TYPE,
        desmot           motivos.desmot%TYPE,
        codart           documentos_det.codart%TYPE,
        desart           articulos.descri%TYPE,
        consto           articulos.consto%TYPE,
        codalm           documentos_det.codalm%TYPE,
        obsdet           documentos_det.observ%TYPE,
        monafedet        documentos_det.monafe%TYPE,
        moninadet        documentos_det.monina%TYPE,
        moniscdet        documentos_det.monisc%TYPE,
        monigvdet        documentos_det.monigv%TYPE,
        monotrdet        documentos_det.monotr%TYPE,
        codunddet        documentos_det.codund%TYPE,
        codund           articulos.coduni%TYPE,
        cantid           documentos_det.cantid%TYPE,
        piezas           documentos_det.piezas%TYPE,
        largo            documentos_det.largo%TYPE,
        ancho            documentos_det.ancho%TYPE,
        preuni           documentos_det.preuni%TYPE,
        importe          documentos_det.importe%TYPE,
        importe_bruto    documentos_det.importe_bruto%TYPE,
        pordes1          documentos_det.pordes1%TYPE,
        pordes2          documentos_det.pordes2%TYPE,
        pordes3          documentos_det.pordes3%TYPE,
        pordes4          documentos_det.pordes4%TYPE,
        opronumdoc       documentos_det.opronumdoc%TYPE,
        etiqueta         documentos_det.etiqueta%TYPE,
        acabado          documentos_det.acabado%TYPE,
        nrocarrete       documentos_det.nrocarrete%TYPE,
        stockk001        kardex001.salida%TYPE,
        saldo            kardex001.salida%TYPE,
        simbolo          tmoneda.simbolo%TYPE,
        desmon           tmoneda.desmon%TYPE,
        porpercep        VARCHAR2(20),
        swdocpercep      VARCHAR2(1),
        astpercep        VARCHAR2(1),
        glosagar         companias_glosa.glosa%TYPE,
        glosagap         companias_glosa.glosa%TYPE,
        glosagfp         companias_glosa.glosa%TYPE,
        codpiepagforf01  documentos_clase.vstrg%TYPE,
        codpiepagforf02  documentos_clase.vstrg%TYPE,
        valundaltven     NUMBER(12, 6),
        c_visadopor      documentos_situac_max.usuari%TYPE,
        visadopor        usuarios.nombres%TYPE,
        c_emitidopor     documentos_situac_max.usuari%TYPE,
        emitidopor       usuarios.nombres%TYPE,
        c_aprobadopor    documentos_aprobacion.uactua%TYPE,
        aprobadopor      usuarios.nombres%TYPE,
        situac_aprob     VARCHAR2(1),
        ubigeo           VARCHAR2(500),
        ubigeo_b         VARCHAR2(500),
        fecha_dcorcom    documentos_cab_ordcom.fecha%TYPE,
        numero_dcordom   documentos_cab_ordcom.numero%TYPE,
        contacto_dcordom documentos_cab_ordcom.contacto%TYPE,
        abrunidad        unidad.abrevi%TYPE,
        codadd01         documentos_det.codadd01%TYPE,
        descodadd01      cliente_articulos_clase.descri%TYPE,
        codadd02         documentos_det.codadd02%TYPE,
        descodadd02      cliente_articulos_clase.descri%TYPE,
        codsuc           documentos_cab.codsuc%TYPE
    );
    TYPE datatable_obtener_pedido IS
        TABLE OF datarecord_obtener_pedido;
    PROCEDURE sp_save (
        pin_id_cia  IN NUMBER,
        pin_datos   IN VARCHAR2,
        pin_opcdml  INTEGER,
        pin_mensaje OUT VARCHAR2
    );

    FUNCTION sp_cotizaciones_padre (
        pin_id_cia NUMBER,
        pin_fhasta DATE,
        pin_tipmon VARCHAR2,
        pin_codsuc NUMBER,
        pin_codcli VARCHAR2
    ) RETURN datatable_cotizaciones_padre
        PIPELINED;

    FUNCTION sp_guias_remision_padre (
        pin_id_cia NUMBER,
        pin_fhasta DATE,
        pin_codsuc NUMBER,
        pin_codcli VARCHAR2,
        pin_tipmon VARCHAR2,
        pin_codmot NUMBER,
        pin_periodo NUMBER,
        pin_mes NUMBER
    ) RETURN datatable_guias_remision_padre
        PIPELINED;

    FUNCTION sp_ordenes_pedido_padre (
        pin_id_cia NUMBER,
        pin_fhasta DATE,
        pin_codsuc NUMBER,
        pin_codcli VARCHAR2,
        pin_tipmon VARCHAR2,
        pin_codmot NUMBER,
        pin_docdes INTEGER
    ) RETURN datatable_ordenes_pedido_padre
        PIPELINED;

    FUNCTION sp_ordenes_produccion_padre (
        pin_id_cia NUMBER,
        pin_fhasta DATE,
        pin_codsuc NUMBER,
        pin_codcli VARCHAR2,
        pin_tipmon VARCHAR2,
        pin_codmot NUMBER
    ) RETURN datatable_ordenes_pedido_padre
        PIPELINED;

    FUNCTION sp_ordenes_devolucion_padre (
        pin_id_cia NUMBER,
        pin_fhasta DATE,
        pin_codsuc NUMBER,
        pin_codcli VARCHAR2,
        pin_tipmon VARCHAR2,
        pin_codmot NUMBER
    ) RETURN datatable_ordenes_pedido_padre
        PIPELINED;

    FUNCTION sp_facturas_padre (
        pin_id_cia NUMBER,
        pin_fhasta DATE,
        pin_codsuc NUMBER,
        pin_codcli VARCHAR2,
        pin_tipmon VARCHAR2,
        pin_periodo NUMBER,
        pin_mes NUMBER
    ) RETURN datatable_facturas_padre
        PIPELINED;

    FUNCTION sp_facturas_devolucion_padre (
        pin_id_cia NUMBER,
        pin_fhasta DATE,
        pin_codsuc NUMBER,
        pin_codcli VARCHAR2,
        pin_tipmon VARCHAR2,
        pin_periodo NUMBER,
        pin_mes NUMBER
    ) RETURN datatable_facturas_padre
        PIPELINED;

    FUNCTION sp_boleta_padre (
        pin_id_cia NUMBER,
        pin_fhasta DATE,
        pin_codsuc NUMBER,
        pin_codcli VARCHAR2,
        pin_tipmon VARCHAR2,
        pin_periodo NUMBER,
        pin_mes NUMBER
    ) RETURN datatable_boleta_padre
        PIPELINED;

    FUNCTION sp_boleta_devolucion_padre (
        pin_id_cia NUMBER,
        pin_fhasta DATE,
        pin_codsuc NUMBER,
        pin_codcli VARCHAR2,
        pin_tipmon VARCHAR2,
        pin_periodo NUMBER,
        pin_mes NUMBER
    ) RETURN datatable_boleta_padre
        PIPELINED;

    FUNCTION sp_req_compras_padre (
        pin_id_cia NUMBER,
        pin_fhasta DATE,
        pin_codsuc NUMBER,
        pin_codcli VARCHAR2,
        pin_tipmon VARCHAR2
    ) RETURN datatable_req_compras_padre
        PIPELINED;

    FUNCTION sp_orden_compras_padre (
        pin_id_cia NUMBER,
        pin_fhasta DATE,
        pin_codsuc NUMBER,
        pin_codcli VARCHAR2,
        pin_tipmon VARCHAR2,
        pin_destin NUMBER
    ) RETURN datatable_orden_compras_padre
        PIPELINED;

    FUNCTION sp_guias_interna_padre (
        pin_id_cia NUMBER,
        pin_fhasta DATE,
        pin_codcli VARCHAR2,
        pin_codmot NUMBER,
        pin_id     NUMBER
    ) RETURN datatable_guias_interna_padre
        PIPELINED;

    FUNCTION sp_conforme_para_anular (
        pin_id_cia  IN NUMBER,
        pin_tipdoc  IN NUMBER,
        pin_coduser VARCHAR2
    ) RETURN VARCHAR2;

    FUNCTION sp_obtener_comprobante (
        pin_id_cia IN NUMBER,
        pin_numint IN NUMBER
    ) RETURN datatable_obtener_comprobante
        PIPELINED;

    FUNCTION sp_obtener_factura (
        pin_id_cia IN NUMBER,
        pin_numint IN NUMBER
    ) RETURN datatable_obtener_factura
        PIPELINED;

    FUNCTION sp_obtener_cotizacion (
        pin_id_cia IN NUMBER,
        pin_numint IN NUMBER
    ) RETURN datatable_obtener_cotizacion
        PIPELINED;

    FUNCTION sp_obtener_guia_remision (
        pin_id_cia IN NUMBER,
        pin_numint IN NUMBER
    ) RETURN datatable_obtener_guia_remision
        PIPELINED;

    FUNCTION sp_obtener_pedido (
        pin_id_cia IN NUMBER,
        pin_numint IN NUMBER
    ) RETURN datatable_obtener_pedido
        PIPELINED;

END pack_documentos_cab;

/
