--------------------------------------------------------
--  DDL for Table PCUENTASTCCOSTOS
--------------------------------------------------------

  CREATE TABLE "USR_TSI_SUITE"."PCUENTASTCCOSTOS" 
   (	"ID_CIA" NUMBER(*,0), 
	"CUENTA" VARCHAR2(16 BYTE), 
	"CCOSTO" VARCHAR2(16 BYTE), 
	"PORCENTAJE" NUMBER(9,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_TSI_SUITE" ;
