--------------------------------------------------------
--  DDL for Table PERSONAL
--------------------------------------------------------

  CREATE TABLE "USR_TSI_SUITE"."PERSONAL" 
   (	"ID_CIA" NUMBER, 
	"CODPER" VARCHAR2(20 BYTE), 
	"APEPAT" VARCHAR2(40 BYTE), 
	"APEMAT" VARCHAR2(40 BYTE), 
	"NOMBRE" VARCHAR2(50 BYTE), 
	"DIRECC" VARCHAR2(100 BYTE), 
	"NROTLF" VARCHAR2(40 BYTE), 
	"SEXPER" VARCHAR2(1 BYTE), 
	"FECNAC" TIMESTAMP (6), 
	"CODECI" VARCHAR2(2 BYTE), 
	"TIPTRA" VARCHAR2(1 BYTE), 
	"CODNAC" VARCHAR2(4 BYTE), 
	"CODCAR" VARCHAR2(2 BYTE), 
	"FORPAG" VARCHAR2(1 BYTE), 
	"CODBAN" NUMBER, 
	"TIPCTA" NUMBER, 
	"CODMON" VARCHAR2(5 BYTE), 
	"NROCTA" VARCHAR2(20 BYTE), 
	"SITUAC" VARCHAR2(2 BYTE), 
	"CODEST" VARCHAR2(2 BYTE), 
	"GLONOT" VARCHAR2(4000 BYTE), 
	"CODAFP" VARCHAR2(4 BYTE), 
	"FOTOGR" BLOB, 
	"FORMATO" VARCHAR2(3 BYTE), 
	"CODSUC" NUMBER(*,0), 
	"EMAIL" VARCHAR2(200 BYTE), 
	"UCREAC" VARCHAR2(10 BYTE), 
	"UACTUA" VARCHAR2(10 BYTE), 
	"FCREAC" TIMESTAMP (6), 
	"FACTUA" TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_TSI_SUITE" 
 LOB ("FOTOGR") STORE AS SECUREFILE (
  TABLESPACE "TBS_TSI_SUITE" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
