--------------------------------------------------------
--  DDL for Table PERSONAL_DEPENDIENTE
--------------------------------------------------------

  CREATE TABLE "USR_TSI_SUITE"."PERSONAL_DEPENDIENTE" 
   (	"ID_CIA" NUMBER, 
	"CODPER" VARCHAR2(20 BYTE), 
	"ITEM" NUMBER(*,0), 
	"NUMDOC" VARCHAR2(40 BYTE), 
	"CLAS03" NUMBER, 
	"CODI03" VARCHAR2(20 BYTE), 
	"APEPAT" VARCHAR2(40 BYTE), 
	"APEMAT" VARCHAR2(40 BYTE), 
	"NOMBRE" VARCHAR2(50 BYTE), 
	"FECNAC" DATE, 
	"SEXO" VARCHAR2(1 BYTE), 
	"CLAS19" NUMBER, 
	"CODI19" VARCHAR2(20 BYTE), 
	"FECALT" DATE, 
	"CLAS20" NUMBER, 
	"CODI20" VARCHAR2(20 BYTE), 
	"MISDOM" VARCHAR2(1 BYTE), 
	"UCREAC" VARCHAR2(10 BYTE), 
	"UACTUA" VARCHAR2(10 BYTE), 
	"FCREAC" TIMESTAMP (6), 
	"FACTUA" TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_TSI_SUITE" ;
