--------------------------------------------------------
--  Constraints for Table PERSONAL_PERIODOLABORAL
--------------------------------------------------------

  ALTER TABLE "USR_TSI_SUITE"."PERSONAL_PERIODOLABORAL" MODIFY ("FINICIO" NOT NULL ENABLE);
  ALTER TABLE "USR_TSI_SUITE"."PERSONAL_PERIODOLABORAL" MODIFY ("ID_CIA" NOT NULL ENABLE);
  ALTER TABLE "USR_TSI_SUITE"."PERSONAL_PERIODOLABORAL" MODIFY ("CODPER" NOT NULL ENABLE);
  ALTER TABLE "USR_TSI_SUITE"."PERSONAL_PERIODOLABORAL" MODIFY ("ID_PLAB" NOT NULL ENABLE);
  ALTER TABLE "USR_TSI_SUITE"."PERSONAL_PERIODOLABORAL" ADD CONSTRAINT "PK_PERSONALPLAB" PRIMARY KEY ("ID_CIA", "CODPER", "ID_PLAB")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_TSI_SUITE"  ENABLE;
