--------------------------------------------------------
--  Ref Constraints for Table PERSONAL_PERIODO_RPENSION
--------------------------------------------------------

  ALTER TABLE "USR_TSI_SUITE"."PERSONAL_PERIODO_RPENSION" ADD CONSTRAINT "FK_PERSONAL_PERIODO_RPENSION_PERSONAL" FOREIGN KEY ("ID_CIA", "CODPER")
	  REFERENCES "USR_TSI_SUITE"."PERSONAL" ("ID_CIA", "CODPER") ENABLE;
  ALTER TABLE "USR_TSI_SUITE"."PERSONAL_PERIODO_RPENSION" ADD CONSTRAINT "FK_PERSONAL_PERIODO_RPENSION_AFP" FOREIGN KEY ("ID_CIA", "CODAFP")
	  REFERENCES "USR_TSI_SUITE"."AFP" ("ID_CIA", "CODAFP") ENABLE;
