--------------------------------------------------------
--  Constraints for Table PERSONAL_CONTRATOS_ADJUNTO
--------------------------------------------------------

  ALTER TABLE "USR_TSI_SUITE"."PERSONAL_CONTRATOS_ADJUNTO" MODIFY ("ID_CIA" NOT NULL ENABLE);
  ALTER TABLE "USR_TSI_SUITE"."PERSONAL_CONTRATOS_ADJUNTO" MODIFY ("CODPER" NOT NULL ENABLE);
  ALTER TABLE "USR_TSI_SUITE"."PERSONAL_CONTRATOS_ADJUNTO" MODIFY ("NROCON" NOT NULL ENABLE);
  ALTER TABLE "USR_TSI_SUITE"."PERSONAL_CONTRATOS_ADJUNTO" MODIFY ("ITEM" NOT NULL ENABLE);
  ALTER TABLE "USR_TSI_SUITE"."PERSONAL_CONTRATOS_ADJUNTO" ADD CONSTRAINT "PK_PERSONAL_CONTRATOS_ADJUNTO" PRIMARY KEY ("ID_CIA", "CODPER", "NROCON", "ITEM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_TSI_SUITE"  ENABLE;
