--------------------------------------------------------
--  Ref Constraints for Table PERSONAL_CTS
--------------------------------------------------------

  ALTER TABLE "USR_TSI_SUITE"."PERSONAL_CTS" ADD CONSTRAINT "FK_PERSONAL_CTS_TBANCOS" FOREIGN KEY ("ID_CIA", "CODBAN")
	  REFERENCES "USR_TSI_SUITE"."E_FINANCIERA" ("ID_CIA", "CODIGO") ENABLE;
  ALTER TABLE "USR_TSI_SUITE"."PERSONAL_CTS" ADD CONSTRAINT "FK_PERSONAL_CTS_PERSONAL" FOREIGN KEY ("ID_CIA", "CODPER")
	  REFERENCES "USR_TSI_SUITE"."PERSONAL" ("ID_CIA", "CODPER") ENABLE;
