--------------------------------------------------------
--  Constraints for Table PERSONAL_CCOSTO
--------------------------------------------------------

  ALTER TABLE "USR_TSI_SUITE"."PERSONAL_CCOSTO" MODIFY ("ID_CIA" NOT NULL ENABLE);
  ALTER TABLE "USR_TSI_SUITE"."PERSONAL_CCOSTO" MODIFY ("CODPER" NOT NULL ENABLE);
  ALTER TABLE "USR_TSI_SUITE"."PERSONAL_CCOSTO" MODIFY ("CODCCO" NOT NULL ENABLE);
  ALTER TABLE "USR_TSI_SUITE"."PERSONAL_CCOSTO" ADD CONSTRAINT "PK_PERSONAL_CCOSTO" PRIMARY KEY ("ID_CIA", "CODPER", "CODCCO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_TSI_SUITE"  ENABLE;
