--------------------------------------------------------
--  Constraints for Table PERSONAL_PERIODO_RPENSION
--------------------------------------------------------

  ALTER TABLE "USR_TSI_SUITE"."PERSONAL_PERIODO_RPENSION" MODIFY ("ID_CIA" NOT NULL ENABLE);
  ALTER TABLE "USR_TSI_SUITE"."PERSONAL_PERIODO_RPENSION" MODIFY ("CODPER" NOT NULL ENABLE);
  ALTER TABLE "USR_TSI_SUITE"."PERSONAL_PERIODO_RPENSION" MODIFY ("CODAFP" NOT NULL ENABLE);
  ALTER TABLE "USR_TSI_SUITE"."PERSONAL_PERIODO_RPENSION" MODIFY ("ID_PRPEN" NOT NULL ENABLE);
  ALTER TABLE "USR_TSI_SUITE"."PERSONAL_PERIODO_RPENSION" ADD CONSTRAINT "PK_PERSONAL_PERIODO_RPENSION" PRIMARY KEY ("ID_CIA", "CODPER", "ID_PRPEN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_TSI_SUITE"  ENABLE;
