--------------------------------------------------------
--  DDL for Index PK_DCTA103_APROBACION
--------------------------------------------------------

  CREATE UNIQUE INDEX "USR_TSI_SUITE"."PK_DCTA103_APROBACION" ON "USR_TSI_SUITE"."DCTA103_APROBACION" ("ID_CIA", "LIBRO", "PERIODO", "MES", "SECUENCIA", "ITEM", "NUMINT", "TIPO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_TSI_SUITE" ;
