--------------------------------------------------------
--  DDL for Index PK_FE_RESUMENDIARIO_DET
--------------------------------------------------------

  CREATE UNIQUE INDEX "USR_TSI_SUITE"."PK_FE_RESUMENDIARIO_DET" ON "USR_TSI_SUITE"."FE_RESUMENDIARIO_DET" ("ID_CIA", "IDRES", "NUMINT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_TSI_SUITE" ;
