--------------------------------------------------------
--  DDL for Package PKG_EXCEPTIONUSER
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE PACKAGE "USR_TSI_SUITE"."PKG_EXCEPTIONUSER" AS
    cuenta_en_blanco NUMBER := -20001;
    ex_cuenta_en_blanco EXCEPTION;
    PRAGMA exception_init ( ex_cuenta_en_blanco, -20001 );
    saldo_en_negativo NUMBER := -20002;
    ex_saldo_en_negativo EXCEPTION;
    PRAGMA exception_init ( ex_saldo_en_negativo, -20002 );
    saldo_saldo_mayor NUMBER := -20003;
    ex_saldo_mayor EXCEPTION;
    PRAGMA exception_init ( ex_saldo_mayor, -20003 );
    libro_correlativo_no_existe NUMBER := -20004;
    ex_libro_correlativo_no_existe EXCEPTION;
    PRAGMA exception_init ( ex_libro_correlativo_no_existe, -20004 );
    mes_cerrado_contabilidad NUMBER := -20005;
    ex_mes_cerrado_contabilidad EXCEPTION;
    PRAGMA exception_init ( ex_mes_cerrado_contabilidad, -20005 );
    mes_cerrado_ctaxcobrar NUMBER := -20006;
    ex_mes_cerrado_ctaxcobrar EXCEPTION;
    PRAGMA exception_init ( ex_mes_cerrado_ctaxcobrar, -20006 );
    mes_cerrado_comercial NUMBER := -20007;
    ex_mes_cerrado_comercial EXCEPTION;
    PRAGMA exception_init ( ex_mes_cerrado_comercial, -20007 );
    mes_cerrado_logistica NUMBER := -20008;
    ex_mes_cerrado_logistica EXCEPTION;
    PRAGMA exception_init ( ex_mes_cerrado_logistica, -20008 );
    mes_cerrado_ctaxpagar NUMBER := -20009;
    ex_mes_cerrado_ctaxpagar EXCEPTION;
    PRAGMA exception_init ( ex_mes_cerrado_ctaxpagar, -20009 );
    numero_repetido_doccab NUMBER := -20010;
    ex_numero_repetido_doccab EXCEPTION;
    PRAGMA exception_init ( ex_numero_repetido_doccab, -20010 );
    fecha_no_valida NUMBER := -20011;
    ex_fecha_no_valida EXCEPTION;
    PRAGMA exception_init ( ex_fecha_no_valida, -20011 );
    tcambio_no_existe NUMBER := -20011;
    ex_tcambio_no_existe EXCEPTION;
    PRAGMA exception_init ( ex_tcambio_no_existe, -20011 );
    documento_relacionado_anulado NUMBER := -20012;
    ex_documento_relacionado_anulado EXCEPTION;
    PRAGMA exception_init ( ex_documento_relacionado_anulado, -20012 );
    gen_documentos_cab_log_no_existe NUMBER := -20013;
    ex_gen_documentos_cab_log EXCEPTION;
    PRAGMA exception_init ( ex_gen_documentos_cab_log, -20013 );
    gen_kardex_no_existe NUMBER := -20014;
    ex_gen_kardex EXCEPTION;
    PRAGMA exception_init ( ex_gen_kardex, -20014 );
    gen_dcta102_caja_cab_no_existe NUMBER := -20015;
    ex_gen_dcta102_caja_cab EXCEPTION;
    PRAGMA exception_init ( ex_gen_dcta102_caja_cab, -20015 );
    documento_tiene_pagos NUMBER := -20016;
    ex_documento_tiene_pagos EXCEPTION;
    PRAGMA exception_init ( ex_documento_tiene_pagos, -20016 );
    no_existe_numint NUMBER := -20017;
    ex_no_existe_numint EXCEPTION;
    PRAGMA exception_init ( ex_no_existe_numint, -20017 );
    compr010_recibo_duplicado NUMBER := -20018;
    ex_compr010_recibo_duplicado EXCEPTION;
    PRAGMA exception_init ( ex_compr010_recibo_duplicado, -20018 );
    compr010_liq_com_duplicado NUMBER := -20019;
    ex_compr010_liq_com_duplicado EXCEPTION;
    PRAGMA exception_init ( ex_compr010_liq_com_duplicado, -20019 );
    clase_codigo_1_9_no_existe NUMBER := -20020;
    ex_clase_codigo_1_9_no_existe EXCEPTION;
    PRAGMA exception_init ( ex_clase_codigo_1_9_no_existe, -20020 );
    clase_codigo_no_existe NUMBER := -20021;
    ex_clase_codigo_no_existe EXCEPTION;
    PRAGMA exception_init ( ex_clase_codigo_no_existe, -20021 );
    registro_key_null NUMBER := -20022;
    ex_registro_key_null EXCEPTION;
    PRAGMA exception_init ( ex_registro_key_null, -20022 );
    clase_articulos_alternativo_no_existe NUMBER := -20023;
    ex_clase_articulos_alternativo_no_existe EXCEPTION;
    PRAGMA exception_init ( ex_clase_articulos_alternativo_no_existe, -20023 );
    registro_duplicado NUMBER := -20024;
    ex_registro_duplicado EXCEPTION;
    PRAGMA exception_init ( ex_registro_duplicado, -20024 );
    registro_relacionado NUMBER := -20025;
    ex_registro_relacionado EXCEPTION;
    PRAGMA exception_init ( ex_registro_relacionado, -20025 );
    codigo_no_existe_pcuentas NUMBER := -20026;
    ex_codigo_no_existe_pcuentas EXCEPTION;
    PRAGMA exception_init ( ex_codigo_no_existe_pcuentas, -20026 );
    destin_no_existe_pcuentas NUMBER := -20027;
    ex_destin_no_existe_pcuentas EXCEPTION;
    PRAGMA exception_init ( ex_destin_no_existe_pcuentas, -20027 );
    generador_no_existe NUMBER := -20028;
    ex_generador_no_existe EXCEPTION;
    PRAGMA exception_init ( ex_generador_no_existe, -20028 );
    clase_pcuentas_codigo_no_existe NUMBER := -20029;
    ex_clase_pcuentas_codigo_no_existe EXCEPTION;
    PRAGMA exception_init ( ex_clase_pcuentas_codigo_no_existe, -20029 );
    clase_pcuentas_no_existe NUMBER := -20030;
    ex_clase_pcuentas_no_existe EXCEPTION;
    PRAGMA exception_init ( ex_clase_pcuentas_no_existe, -20030 );
    cuenta_relacionada_01 NUMBER := -20031;
    ex_cuenta_relacionada_01 EXCEPTION;
    PRAGMA exception_init ( ex_cuenta_relacionada_01, -20031 );
    cuenta_relacionada_02 NUMBER := -20032;
    ex_cuenta_relacionada_02 EXCEPTION;
    PRAGMA exception_init ( ex_cuenta_relacionada_02, -20032 );
    cuenta_relacionada_03 NUMBER := -20033;
    ex_cuenta_relacionada_03 EXCEPTION;
    PRAGMA exception_init ( ex_cuenta_relacionada_03, -20033 );
    cuenta_relacionada_04 NUMBER := -20034;
    ex_cuenta_relacionada_04 EXCEPTION;
    PRAGMA exception_init ( ex_cuenta_relacionada_04, -20034 );
    tiene_movimientos NUMBER := -20035;
    ex_tiene_movimientos EXCEPTION;
    PRAGMA exception_init ( ex_tiene_movimientos, -20035 );
    error_inesperado NUMBER := -20036;
    ex_error_inesperado EXCEPTION;
    PRAGMA exception_init ( ex_error_inesperado, -20036 );
    cliente_con_referencia NUMBER := -20037;
    ex_cliente_con_referencia EXCEPTION;
    PRAGMA exception_init ( ex_cliente_con_referencia, -20037 );
    libro_en_blanco NUMBER := -20038;
    ex_libro_en_blanco EXCEPTION;
    PRAGMA exception_init ( ex_libro_en_blanco, -20038 );
    cliente_con_mas_de_una_cpago_defaul NUMBER := -20039;
    ex_cliente_con_mas_de_una_cpago_defaul EXCEPTION;
    PRAGMA exception_init ( ex_cliente_con_mas_de_una_cpago_defaul, -20039 );
    movimiento_relacionado NUMBER := -20040;
    ex_movimiento_relacionado EXCEPTION;
    PRAGMA exception_init ( ex_movimiento_relacionado, -20040 );
    destin_no_existe_tccostos NUMBER := -20041;
    ex_destin_no_existe_tccostos EXCEPTION;
    PRAGMA exception_init ( ex_destin_no_existe_tccostos, -20041 );
    codigo_no_existe_tccostos NUMBER := -20042;
    ex_codigo_no_existe_tccostos EXCEPTION;
    PRAGMA exception_init ( ex_codigo_no_existe_tccostos, -20042 );
    documento_con_operaciones NUMBER := -20043;
    ex_documento_con_operaciones EXCEPTION;
    PRAGMA exception_init ( ex_documento_con_operaciones, -20043 );
    usuario_sin_permiso NUMBER := -20044;
    ex_usuario_sin_permiso EXCEPTION;
    PRAGMA exception_init ( ex_usuario_sin_permiso, -20044 );
    documento_con_relaciones NUMBER := -20045;
    ex_documento_con_relaciones EXCEPTION;
    PRAGMA exception_init ( ex_documento_con_relaciones, -20045 );
    documento_con_correlaciones NUMBER := -20046;
    ex_documento_con_correlaciones EXCEPTION;
    PRAGMA exception_init ( ex_documento_con_correlaciones, -20046 );
    documento_con_planillas NUMBER := -20047;
    ex_documento_con_planillas EXCEPTION;
    PRAGMA exception_init ( ex_documento_con_planillas, -20047 );
    documento_no_existe NUMBER := -20048;
    ex_documento_no_existe EXCEPTION;
    PRAGMA exception_init ( ex_documento_no_existe, -20048 );
    mes_cerrado_planilla NUMBER := -20049;
    ex_mes_cerrado_planilla EXCEPTION;
    PRAGMA exception_init ( ex_mes_cerrado_planilla, -20049 );
END pkg_exceptionuser;

/
