--------------------------------------------------------
--  DDL for Table PLANILLA_CONCEPTO_LEYENDA
--------------------------------------------------------

  CREATE TABLE "USR_TSI_SUITE"."PLANILLA_CONCEPTO_LEYENDA" 
   (	"ID_CIA" NUMBER, 
	"NUMPLA" NUMBER, 
	"CODPER" VARCHAR2(20 CHAR), 
	"CODORI" VARCHAR2(20 CHAR), 
	"CODDES" VARCHAR2(20 CHAR), 
	"TIPORI" VARCHAR2(2 CHAR), 
	"DTIPORI" VARCHAR2(100 CHAR), 
	"NIVEL" NUMBER, 
	"CODLEY" VARCHAR2(20 CHAR), 
	"DESLEY" VARCHAR2(250 CHAR), 
	"VALCON" VARCHAR2(4000 CHAR), 
	"FORMUL" VARCHAR2(4000 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_TSI_SUITE" ;
