--------------------------------------------------------
--  Ref Constraints for Table PLANILLA_CONCEPTO
--------------------------------------------------------

  ALTER TABLE "USR_TSI_SUITE"."PLANILLA_CONCEPTO" ADD CONSTRAINT "FK_PLANILLA_CONCEPTO_PERSONAL" FOREIGN KEY ("ID_CIA", "CODPER")
	  REFERENCES "USR_TSI_SUITE"."PERSONAL" ("ID_CIA", "CODPER") ENABLE;
  ALTER TABLE "USR_TSI_SUITE"."PLANILLA_CONCEPTO" ADD CONSTRAINT "FK_PLANILLA_CONCEPTO_CONCEPTO" FOREIGN KEY ("ID_CIA", "CODCON")
	  REFERENCES "USR_TSI_SUITE"."CONCEPTO" ("ID_CIA", "CODCON") ENABLE;
