--------------------------------------------------------
--  DDL for Table PRESTAMO
--------------------------------------------------------

  CREATE TABLE "USR_TSI_SUITE"."PRESTAMO" 
   (	"ID_CIA" NUMBER, 
	"ID_PRE" NUMBER(*,0), 
	"CODPER" VARCHAR2(20 CHAR), 
	"FECPRE" DATE, 
	"MONPRE" NUMBER(15,4), 
	"MONPAG" NUMBER(15,4), 
	"CODMON" VARCHAR2(5 CHAR), 
	"CANCUO" NUMBER(*,0), 
	"VALCUO" NUMBER(15,4), 
	"SALPRE" NUMBER(15,4), 
	"OBSERV" VARCHAR2(4000 CHAR), 
	"MODIFI" VARCHAR2(1 CHAR), 
	"SITUAC" VARCHAR2(1 CHAR), 
	"UCREAC" VARCHAR2(10 BYTE), 
	"UACTUA" VARCHAR2(10 BYTE), 
	"FCREAC" TIMESTAMP (6), 
	"FACTUA" TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_TSI_SUITE" ;
