--------------------------------------------------------
--  Ref Constraints for Table PRESTAMO_TIPOPLANILLA
--------------------------------------------------------

  ALTER TABLE "USR_TSI_SUITE"."PRESTAMO_TIPOPLANILLA" ADD CONSTRAINT "FK_PRESTAMO_TIPOPLANILLA_PRESTAMO" FOREIGN KEY ("ID_CIA", "ID_PRE")
	  REFERENCES "USR_TSI_SUITE"."PRESTAMO" ("ID_CIA", "ID_PRE") ENABLE;
  ALTER TABLE "USR_TSI_SUITE"."PRESTAMO_TIPOPLANILLA" ADD CONSTRAINT "FK_PRESTAMO_TIPOPLANILLA_TIPOPLANILLA" FOREIGN KEY ("ID_CIA", "TIPPLA")
	  REFERENCES "USR_TSI_SUITE"."TIPOPLANILLA" ("ID_CIA", "TIPPLA") ENABLE;
