--------------------------------------------------------
--  DDL for Table PROCESO_COSTO_KARDEX
--------------------------------------------------------

  CREATE TABLE "USR_TSI_SUITE"."PROCESO_COSTO_KARDEX" 
   (	"ID_CIA" NUMBER(*,0), 
	"LOCALI" NUMBER(*,0), 
	"ID" CHAR(1 BYTE), 
	"PERIODO" NUMBER(*,0), 
	"CODMOT" NUMBER(*,0), 
	"TIPINV" NUMBER(*,0), 
	"CODART" VARCHAR2(40 BYTE), 
	"CANTID" NUMBER(16,4), 
	"COSTOT01" NUMBER(16,2), 
	"COSTOT02" NUMBER(16,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_TSI_SUITE" ;
