--------------------------------------------------------
--  DDL for Table PROPIEDADES_USUARIOS
--------------------------------------------------------

  CREATE TABLE "USR_TSI_SUITE"."PROPIEDADES_USUARIOS" 
   (	"CODIGO" NUMBER(*,0), 
	"NOMBRE" VARCHAR2(100 BYTE), 
	"SWFLAG" VARCHAR2(1 BYTE), 
	"OBSERV" VARCHAR2(3000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_TSI_SUITE" ;
