--------------------------------------------------------
--  DDL for Table PROV102
--------------------------------------------------------

  CREATE TABLE "USR_TSI_SUITE"."PROV102" 
   (	"ID_CIA" NUMBER(*,0), 
	"LIBRO" VARCHAR2(3 BYTE), 
	"PERIODO" NUMBER(*,0), 
	"MES" NUMBER(*,0), 
	"SECUENCIA" NUMBER(*,0), 
	"DIA" NUMBER(*,0), 
	"CODCOB" NUMBER(*,0), 
	"FEMISI" DATE, 
	"TIPCAM" NUMBER(9,6), 
	"CODSUC" NUMBER(*,0), 
	"FCREAC" TIMESTAMP (6), 
	"FACTUA" TIMESTAMP (6), 
	"CODUSERCREA" VARCHAR2(10 BYTE), 
	"USUARI" VARCHAR2(10 BYTE), 
	"SITUAC" CHAR(1 BYTE), 
	"CONPAG" NUMBER(*,0), 
	"TIPMON" VARCHAR2(5 BYTE), 
	"EXTORNO" NUMBER(*,0), 
	"DEPOSITO" NUMBER(16,5), 
	"SWRETENCION" VARCHAR2(1 BYTE), 
	"SWCHKAJUSCEN" VARCHAR2(1 BYTE), 
	"CONCEP" VARCHAR2(150 BYTE), 
	"CODBAN" VARCHAR2(3 BYTE), 
	"REFERENCIA" VARCHAR2(30 BYTE), 
	"GIRARA" VARCHAR2(70 BYTE), 
	"TIPPLA" NUMBER(*,0), 
	"SWACTI" VARCHAR2(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_TSI_SUITE" ;
