--------------------------------------------------------
--  DDL for Table PROV113
--------------------------------------------------------

  CREATE TABLE "USR_TSI_SUITE"."PROV113" 
   (	"ID_CIA" NUMBER(*,0), 
	"LIBRO" VARCHAR2(3 BYTE), 
	"PERIODO" NUMBER(*,0), 
	"MES" NUMBER(*,0), 
	"SECUENCIA" NUMBER(*,0), 
	"ITEM" NUMBER(*,0), 
	"TIPO" NUMBER(*,0), 
	"DOCU" NUMBER(*,0), 
	"TIPCAN" NUMBER(*,0), 
	"CUENTA" VARCHAR2(16 BYTE), 
	"DH" CHAR(1 BYTE), 
	"TIPMON" VARCHAR2(5 BYTE), 
	"DOCCAN" VARCHAR2(20 BYTE), 
	"DOCUME" VARCHAR2(25 BYTE), 
	"TIPCAM" NUMBER(16,6), 
	"AMORTI" NUMBER(16,2), 
	"TCAMB01" NUMBER(16,6), 
	"TCAMB02" NUMBER(16,6), 
	"IMPOR01" NUMBER(16,2), 
	"IMPOR02" NUMBER(16,2), 
	"PAGOMN" NUMBER(16,2), 
	"PAGOME" NUMBER(16,2), 
	"SITUAC" CHAR(1 BYTE), 
	"NUMBCO" VARCHAR2(16 BYTE), 
	"DEPOSITO" NUMBER(16,5), 
	"SWCHKSEPAGA" VARCHAR2(1 BYTE), 
	"SWCHKRETIENE" VARCHAR2(1 BYTE), 
	"CONCEP" VARCHAR2(75 BYTE), 
	"RETCODCLI" VARCHAR2(20 BYTE), 
	"RETSERIE" VARCHAR2(5 BYTE), 
	"RETNUMERO" NUMBER(*,0), 
	"SWCHKAJUSCEN" VARCHAR2(1 BYTE), 
	"REFERE01" VARCHAR2(25 BYTE), 
	"REFERE02" VARCHAR2(25 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_TSI_SUITE" ;
