--------------------------------------------------------
--  DDL for Table PROV100
--------------------------------------------------------

  CREATE TABLE "USR_TSI_SUITE"."PROV100" 
   (	"ID_CIA" NUMBER(*,0), 
	"TIPO" NUMBER(*,0), 
	"DOCU" NUMBER(*,0), 
	"CODCLI" VARCHAR2(20 BYTE), 
	"TIPDOC" CHAR(2 BYTE), 
	"DOCUME" VARCHAR2(40 BYTE), 
	"SERIE" VARCHAR2(20 BYTE), 
	"NUMERO" VARCHAR2(20 BYTE), 
	"PERIODO" NUMBER(*,0), 
	"MES" NUMBER(*,0), 
	"FEMISI" DATE, 
	"FVENCI" DATE, 
	"FCANCE" DATE, 
	"CODBAN" NUMBER(*,0), 
	"NUMBCO" VARCHAR2(15 BYTE), 
	"REFERE01" VARCHAR2(25 CHAR), 
	"REFERE02" VARCHAR2(25 CHAR), 
	"TIPMON" VARCHAR2(5 BYTE), 
	"IMPORTE" NUMBER(16,2), 
	"IMPORTEMN" NUMBER(16,2), 
	"IMPORTEME" NUMBER(16,2), 
	"SALDO" NUMBER(16,2), 
	"SALDOMN" NUMBER(16,2), 
	"SALDOME" NUMBER(16,2), 
	"CONCPAG" NUMBER(*,0), 
	"CODCOB" NUMBER(*,0), 
	"CODVEN" NUMBER(*,0), 
	"COMISI" NUMBER(14,4), 
	"CODSUC" NUMBER(*,0), 
	"CANCELADO" CHAR(1 BYTE), 
	"FCREAC" DATE, 
	"FACTUA" DATE, 
	"USUARI" VARCHAR2(10 BYTE), 
	"SITUAC" CHAR(1 BYTE), 
	"CUENTA" VARCHAR2(16 BYTE), 
	"DH" CHAR(1 BYTE), 
	"TIPCAM" NUMBER(14,6), 
	"OPERAC" NUMBER(*,0), 
	"PROTES" NUMBER(*,0), 
	"XLIBRO" VARCHAR2(3 BYTE), 
	"XPERIODO" NUMBER(*,0), 
	"XMES" NUMBER(*,0), 
	"XSECUENCIA" NUMBER(*,0), 
	"CODUBI" NUMBER(*,0), 
	"XPROTESTO" NUMBER(16,5), 
	"CODCLIR" VARCHAR2(20 BYTE), 
	"FVENCI2" DATE, 
	"SWMIGRA" VARCHAR2(1 CHAR) DEFAULT 'N'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_TSI_SUITE" ;
