--------------------------------------------------------
--  Constraints for Table PROYECTO_TAREA_USUARIO
--------------------------------------------------------

  ALTER TABLE "USR_TSI_SUITE"."PROYECTO_TAREA_USUARIO" MODIFY ("ID_CIA" NOT NULL ENABLE);
  ALTER TABLE "USR_TSI_SUITE"."PROYECTO_TAREA_USUARIO" MODIFY ("NUMINT_PROYEC" NOT NULL ENABLE);
  ALTER TABLE "USR_TSI_SUITE"."PROYECTO_TAREA_USUARIO" MODIFY ("CODUSER" NOT NULL ENABLE);
  ALTER TABLE "USR_TSI_SUITE"."PROYECTO_TAREA_USUARIO" ADD CONSTRAINT "PK_PROYECTO_TAREA_USUARIO" PRIMARY KEY ("ID_CIA", "NUMINT_PROYEC", "CODUSER")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_TSI_SUITE"  ENABLE;
