--------------------------------------------------------
--  DDL for Type REC_SP_PLE_8_1_REGISTRO_COMPRAS
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TYPE "USR_TSI_SUITE"."REC_SP_PLE_8_1_REGISTRO_COMPRAS" AS OBJECT 
( 

  CPERIODO NUMBER,
  CNUMREGOPE VARCHAR(20),
  MCORRASIEN VARCHAR(10),
  CFECCOM VARCHAR(10),
  CFECVENPAG VARCHAR(10),
  CTIPDOCCOM VARCHAR(2),
  CNUMSER VARCHAR(20),
  CEMIDUADSI VARCHAR(4),
  CNUMDCODFV VARCHAR(20),
  OPERACONSOLIDADA NUMBER,
  CTIPDIDPRO VARCHAR(2),
  CNUMDIDPRO VARCHAR(15),
  CNOMRSOPRO VARCHAR(200),
  CBASIMPGRA NUMBER(16, 2), 
  CIGVGRA NUMBER(16, 2),
  CBASIMPGNG NUMBER(16, 2),
  CIGVGRANGV NUMBER(16, 2), 
  CBASIMPSCF NUMBER(16, 2),
  CIGVSCF NUMBER(16, 2), 
  CIMPTOTNGV NUMBER(16, 2),
  CISC NUMBER(16, 2),
  CICBPER NUMBER(16, 2),
  COTRTRICGO NUMBER(16, 2),
  CIMPTOTCOM NUMBER(16, 2),
  CMONEDA VARCHAR(3),
  CTIPCAM NUMBER(6, 3),
  FEMISIORI VARCHAR(10), 
  TDOCUMORI VARCHAR(2),
  NSERIEORI VARCHAR(20),
  MCODADUDEC VARCHAR(1),
  NUMEROORI VARCHAR(20),
  NROCOMNODOM VARCHAR(20),
  CFEMIDEPDET VARCHAR(10),
  CNRODETRAC VARCHAR(15),
  CCOMPGORET VARCHAR(1),
  CCANCELADO NUMBER,
  BIENSER VARCHAR(5),
  ESTADO NUMBER

);

/
