--------------------------------------------------------
--  DDL for Type REC_REGISTROS_COMPRAS_001
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TYPE "USR_TSI_SUITE"."REC_REGISTROS_COMPRAS_001" AS OBJECT (
    libro         VARCHAR2(3),
    periodo       NUMBER,
    mes           NUMBER,
    deslib        VARCHAR2(50),
    asiento       NUMBER,
    situac        NUMBER,
    tipo          NUMBER,
    docume        NUMBER,
    femisi        DATE,
    tdocum        VARCHAR2(2),
    serie         VARCHAR2(20),
    numero        VARCHAR2(20),
    codigo        VARCHAR2(20),
    razon         VARCHAR2(100 CHAR),
    moneda        VARCHAR2(5),
    tcambio01     NUMERIC(14, 6),
    tcambio02     NUMERIC(14, 6),
    concep        VARCHAR2(150 CHAR),
    porigv        NUMERIC(6, 2),
    signo         FLOAT,
    tcrefis       NUMERIC(16, 4),
    tcrefis2      NUMERIC(16, 4),
    tinafecto     NUMERIC(16, 4),
    tinafecto2    NUMERIC(16, 4),
    tncrefis      NUMERIC(16, 4),
    tncrefis2     NUMERIC(16, 4),
    tbaseimp_c1   NUMERIC(16, 4),
    tbaseimp_c2   NUMERIC(16, 4),
    tbaseimp_c3   NUMERIC(16, 4),
    tbaseimp      NUMERIC(16, 4),
    tbaseimp2     NUMERIC(16, 4),
    timpuesto     NUMERIC(16, 4),
    timpuesto_c1  NUMERIC(16, 4),
    timpuesto_c2  NUMERIC(16, 4),
    timpuesto_c3  NUMERIC(16, 4),
    timpuesto2    NUMERIC(16, 4),
    tisc          NUMERIC(16, 4),
    tisc2         NUMERIC(16, 4),
    totrostri     NUMERIC(16, 4),
    totrostri2    NUMERIC(16, 4),
    ticbper       NUMERIC(16, 4),
    ticbper2      NUMERIC(16, 4),
    tgeneral      NUMERIC(16, 4),
    tgeneral2     NUMERIC(16, 4),
    coduser       VARCHAR2(20),
    usuario       VARCHAR2(50),
    factua        TIMESTAMP
);

/
