--------------------------------------------------------
--  DDL for Type REC_SP_PLE_14_REGISTRO_VENTAS
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TYPE "USR_TSI_SUITE"."REC_SP_PLE_14_REGISTRO_VENTAS" AS OBJECT 
( /* TODO enter attribute and method declarations here */ 

PERIODO NUMBER,
MCORRASIEN VARCHAR2(30),
NUMREGOPE VARCHAR2(80),
VFECCOM VARCHAR2(10),
VFECVENPAG VARCHAR2(10),
VTIPDOCCOM VARCHAR2(2),
VNUMSER VARCHAR2(20),
VNUMDOCCOI VARCHAR2(20),
VMONEDA VARCHAR2(5),
IMPTOTOPE NUMBER,
VTIPDIDCLI VARCHAR2(10),
VNUMDIDCLI VARCHAR2(20),
VAPENOMRSO VARCHAR2(100),
VVALFACEXP NUMBER(16,2),
VBASIMPGRA NUMBER(16,2),
VDESIGVIPM NUMBER(16,2),
VDESBASIMPGRA NUMBER(16,2),
VIMPTOTEXO NUMBER(16,2),
VIMPTOTINA NUMBER(16,2),
VISC NUMBER(16,2),
VIGVIPM NUMBER(16,2),
VBASIMIVAP NUMBER(16,2),
BIVAP NUMBER(16,2),
VOTRTRICGO NUMBER(16,2),
VIMPTOTCOM NUMBER(16,2),
VTIPCAM NUMBER(6,3),
TIPDOCRE NUMBER,
SERIERE VARCHAR2(5),
NUMDOCRE NUMBER,
FEMISIRE DATE, 
VFOBEXP NUMBER, 
VICBPER NUMBER(16,2), 
ESTADO NUMBER

);

/
