--------------------------------------------------------
--  DDL for Type REC_SP_ARTICULO_COTIZACIONES
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TYPE "USR_TSI_SUITE"."REC_SP_ARTICULO_COTIZACIONES" AS OBJECT 
( /* TODO enter attribute and method declarations here */ 

TIPDOC NUMBER,
NUMINT NUMBER,
NUMITE NUMBER,
CODMOT NUMBER,
FEMISI DATE,
NUMDOC NUMBER,
SERIES VARCHAR2(40),
CODCLI VARCHAR2(60),
RAZONC VARCHAR2(120),
INCIGV VARCHAR2(1),
TIPINV NUMBER,
CODART VARCHAR2(40),
CANTID NUMBER,
CODALM NUMBER,
PREUNISOL NUMBER,
PREUNIDOL NUMBER,
PRETOTSOL NUMBER,
PRETOTDOL NUMBER,
PORDES1 NUMBER,
PORDES2 NUMBER,
PORDES3 NUMBER,
PORDES4 NUMBER,
DESALM VARCHAR2(60),
ORDCOM VARCHAR2(40),
DESDOC VARCHAR2(40),
DESSIT VARCHAR2(40),
LARGO NUMBER
);

/
