--------------------------------------------------------
--  DDL for Type REC_SP00_SACA_ORDENES_PEDIDOS_DETALLE
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TYPE "USR_TSI_SUITE"."REC_SP00_SACA_ORDENES_PEDIDOS_DETALLE" AS OBJECT 
( /* TODO enter attribute and method declarations here */ 

  NUMINT  NUMBER,
  NUMITE  NUMBER,
  SERIES  VARCHAR(5),
  NUMDOC  NUMBER,
  FEMISI  DATE,
  FENTREG  DATE,
  TIPMON  VARCHAR(5),
  TIPCAM  NUMBER(10, 6),
  CODCLI  VARCHAR(20),
  RUC  VARCHAR(20),
  RAZONC  VARCHAR(80 CHAR),
  OPNUMDOC  NUMBER,
  ORDCOM  VARCHAR(20),
  CODART  VARCHAR(40),
  TIPINV  NUMBER,
  CODALM  NUMBER,
  CANTIDAD  NUMBER(16, 4),
  CODUND  VARCHAR(3),
  PREUNISOL  NUMBER(16, 4),
  PREUNIDOL  NUMBER(16, 4),
  ENTREGA  NUMBER(16, 4),
  SALDO  NUMBER(16, 4),
  CODVEN  NUMBER,
  DESVEN  VARCHAR(40),
  ETIQUETA  VARCHAR(100),
  OBSERV  VARCHAR(100)

);

/
