--------------------------------------------------------
--  DDL for Type REC_SP_RE_ABRE_QRYFORMATOS_GUIAREMISION
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TYPE "USR_TSI_SUITE"."REC_SP_RE_ABRE_QRYFORMATOS_GUIAREMISION" AS OBJECT (
       tipdoc                NUMBER(38),
    nomdoc                VARCHAR2(30),
    numint                NUMBER(38),
    id                    VARCHAR2(1), --CHAR,
    series                VARCHAR2(5),
    numdoc                NUMBER(38),
    femisi                DATE,
    destin                NUMBER(38),
    codcli                VARCHAR2(20),
    razonc                VARCHAR2(80 CHAR),
    direc1                VARCHAR2(100 CHAR),
    ruc                   VARCHAR2(20),
    tipcam                NUMBER(10, 6),
    tipmon                VARCHAR2(5),
    codven                NUMBER(38),
    numite                NUMBER(38),
    positi                NUMBER(38),
    tipinv                NUMBER(38),
    codart                VARCHAR2(40),
    obsdet                VARCHAR2(3000),
    codund                VARCHAR2(3),
    cantid                NUMBER(16, 5),
    cantidbase            NUMBER(16, 5),
    canref                NUMBER(16, 5),
    preuni                NUMBER(16, 5),--
    importe_bruto         NUMBER(16, 2),
    importe               NUMBER(16, 2),
    descdet               NUMBER(16, 2),
    opronumdoc            VARCHAR2(30),
    swacti                NUMBER(38),--b
    piezas                NUMBER(16, 5),
    largo                 NUMBER(9, 3),
    ancho                 NUMBER(9, 3),--b
    altura                NUMBER(9, 3),
    etiqueta              VARCHAR2(100),
    etiqueta2             VARCHAR2(100),
    codunidet             VARCHAR2(3),
    tara                  NUMBER(16, 5),--b
    royos                 NUMBER(16, 5),
    pordes1               NUMBER(16, 5),
    pordes2               NUMBER(16, 5),
    pordes3               NUMBER(16, 5),
    pordes4               NUMBER(16, 5),
   dopnumdoc             NUMBER(38),
    dopcargo              VARCHAR2(8),
    dopnumite             NUMBER(38),
    codalm                NUMBER(38),
    monafedet             NUMBER(16, 2),
    monigvdet             NUMBER(16, 2),
    lote                  VARCHAR2(20),
    fvenci                DATE,
    nrocarrete            VARCHAR2(20),
    descue                NUMBER(16, 2),
    totbru                NUMBER(16, 2),
    monafe                NUMBER(16, 2),
    monina                NUMBER(16, 2),
    monneto               NUMBER(16, 2),
    monigv                NUMBER(16, 2),
    preven                NUMBER(16, 2),
    porigv                NUMBER(16, 2), --b
     codsuc                NUMBER(38),
    incigv                VARCHAR2(1),--CHAR
    numped                VARCHAR2(60),
    codmot                NUMBER(38),
    situac                CHAR(1),   --CHAR
    obscab                VARCHAR2(3000 CHAR),
    fentreg               DATE,
    codarea               NUMBER(38),
    coduso                NUMBER(38),
    totcan                NUMBER(16, 5),
    codenv                NUMBER(38),
    horing                TIMESTAMP(6),
    fecter                DATE,
    horter                TIMESTAMP(6),
    codtec                NUMBER(38),
    opnumdoc              NUMBER(38),
    ordcom                VARCHAR2(20),
    fordcom               DATE,
    guiarefe              VARCHAR2(15),
    desenv01              VARCHAR2(150),
    desenv02              VARCHAR2(60 CHAR),
    marcas                VARCHAR2(50 CHAR),
    presen                VARCHAR2(200 CHAR),--b
    codsec                NUMBER(38),
    facpro                VARCHAR2(20),
    ffacpro               DATE,
    numvale               NUMBER(38),
    fecvale               DATE,
    desnetx               VARCHAR2(50),
    despreven             VARCHAR2(50),
    desfle                VARCHAR2(50),
    flete                 NUMBER(12, 2),
    desseg                VARCHAR2(50),
    seguro                NUMBER(12, 2),
    desgasa               VARCHAR2(50),
    gasadu                NUMBER(16, 2),
    desart                VARCHAR2(100),
    codbar                VARCHAR2(40),
    coddesart             VARCHAR2(200),
    codlin                NUMBER(38),
    faccon                NUMBER(9, 5),
    consto                NUMBER(38),
    peslar                NUMBER(9, 5),
    pesdet                NUMBER(16, 5),
    pescable              NUMBER(16, 5),
    taraadic              VARCHAR2(6),--b
    despagven             VARCHAR2(50 CHAR),
    enctacte              VARCHAR2(25),
    diaven                NUMBER(38),
    dessuc                VARCHAR2(20),
    dissuc                VARCHAR2(50),
    dircli1               VARCHAR2(100 CHAR),
    dircli2               VARCHAR2(100 CHAR),
    emailcli              VARCHAR2(50 CHAR),
    faxcli                VARCHAR2(50 CHAR),
    tlfcli                VARCHAR2(50 CHAR),
    dident                VARCHAR2(20),
    tident                VARCHAR2(2),
    desven                VARCHAR2(50),
    comiven               NUMBER(9, 3),--b
    codvendedor           NUMBER(38),
    simbolo               CHAR(3),
    desmon                VARCHAR2(50),
    codtra                NUMBER(38),
    swdattra              VARCHAR2(1),
    razonctra             VARCHAR2(100),
    destra                VARCHAR2(50),
    dirtra                VARCHAR2(100),
    ructra                VARCHAR2(15),
    licenciatra           VARCHAR2(15),
    placatra              VARCHAR2(50),
    certiftra             VARCHAR2(15),
    fonotra               VARCHAR2(80),
    desveh                VARCHAR2(50),
    tipoveh               VARCHAR2(20),--b
  marcaveh              VARCHAR2(50),
    placaveh              VARCHAR2(20),
    certifveh             VARCHAR2(30),
    observveh             VARCHAR2(1000),
    razonctra2            VARCHAR2(100),
    destra2               VARCHAR2(50),--m
    dirtra2               VARCHAR2(100),
    ructra2               VARCHAR2(20),
    punpartra2            VARCHAR2(50 CHAR),
    licenctra2            VARCHAR2(15),
    placaveh2             VARCHAR2(20),
    desmot                VARCHAR2(50),
    stockk001             NUMBER(11, 4),
    saldok001             NUMBER(11, 4),
    desenval              VARCHAR2(50 CHAR),--m
    direnv1               VARCHAR2(150),
    direnv2               VARCHAR2(150),
    nrodni                VARCHAR2(20),
    colorart              VARCHAR2(60),
    desglosa              VARCHAR2(1000),
    skuventas             VARCHAR2(50),
    glosxdes              VARCHAR2(20),
    ocseries              VARCHAR2(5),
    ocnumdoc              NUMBER(38),
    ocdesdoc              VARCHAR2(50),
    ocabrdoc              VARCHAR2(4),
    codcalid              VARCHAR2(20),
    dcalidad              VARCHAR2(100),
    acalidad              VARCHAR2(10),
    codcolor              VARCHAR2(20),
    dcolor                VARCHAR2(40),
    desfam                VARCHAR2(70),
    deslin                VARCHAR2(70),
    desmod                VARCHAR2(70),
    codubica              VARCHAR2(20),
    valundaltven          NUMBER(12, 6),
    ubigeo                VARCHAR2(200),
    ubigeo_b              VARCHAR2(200),
    ubigeo_destino_b      VARCHAR2(200),
    fecha_dcorcom         DATE,
    numero_dcorcom        VARCHAR2(25),
    contacto_dcorcom      VARCHAR2(50),
    pesnet                NUMBER(16, 2),
    ubigeodes_partida_a   VARCHAR2(200),
    ubigeodes_partida_b   VARCHAR2(200),
    ubigeo_partida        VARCHAR2(200),
    ubigeo_llegada        VARCHAR2(200),
    direccpar             VARCHAR2(100 CHAR),
    ubigeopar             VARCHAR2(10),
    tidentra              VARCHAR2(15),
    tidentconductor       VARCHAR2(2),
    destidentconductor    VARCHAR2(50),
    didentconductor       VARCHAR2(20),
    placavehiculo         VARCHAR2(50),
    glosagfecab           VARCHAR2(3000 CHAR),
    glosagfepie           VARCHAR2(3000 CHAR),
    dessit                VARCHAR2(50),
    aliassit              VARCHAR2(50),
    proyec                VARCHAR2(16),
    abrunidad             VARCHAR2(10) 
);

/
