--------------------------------------------------------
--  DDL for Type REC_SP_PLE_8_2_REGISTRO_COMPRAS_NO_DOMICILIADO
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TYPE "USR_TSI_SUITE"."REC_SP_PLE_8_2_REGISTRO_COMPRAS_NO_DOMICILIADO" AS OBJECT 
( /* TODO enter attribute and method declarations here */ 

  CPERIODO NUMBER,
  CNUMREGOPE VARCHAR2(20),
  MCORRASIEN VARCHAR2(10),
  CFECCOM VARCHAR2(10),
  CFECVENPAG VARCHAR2(10),
  CTIPDOCCOM VARCHAR2(2),
  CNUMSER VARCHAR2(20),
  CEMIDUADSI VARCHAR2(4),
  CNUMDCODFV VARCHAR2(20),
  OPERACONSOLIDADA INTEGER,
  CTIPDIDPRO VARCHAR2(2),
  CNUMDIDPRO VARCHAR2(15),
  CNOMRSOPRO VARCHAR2(200),
  CBASIMPGRA NUMBER(16, 2),
  CIGVGRA NUMBER(16, 2),
  CBASIMPGNG NUMBER(16, 2),
  CIGVGRANGV NUMBER(16, 2),
  CBASIMPSCF NUMBER(16, 2),
  CIGVSCF NUMBER(16, 2),
  CIMPTOTNGV NUMBER(16, 2),
  CISC NUMBER(16, 2),
  COTRTRICGO NUMBER(16, 2),
  CIMPTOTCOM NUMBER(16, 2),
  CMONEDA VARCHAR2(3),
  CTIPCAM NUMBER(6, 3),
  FEMISIORI VARCHAR2(10), 
  TDOCUMORI VARCHAR2(2),
  NSERIEORI VARCHAR2(20),
  MCODADUDEC VARCHAR2(1),
  NUMEROORI VARCHAR2(20),
  NROCOMNODOM VARCHAR2(20),
  CFEMIDEPDET VARCHAR2(10),
  CNRODETRAC VARCHAR2(15),
  CCOMPGORET VARCHAR2(1),
  CCANCELADO NUMBER,
  ESTADO NUMBER,
  CODIGOPAIS VARCHAR2(20)

);

/
