--------------------------------------------------------
--  DDL for Type REC_SP_ARTICULO_VENTAS
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TYPE "USR_TSI_SUITE"."REC_SP_ARTICULO_VENTAS" AS OBJECT 
( /* TODO enter attribute and method declarations here */ 

TIPDOC NUMBER,
NUMINT NUMBER,
NUMITE NUMBER,
CODMOT NUMBER,
FEMISI DATE,
NUMDOC NUMBER,
SERIES VARCHAR2(120),
CODCLI VARCHAR2(120),
RAZONC VARCHAR2(120),
SIGNO VARCHAR2(120),
INCIGV VARCHAR2(120),
TIPINV NUMBER,
CODART VARCHAR2(120),
DESART VARCHAR2(100),
CANTID NUMBER,
LARGO NUMBER,
CODALM NUMBER,
PORDES1 NUMBER,
PORDES2 NUMBER,
PORDES3 NUMBER,
PORDES4 NUMBER,
PREUNISOL NUMBER,
PREUNIDOL NUMBER,
PRETOTSOL NUMBER,
PRETOTDOL NUMBER,
DESALM VARCHAR2(120),
ORDCOM VARCHAR2(120),
DESDOC VARCHAR2(120),
DESSIT VARCHAR2(120)  
);

/
