--------------------------------------------------------
--  DDL for Type REC_SP000_DOCUMENTOS_PENDIENTES_CTAXCOBRAR_2
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TYPE "USR_TSI_SUITE"."REC_SP000_DOCUMENTOS_PENDIENTES_CTAXCOBRAR_2" AS OBJECT (
    codcli      VARCHAR2(20),
    razonc      VARCHAR2(100 CHAR),
    numint      INTEGER,
    tipdoc      SMALLINT,
    serie       VARCHAR2(50),
    numero      VARCHAR2(20),
    desdoc      VARCHAR2(30),
    abrevi      VARCHAR2(6),
    docume      VARCHAR2(40),
    codven      INTEGER,
    desven      VARCHAR2(50),
    codven_car  NUMBER,
    desven_car  VARCHAR2(50),
    codsuc      NUMBER,
    dessuc      VARCHAR2(50),
    codubi      NUMBER,
    desubi      VARCHAR2(50),
    abrubi      VARCHAR2(10),
    femisi      DATE,
    fvenci      DATE,
    fcance      DATE,
    dias        NUMBER,
    tipmon      VARCHAR2(3),
    moneda      VARCHAR2(3),
    tipcam      NUMBER,
    tpercepcion NUMERIC(16, 2),
    importe     NUMBER,
    saldopercep NUMERIC(16, 2),
    saldo       NUMBER,
    saldosol    NUMBER,
    saldodol    NUMBER,
    saldodolar  NUMBER,
    vencidos    NUMBER,
    dh          VARCHAR2(1),
    fed         VARCHAR2(15),
    refere01    VARCHAR2(25),
    refere02    VARCHAR2(25),
    codban      SMALLINT,
    desban      VARCHAR2(70),
    numbco      VARCHAR2(50),
    signo       INTEGER,
    protes      SMALLINT,
    desprotes   VARCHAR2(10),
    limcre1     NUMERIC(9, 2),
    limcre2     NUMERIC(9, 2),
    chedev      INTEGER,
    letpro      INTEGER,
    renova      INTEGER,
    refina      INTEGER,
    fecing      DATE,
    codpag      INTEGER,
    operac      INTEGER,
    desoperac   VARCHAR2(20),
    concpag     SMALLINT,
    descpag     VARCHAR2(50 CHAR),
    telefono    VARCHAR2(50 CHAR),
    direc1      VARCHAR2(100 CHAR),
    renovada    VARCHAR2(10),
    estadolet   VARCHAR2(20),
    codmot      SMALLINT,
    desmot      VARCHAR2(50)
);

/
