--------------------------------------------------------
--  DDL for Table REGISTRO
--------------------------------------------------------

  CREATE TABLE "USR_TSI_SUITE"."REGISTRO" 
   (	"ID_CIA" NUMBER(*,0), 
	"TIPDOC" NUMBER(*,0), 
	"SERIE" VARCHAR2(5 BYTE), 
	"NUMDOC" NUMBER(*,0), 
	"NUMINT" NUMBER(*,0), 
	"CODSUC" NUMBER(*,0), 
	"FEMISI" DATE, 
	"ANOPRO" NUMBER(*,0), 
	"MESPRO" NUMBER(*,0), 
	"SITUAC" CHAR(1 BYTE), 
	"FCREAC" TIMESTAMP (6), 
	"FACTUA" TIMESTAMP (6), 
	"USUARI" VARCHAR2(10 BYTE), 
	"CODLIB" VARCHAR2(3 BYTE), 
	"SECUENCIA" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_TSI_SUITE" ;
