--------------------------------------------------------
--  DDL for Table RETENHEA
--------------------------------------------------------

  CREATE TABLE "USR_TSI_SUITE"."RETENHEA" 
   (	"ID_CIA" NUMBER(*,0), 
	"NUMINT" NUMBER(*,0), 
	"SERIE" VARCHAR2(5 BYTE), 
	"NUMERO" NUMBER(*,0), 
	"PERIODO" NUMBER(*,0), 
	"MES" NUMBER(*,0), 
	"LIBRO" VARCHAR2(3 BYTE), 
	"ASIENTO" NUMBER(*,0), 
	"FEMISI" DATE, 
	"MONEDA" VARCHAR2(3 BYTE), 
	"TCAMB01" NUMBER(14,6), 
	"TCAMB02" NUMBER(14,6), 
	"CODIGO" VARCHAR2(20 BYTE), 
	"RAZONC" VARCHAR2(120 BYTE), 
	"CUENTARET" VARCHAR2(16 BYTE), 
	"DHRET" VARCHAR2(1 BYTE), 
	"CUENTAIGV" VARCHAR2(16 BYTE), 
	"SITUAC" NUMBER(*,0), 
	"FCREAC" TIMESTAMP (6), 
	"FACTUA" TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_TSI_SUITE" ;
