--------------------------------------------------------
--  DDL for Function SP001_AJUSTA_ALMACENES_FORMATO
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE FUNCTION "USR_TSI_SUITE"."SP001_AJUSTA_ALMACENES_FORMATO" (
 WALMACENES IN VARCHAR2,
 WLENAJUS IN NUMBER
 )
 RETURN VARCHAR2
 IS 
  ALMACENES VARCHAR2(200):='';
  SNUMERO VARCHAR2(10):='';
  LARGO NUMBER:=0;
  POS INTEGER:=1;
  NCARACTER NUMBER:=0;
 BEGIN

  LARGO     :=LENGTH(WALMACENES);

  WHILE (POS<=LARGO) LOOP
   IF (SUBSTR(WALMACENES,POS,1) IN ('0','1','2','3','4','5','6','7','8','9')) Then
        SNUMERO:=SNUMERO||SubStr(WALMACENES,POS,1);
        NCARACTER:=NCARACTER+1;
    ELSIF (NCARACTER>0) THEN
      ALMACENES := ALMACENES||' '||SP000_AJUSTA_STRING(SNUMERO,WLENAJUS,'0','R')||' ';  
      SNUMERO:=''; NCARACTER:=0;
   END IF ;
   POS:=POS+1;
  END LOOP;

  IF (NCARACTER>0) THEN
   ALMACENES := ALMACENES||' '||SP000_AJUSTA_STRING(SNUMERO,WLENAJUS,'0','R')||' ';    
  END IF ;
  RETURN ALMACENES;
 END SP001_AJUSTA_ALMACENES_FORMATO;

/
