--------------------------------------------------------
--  DDL for Function SP_ARTICULO_COTIZACIONES
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE FUNCTION "USR_TSI_SUITE"."SP_ARTICULO_COTIZACIONES" 
(
  PIN_ID_CIA IN NUMBER,
   PIN_TIPINV IN NUMBER,
  PIN_CODART IN VARCHAR2,
  PIN_CODSUC IN NUMBER,
  PIN_CODCLI IN VARCHAR2,
  PIN_SITUAC IN VARCHAR2,
  PIN_LIMIT IN NUMBER,
  PIN_OFFSET IN NUMBER
) RETURN TBL_SP_ARTICULO_COTIZACIONES
    PIPELINED  AS 

 REC REC_SP_ARTICULO_COTIZACIONES := REC_SP_ARTICULO_COTIZACIONES(NULL,
NULL,
NULL,NULL, NULL, NULL, NULL, NULL, NULL, NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL);


BEGIN



       FOR i IN (
         SELECT   
            C.TIPDOC,C.NUMINT,D.NUMITE,C.CODMOT,C.FEMISI, 
            C.NUMDOC,C.SERIES,C.CODCLI,C.RAZONC,C.INCIGV, 
       D.TIPINV,D.CODART,D.CANTID,D.CODALM, 
       CASE WHEN (C.TIPMON='PEN') AND 
       (D.CANTID>0) THEN D.PREUNI ELSE 0 END AS PREUNISOL, 
       CASE WHEN (C.TIPMON='USD')AND 
       (D.CANTID>0) THEN D.PREUNI ELSE 0 END AS PREUNIDOL, 
       CASE WHEN (C.TIPMON='PEN') THEN 
       D.IMPORTE          ELSE 0 END AS PRETOTSOL, 
       CASE WHEN (C.TIPMON='USD') THEN 
       D.PREUNI          ELSE 0 END AS PRETOTDOL, 
       D.PORDES1,
       D.PORDES2,
       D.PORDES3,
       D.PORDES4,  
       AL.DESCRI AS DESALM,
       C.ORDCOM,
       DC.DESCRI AS DESDOC, 
       S.DESSIT,
       D.LARGO  
 FROM DOCUMENTOS_DET D 
  LEFT OUTER JOIN DOCUMENTOS_CAB   C ON (C.ID_CIA = D.ID_CIA AND C.NUMINT = D.NUMINT) 
  LEFT OUTER JOIN DOCUMENTOS DC ON (DC.ID_CIA = D.ID_CIA AND DC.CODIGO = D.TIPDOC) AND (DC.SERIES=C.SERIES) 
  LEFT OUTER JOIN SITUACION   S ON (S.ID_CIA = D.ID_CIA AND S.TIPDOC = D.TIPDOC  AND S.SITUAC=D.SITUAC) 
  LEFT OUTER JOIN ALMACEN         AL ON AL.ID_CIA = D.ID_CIA AND (AL.TIPINV = D.TIPINV  AND  AL.CODALM=D.CODALM) 
  WHERE (D.ID_CIA = PIN_ID_CIA ) 
  AND (D.TIPINV = PIN_TIPINV ) 
  AND (D.CODART = PIN_CODART)
  AND (C.CodSuc = PIN_CODSUC)
  AND (C.TIPDOC = 100)
  AND ((PIN_SITUAC is null) or (C.SITUAC IN (SELECT *  FROM TABLE(convert_in(PIN_SITUAC)))))  
  AND ((PIN_CODCLI is null) or (C.CodCli = PIN_CODCLI))
  AND (C.CODMOT <> 0)
  ORDER BY C.FEMISI DESC
  OFFSET PIN_OFFSET ROWS FETCH NEXT PIN_LIMIT ROWS ONLY
       ) LOOP

           REC.TIPDOC := I.TIPDOC;
REC.NUMINT := I.NUMINT;
REC.NUMITE := I.NUMITE;
REC.CODMOT := I.CODMOT;
REC.FEMISI := I.FEMISI;
REC.NUMDOC := I.NUMDOC;
REC.SERIES := I.SERIES;
REC.CODCLI := I.CODCLI;
REC.RAZONC := I.RAZONC;
REC.INCIGV := I.INCIGV;
REC.TIPINV := I.TIPINV;
REC.CODART := I.CODART;
REC.CANTID := I.CANTID;
REC.CODALM := I.CODALM;
REC.PREUNISOL := I.PREUNISOL;
REC.PREUNIDOL := I.PREUNIDOL;
REC.PRETOTSOL := I.PRETOTSOL;
REC.PRETOTDOL := I.PRETOTDOL;
REC.PORDES1 := I.PORDES1;
REC.PORDES2 := I.PORDES2;
REC.PORDES3 := I.PORDES3;
REC.PORDES4 := I.PORDES4;
REC.DESALM := I.DESALM;
REC.ORDCOM := I.ORDCOM;
REC.DESDOC := I.DESDOC;
REC.DESSIT := I.DESSIT;
REC.LARGO := I.LARGO;


             PIPE ROW(REC);
       END LOOP; 


  --RETURN NULL;
END SP_ARTICULO_COTIZACIONES;

/
