--------------------------------------------------------
--  DDL for Function SP_SELECT_MOV_ARTICULO_GUIA_INGRESO
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE FUNCTION "USR_TSI_SUITE"."SP_SELECT_MOV_ARTICULO_GUIA_INGRESO" 
(
  PIN_ID_CIA IN NUMBER, 
  PIN_CODPROV IN VARCHAR2, 
  PIN_FDESDE IN DATE, 
  PIN_FHASTA IN DATE,
  PIN_CODART VARCHAR2,
  PIN_NUMINT NUMBER,
  PIN_MONEDA VARCHAR2
) RETURN TBL_SP_SELECT_MOV_ARTICULO_GUIA_INGRESO PIPELINED AS 

REC REC_SP_SELECT_MOV_ARTICULO_GUIA_INGRESO := REC_SP_SELECT_MOV_ARTICULO_GUIA_INGRESO(
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL
);

V_MONEDA VARCHAR2(3);

BEGIN

    IF PIN_MONEDA IS NULL THEN
        V_MONEDA := 'PEN';
        ELSE
        V_MONEDA := PIN_MONEDA;
    END IF;


    FOR i IN (




    SELECT 
       C.NUMINT, 
       C.SERIES, 
       C.NUMDOC, 
       C.GUIPRO, 
       C.FGUIPRO, 
       C.FACPRO, 
       C.FFACPRO, 
       C.NUMPED, 
       C.CODMOT, 
       C.FEMISI, 
       D.TIPINV, 
       D.CODART, 
       A.DESCRI AS DESART, 
       D.CODADD01 AS CODCALID, 
       CL1.DESCRI AS DESCALID, 
       D.CODADD02 AS CODCOLOR, 
       CL2.DESCRI AS DESCOLOR, 
       D.ANCHO, 
       COUNT(D.ETIQUETA) AS CANTROLLOS, 
       SUM(D.CANTID) AS CANTID, 
       A.CODUNI, 
       TM.SIMBOLO, 

       SUM(K.COSTOT01) AS COSTOT_IN, 
       (SUM(K.COSTOT01)) * (((CASE WHEN (C.PORIGV=0) THEN 18 ELSE C.PORIGV END )/100)+1) AS COSTOT_CON, 
       (SUM(K.COSTOT01)/SUM(K.CANTID)) AS COSTOSIN, 
       (SUM(K.COSTOT01)/SUM(K.CANTID)) * (((CASE WHEN (C.PORIGV=0) THEN 18 ELSE C.PORIGV END )/100)+1) AS COSTOCON ,

       SUM(K.COSTOT02) AS COSTOT_IN_02, 
       (SUM(K.COSTOT02)) * (((CASE WHEN (C.PORIGV=0) THEN 18 ELSE C.PORIGV END )/100)+1) AS COSTOT_CON_02, 
       (SUM(K.COSTOT02)/SUM(K.CANTID)) AS COSTOSIN_02, 
       (SUM(K.COSTOT02)/SUM(K.CANTID)) * (((CASE WHEN (C.PORIGV=0) THEN 18 ELSE C.PORIGV END )/100)+1) AS COSTOCON_02


 FROM DOCUMENTOS_CAB C 
 LEFT OUTER JOIN DOCUMENTOS_DET D ON D.ID_CIA = C.ID_CIA AND D.NUMINT=C.NUMINT 
 LEFT OUTER JOIN KARDEX K ON K.NUMINT=D.NUMINT AND K.ID_CIA = D.ID_CIA AND K.NUMITE=D.NUMITE 
 LEFT OUTER JOIN ARTICULOS               A    ON A.ID_CIA = D.ID_CIA AND (A.CODART = D.CODART) AND (A.TIPINV=D.TIPINV) 
 LEFT OUTER JOIN CLIENTE_ARTICULOS_CLASE CL1  ON CL1.ID_CIA = A.ID_CIA AND (CL1.TIPCLI = 'B')  AND (CL1.CODCLI=A.CODPRV) AND 
                                                 (CL1.CLASE=1) AND (CL1.CODIGO=D.CODADD01) 
 LEFT OUTER JOIN CLIENTE_ARTICULOS_CLASE CL2  ON CL2.ID_CIA = A.ID_CIA AND (CL2.TIPCLI = 'B') AND (CL2.CODCLI=A.CODPRV) AND 
                                                 (CL2.CLASE=2) AND (CL2.CODIGO=D.CODADD02) 
 LEFT OUTER JOIN TMONEDA TM ON TM.ID_CIA = C.ID_CIA AND TM.CODMON = V_MONEDA 
 WHERE C.id_cia = pin_id_cia 
 AND ((pin_codprov is null) or (C.CODCLI = pin_codprov))  
 AND C.SITUAC = 'F' 
 AND C.TIPDOC = 103 
 AND C.CODMOT IN (1,28) 
 AND (((PIN_NUMINT IS NOT NULL)AND(PIN_NUMINT>0)) OR (C.FEMISI BETWEEN pin_fdesde AND  pin_fhasta))
 AND ((PIN_NUMINT IS NULL) OR C.NUMINT = PIN_NUMINT)
 AND ((pin_codart is null) or (D.CODART = pin_codart))


 GROUP BY 
       C.NUMINT,
       C.SERIES,
       C.NUMDOC,
       C.GUIPRO,
       C.FGUIPRO,
       C.FACPRO,
       C.FFACPRO,
       C.NUMPED,
       C.CODMOT,
       C.FEMISI,
       D.TIPINV,
       D.CODART,
       A.DESCRI,
       D.CODADD01,
       CL1.DESCRI,
       D.CODADD02,
       CL2.DESCRI,
       D.ANCHO,
       A.CODUNI,
       TM.SIMBOLO,
       C.PORIGV
 ORDER BY D.TIPINV,D.CODART,C.SERIES,C.NUMDOC,C.FACPRO,C.GUIPRO,D.CODADD02,D.CODADD01

    ) LOOP


    REC.NUMINT := i.NUMINT; 
	REC.SERIES := i.SERIES; 
	REC.NUMDOC := i.NUMDOC; 
	REC.GUIPRO := i.GUIPRO; 
	REC.FGUIPRO := i.FGUIPRO; 
	REC.FACPRO := i.FACPRO; 
	REC.FFACPRO := i.FFACPRO; 
	REC.NUMPED := i.NUMPED; 
	REC.CODMOT := i.CODMOT; 
	REC.NUMDOC := i.NUMDOC; 
	REC.FEMISI := i.FEMISI; 
    REC.TIPINV := i.TIPINV; 
    REC.CODART := i.CODART; 
    REC.DESART := i.DESART; 
    REC.CODCALID := i.CODCALID; 
    REC.DESCALID := i.DESCALID; 
    REC.CODCOLOR := i.CODCOLOR; 
    REC.DESCOLOR := i.DESCOLOR; 
    REC.ANCHO := i.ANCHO; 
    REC.CANTROLLOS := i.CANTROLLOS; 
    REC.CANTID := i.CANTID; 
    REC.CODUNI := i.CODUNI; 
    REC.SIMBOLO := i.SIMBOLO; 

    IF V_MONEDA = 'PEN' THEN
      REC.COSTOT_IN := i.COSTOT_IN; 
    REC.COSTOT_CON := i.COSTOT_CON; 
    REC.COSTOSIN := i.COSTOSIN; 
    REC.COSTOCON := i.COSTOCON;
    ELSE
      REC.COSTOT_IN := i.COSTOT_IN_02; 
    REC.COSTOT_CON := i.COSTOT_CON_02; 
    REC.COSTOSIN := i.COSTOSIN_02; 
    REC.COSTOCON := i.COSTOCON_02;
    END IF;


          PIPE ROW(REC);
        END LOOP;

END SP_SELECT_MOV_ARTICULO_GUIA_INGRESO;

/
