--------------------------------------------------------
--  DDL for Table SUCURSAL_CLASES
--------------------------------------------------------

  CREATE TABLE "USR_TSI_SUITE"."SUCURSAL_CLASES" 
   (	"ID_CIA" NUMBER(*,0), 
	"CODSUC" NUMBER(*,0), 
	"CLASE" NUMBER(*,0), 
	"CODIGO" VARCHAR2(12 BYTE), 
	"VREAL" NUMBER(9,2), 
	"VSTRG" VARCHAR2(150 BYTE), 
	"VDATE" DATE, 
	"VTIME" TIMESTAMP (6), 
	"VENTERO" NUMBER(*,0), 
	"CUENTA" VARCHAR2(16 BYTE), 
	"SITUAC" CHAR(1 BYTE), 
	"FCREAC" TIMESTAMP (6), 
	"USUARI" VARCHAR2(10 BYTE), 
	"FACTUA" TIMESTAMP (6), 
	"SWACTI" CHAR(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_TSI_SUITE" ;
