--------------------------------------------------------
--  DDL for Table TABLA_TEMPORAL_CLIENTE
--------------------------------------------------------

  CREATE TABLE "USR_TSI_SUITE"."TABLA_TEMPORAL_CLIENTE" 
   (	"RUC" VARCHAR2(20 BYTE), 
	"RAZONC" VARCHAR2(200 BYTE), 
	"FECHA" VARCHAR2(20 BYTE), 
	"DETALLE" VARCHAR2(30 BYTE), 
	"NADA" VARCHAR2(10 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_TSI_SUITE" ;
