--------------------------------------------------------
--  DDL for Table TAREA
--------------------------------------------------------

  CREATE TABLE "USR_TSI_SUITE"."TAREA" 
   (	"ID_CIA" NUMBER(*,0), 
	"NUMINT" NUMBER(*,0), 
	"TIPDOC" NUMBER(*,0), 
	"CODTTA" VARCHAR2(5 BYTE), 
	"NUMTTA" VARCHAR2(20 BYTE), 
	"CODCLI" VARCHAR2(20 BYTE), 
	"CODCON" NUMBER(*,0), 
	"CODVEN" NUMBER(*,0), 
	"CODPRI" NUMBER(*,0), 
	"CODACC" NUMBER(*,0), 
	"FVISITA" DATE, 
	"HINICIO" TIMESTAMP (6), 
	"HFINAL" TIMESTAMP (6), 
	"TIEMPO" NUMBER(*,0), 
	"OBSERVACION" VARCHAR2(1000 CHAR), 
	"FCREAC" TIMESTAMP (6), 
	"FACTUA" TIMESTAMP (6), 
	"USUARI" VARCHAR2(10 BYTE), 
	"SITUAC" CHAR(1 BYTE), 
	"RAZONC" VARCHAR2(80 BYTE), 
	"EMAIL" VARCHAR2(100 BYTE), 
	"DIRECCION" VARCHAR2(100 BYTE), 
	"NOMCONT" VARCHAR2(100 BYTE), 
	"TELEFONO" VARCHAR2(50 BYTE), 
	"CODUSERORI" VARCHAR2(10 BYTE), 
	"IDEVENTOGOOGLE" VARCHAR2(300 BYTE), 
	"FFINAL" DATE, 
	"TIPCLI" CHAR(1 BYTE), 
	"TITULO" VARCHAR2(150 BYTE), 
	"NUMINT_TPADRE" NUMBER, 
	"NUMINT_PROYEC" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_TSI_SUITE" ;
