--------------------------------------------------------
--  DDL for Table TBANCOS
--------------------------------------------------------

  CREATE TABLE "USR_TSI_SUITE"."TBANCOS" 
   (	"ID_CIA" NUMBER(*,0), 
	"CODBAN" VARCHAR2(3 BYTE), 
	"DESCRI" VARCHAR2(65 BYTE), 
	"SECTOR" VARCHAR2(65 BYTE), 
	"MONEDA" CHAR(3 BYTE), 
	"DIRECC" VARCHAR2(100 BYTE), 
	"CLIBRO" CHAR(3 BYTE), 
	"CUENTA" VARCHAR2(25 BYTE), 
	"CODSUNAT" VARCHAR2(10 BYTE), 
	"SITUAC" NUMBER(*,0), 
	"USUARI" VARCHAR2(10 BYTE), 
	"FCREAC" TIMESTAMP (6), 
	"FACTUA" TIMESTAMP (6), 
	"CUENTACON" VARCHAR2(16 BYTE), 
	"CUENTARET" VARCHAR2(16 BYTE), 
	"SECUENCIA" NUMBER(*,0), 
	"CUENTACTA" VARCHAR2(16 BYTE), 
	"CUENTACAR" VARCHAR2(16 BYTE), 
	"CUENTACPROT" VARCHAR2(16 BYTE), 
	"CUENTACOB" VARCHAR2(16 BYTE), 
	"CUENTADES" VARCHAR2(16 BYTE), 
	"CUENTAGAR" VARCHAR2(16 BYTE), 
	"CUENTAORD01" VARCHAR2(16 BYTE), 
	"CUENTAORD02" VARCHAR2(16 BYTE), 
	"CUENTAENVIOS" VARCHAR2(16 BYTE), 
	"FILTRO" VARCHAR2(40 BYTE), 
	"SWACTI" VARCHAR2(1 BYTE), 
	"ABREVI" VARCHAR2(15 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_TSI_SUITE" ;
