--------------------------------------------------------
--  DDL for Table TBANCOS_CHEQUES
--------------------------------------------------------

  CREATE TABLE "USR_TSI_SUITE"."TBANCOS_CHEQUES" 
   (	"ID_CIA" NUMBER(*,0), 
	"CODBAN" VARCHAR2(3 BYTE), 
	"SERIE" VARCHAR2(10 BYTE), 
	"CORREL" NUMBER(*,0), 
	"DESCRI" VARCHAR2(60 BYTE), 
	"PERIODO" NUMBER(*,0), 
	"MES" NUMBER(*,0), 
	"LIBRO" VARCHAR2(3 BYTE), 
	"ASIENTO" NUMBER(*,0), 
	"SITUAC" CHAR(1 BYTE), 
	"FCREAC" TIMESTAMP (6), 
	"FACTUA" TIMESTAMP (6), 
	"UCREAC" VARCHAR2(10 BYTE), 
	"UACTUA" VARCHAR2(10 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_TSI_SUITE" ;
