--------------------------------------------------------
--  DDL for Table TCAMBIO
--------------------------------------------------------

  CREATE TABLE "USR_TSI_SUITE"."TCAMBIO" 
   (	"ID_CIA" NUMBER(*,0), 
	"HMONEDA" CHAR(3 BYTE), 
	"FECHA" DATE, 
	"MONEDA" CHAR(3 BYTE), 
	"COMPRA" NUMBER(10,6), 
	"VENTA" NUMBER(10,6), 
	"FVENTA" NUMBER(10,6), 
	"FCOMPRA" NUMBER(10,6), 
	"USUARI" VARCHAR2(10 BYTE), 
	"FCREAC" TIMESTAMP (6), 
	"FACTUA" TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_TSI_SUITE" ;
