--------------------------------------------------------
--  DDL for Table TDOCUME
--------------------------------------------------------

  CREATE TABLE "USR_TSI_SUITE"."TDOCUME" 
   (	"ID_CIA" NUMBER(*,0), 
	"CODIGO" CHAR(2 BYTE), 
	"DESCRI" VARCHAR2(50 CHAR), 
	"ABREVI" VARCHAR2(6 BYTE), 
	"DH" CHAR(1 BYTE), 
	"FACTOR" NUMBER(*,0), 
	"CDOCUM" NUMBER(*,0), 
	"CLIBRO" VARCHAR2(3 BYTE), 
	"RINFADI" CHAR(1 BYTE), 
	"SIGNO" FLOAT(126), 
	"SITUAC" CHAR(1 BYTE), 
	"USUARI" VARCHAR2(10 BYTE), 
	"FCREAC" TIMESTAMP (6), 
	"FACTUA" TIMESTAMP (6), 
	"SALECTAS" VARCHAR2(50 BYTE), 
	"CTAGASCOLREGCOM" NUMBER(*,0), 
	"VALOR" NUMBER(*,0), 
	"SWCHKCOMPR010" VARCHAR2(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_TSI_SUITE" ;
