--------------------------------------------------------
--  DDL for Table TDOCUME_CLASES
--------------------------------------------------------

  CREATE TABLE "USR_TSI_SUITE"."TDOCUME_CLASES" 
   (	"ID_CIA" NUMBER(*,0), 
	"TIPDOC" CHAR(2 BYTE), 
	"CLASE" NUMBER(*,0), 
	"MONEDA" VARCHAR2(5 BYTE), 
	"CODIGO" VARCHAR2(20 BYTE), 
	"VREAL" NUMBER(9,2), 
	"VSTRG" VARCHAR2(30 BYTE), 
	"VCHAR" CHAR(1 BYTE), 
	"VDATE" DATE, 
	"VTIME" TIMESTAMP (6), 
	"VENTERO" NUMBER(*,0), 
	"CODUSERCREA" VARCHAR2(10 BYTE), 
	"CODUSERACTU" VARCHAR2(10 BYTE), 
	"FCREAC" TIMESTAMP (6), 
	"FACTUA" TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_TSI_SUITE" ;
