--------------------------------------------------------
--  DDL for Table TDOCUME_CAJA
--------------------------------------------------------

  CREATE TABLE "USR_TSI_SUITE"."TDOCUME_CAJA" 
   (	"ID_CIA" NUMBER(*,0), 
	"TIPDOC" CHAR(2 BYTE), 
	"CODSUC" NUMBER(*,0), 
	"MONEDA" VARCHAR2(3 BYTE), 
	"CUENTA" VARCHAR2(16 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_TSI_SUITE" ;
