--------------------------------------------------------
--  DDL for Table TEMP_ESTUDIO_MERMAS
--------------------------------------------------------

  CREATE TABLE "USR_TSI_SUITE"."TEMP_ESTUDIO_MERMAS" 
   (	"ID_CIA" NUMBER(*,0), 
	"OPNUMDOC" VARCHAR2(30 BYTE), 
	"TIPINV" NUMBER(*,0), 
	"CODART" VARCHAR2(40 BYTE), 
	"PERIODO" NUMBER(*,0), 
	"DESART" VARCHAR2(100 BYTE), 
	"CODUNI" VARCHAR2(10 BYTE), 
	"FEMISI" DATE, 
	"CANTIDAD" NUMBER(16,4), 
	"COSTOTSOL" NUMBER(16,4), 
	"COSTOTDOL" NUMBER(16,4)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_TSI_SUITE" ;
