--------------------------------------------------------
--  DDL for Table TIEMPOS_DET
--------------------------------------------------------

  CREATE TABLE "USR_TSI_SUITE"."TIEMPOS_DET" 
   (	"ID_CIA" NUMBER(*,0), 
	"NUMINT" NUMBER(*,0), 
	"ITEM" NUMBER(*,0), 
	"OPNUMDOC" NUMBER(*,0), 
	"OPNUMITE" NUMBER(*,0), 
	"OPTIPINV" NUMBER(*,0), 
	"OPCODART" VARCHAR2(40 BYTE), 
	"CODETA" NUMBER(*,0), 
	"CODMAQ" NUMBER(*,0), 
	"CODTHO" NUMBER(*,0), 
	"HORINI" TIMESTAMP (6), 
	"HORFIN" TIMESTAMP (6), 
	"TIEMPO" NUMBER(*,0), 
	"COSTOT01" NUMBER(16,2), 
	"COSTOT02" NUMBER(16,2), 
	"SITUAC" CHAR(1 BYTE), 
	"FCREAC" TIMESTAMP (6), 
	"FACTUA" TIMESTAMP (6), 
	"USUARI" VARCHAR2(10 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_TSI_SUITE" ;
