--------------------------------------------------------
--  DDL for Table TIEMPO
--------------------------------------------------------

  CREATE TABLE "USR_TSI_SUITE"."TIEMPO" 
   (	"FECHA" DATE, 
	"PERIODO" NUMBER(*,0), 
	"SEMESTRE" NUMBER(*,0), 
	"CUATRIMESTRE" NUMBER(*,0), 
	"TRIMESTRE" NUMBER(*,0), 
	"BIMESTRE" NUMBER(*,0), 
	"MESID" NUMBER(*,0), 
	"MES" VARCHAR2(15 BYTE), 
	"NUMMES" NUMBER(*,0), 
	"SEMANA" NUMBER(*,0), 
	"NUMDIASEMANA" NUMBER(*,0), 
	"DIASEMANA" VARCHAR2(15 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_TSI_SUITE" ;
