--------------------------------------------------------
--  DDL for Table TIPOPLANILLA
--------------------------------------------------------

  CREATE TABLE "USR_TSI_SUITE"."TIPOPLANILLA" 
   (	"ID_CIA" NUMBER, 
	"TIPPLA" VARCHAR2(1 BYTE), 
	"NOMBRE" VARCHAR2(40 BYTE), 
	"DIAPLA" NUMBER(*,0), 
	"HORPLA" NUMBER(*,0), 
	"REDOND" NUMBER(*,0), 
	"CODCTA" VARCHAR2(15 BYTE), 
	"FACADE" NUMBER(15,4), 
	"DH" CHAR(1 BYTE), 
	"AGRUPA" CHAR(1 BYTE), 
	"LIBRO" VARCHAR2(3 BYTE), 
	"SWCUENTA" VARCHAR2(1 BYTE), 
	"SWACTI" CHAR(1 BYTE) DEFAULT 'S', 
	"CODCTAOBR" VARCHAR2(15 BYTE), 
	"UCREAC" VARCHAR2(10 BYTE), 
	"UACTUA" VARCHAR2(10 BYTE), 
	"FCREAC" TIMESTAMP (6), 
	"FACTUA" TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_TSI_SUITE" ;
