--------------------------------------------------------
--  DDL for Table TIPO_NOTIFICACION
--------------------------------------------------------

  CREATE TABLE "USR_TSI_SUITE"."TIPO_NOTIFICACION" 
   (	"ID_CIA" NUMBER(*,0), 
	"TIPNOT" NUMBER(*,0), 
	"DESCRI" VARCHAR2(60 BYTE), 
	"TITULO" VARCHAR2(50 BYTE), 
	"COLOR" VARCHAR2(25 BYTE), 
	"SWACTI" CHAR(1 BYTE), 
	"CLASIF" NUMBER(*,0), 
	"OBJNEG" NUMBER(*,0), 
	"PROCES" NUMBER(*,0), 
	"EXPFIL" BLOB
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_TSI_SUITE" 
 LOB ("EXPFIL") STORE AS SECUREFILE (
  TABLESPACE "TBS_TSI_SUITE" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
