--------------------------------------------------------
--  DDL for Table TIPO_TRABAJADOR
--------------------------------------------------------

  CREATE TABLE "USR_TSI_SUITE"."TIPO_TRABAJADOR" 
   (	"ID_CIA" NUMBER, 
	"TIPTRA" VARCHAR2(1 BYTE), 
	"NOMBRE" VARCHAR2(40 BYTE), 
	"NOPER" VARCHAR2(30 BYTE), 
	"CONPRE" VARCHAR2(3 BYTE), 
	"CUENTA" VARCHAR2(15 BYTE), 
	"LIBRO" VARCHAR2(3 BYTE), 
	"CONRED" VARCHAR2(3 BYTE), 
	"UCREAC" VARCHAR2(10 BYTE), 
	"UACTUA" VARCHAR2(10 BYTE), 
	"FCREAC" TIMESTAMP (6), 
	"FACTUA" TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_TSI_SUITE" ;
