--------------------------------------------------------
--  Constraints for Table TIPOPLANILLA_CONCEPTO
--------------------------------------------------------

  ALTER TABLE "USR_TSI_SUITE"."TIPOPLANILLA_CONCEPTO" MODIFY ("ID_CIA" NOT NULL ENABLE);
  ALTER TABLE "USR_TSI_SUITE"."TIPOPLANILLA_CONCEPTO" MODIFY ("TIPPLA" NOT NULL ENABLE);
  ALTER TABLE "USR_TSI_SUITE"."TIPOPLANILLA_CONCEPTO" MODIFY ("CODCON" NOT NULL ENABLE);
  ALTER TABLE "USR_TSI_SUITE"."TIPOPLANILLA_CONCEPTO" ADD CONSTRAINT "PK_TIPOPLANILLA_CONCEPTO" PRIMARY KEY ("ID_CIA", "TIPPLA", "CODCON")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_TSI_SUITE"  ENABLE;
