--------------------------------------------------------
--  DDL for Table TITULOLISTA
--------------------------------------------------------

  CREATE TABLE "USR_TSI_SUITE"."TITULOLISTA" 
   (	"ID_CIA" NUMBER(*,0), 
	"CODTIT" NUMBER(*,0), 
	"CODMON" VARCHAR2(5 BYTE), 
	"TITULO" VARCHAR2(50 CHAR), 
	"ABREVI" VARCHAR2(5 CHAR), 
	"TIPCAL" CHAR(1 BYTE), 
	"FACTOR" NUMBER(9,2), 
	"INCIGV" CHAR(1 BYTE), 
	"MODPRE" CHAR(1 BYTE), 
	"FCREAC" TIMESTAMP (6), 
	"FACTUA" TIMESTAMP (6), 
	"USUARI" VARCHAR2(10 BYTE), 
	"SWACTI" CHAR(1 BYTE), 
	"PORCOM" NUMBER(16,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_TSI_SUITE" ;
