--------------------------------------------------------
--  DDL for Table TMONEDA
--------------------------------------------------------

  CREATE TABLE "USR_TSI_SUITE"."TMONEDA" 
   (	"ID_CIA" NUMBER(*,0), 
	"CODMON" VARCHAR2(5 BYTE), 
	"DESMON" VARCHAR2(50 BYTE), 
	"ABREVI" VARCHAR2(5 BYTE), 
	"SIMBOLO" CHAR(3 BYTE), 
	"NACIONAL" NUMBER(*,0), 
	"CDIFDEB" VARCHAR2(16 BYTE), 
	"CDIFHAB" VARCHAR2(16 BYTE), 
	"CODSUNAT" VARCHAR2(10 BYTE), 
	"FCREAC" TIMESTAMP (6), 
	"FACTUA" TIMESTAMP (6), 
	"USUARI" VARCHAR2(10 BYTE), 
	"SWACTI" CHAR(1 BYTE), 
	"TCDESDE" NUMBER(9,4), 
	"TCHASTA" NUMBER(9,4)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_TSI_SUITE" ;
