--------------------------------------------------------
--  DDL for Table TOCASIONALES
--------------------------------------------------------

  CREATE TABLE "USR_TSI_SUITE"."TOCASIONALES" 
   (	"ID_CIA" NUMBER(*,0), 
	"TIDENT" CHAR(2 BYTE), 
	"DIDENT" VARCHAR2(20 BYTE), 
	"RAZON" VARCHAR2(120 BYTE), 
	"APEPAT" VARCHAR2(30 BYTE), 
	"APEMAT" VARCHAR2(30 BYTE), 
	"NOMBR1" VARCHAR2(30 BYTE), 
	"NOMBR2" VARCHAR2(30 BYTE), 
	"TPERSO" NUMBER(*,0), 
	"SITUAC" CHAR(1 BYTE), 
	"USUARI" VARCHAR2(10 BYTE), 
	"FCREAC" TIMESTAMP (6), 
	"FACTUA" TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_TSI_SUITE" ;
