--------------------------------------------------------
--  DDL for Table TSINOTICIAS
--------------------------------------------------------

  CREATE TABLE "USR_TSI_SUITE"."TSINOTICIAS" 
   (	"ID_CIA" NUMBER(*,0), 
	"NUMINT" NUMBER(*,0), 
	"TITULO" VARCHAR2(50 BYTE), 
	"LINK" VARCHAR2(500 BYTE), 
	"FDESDE" TIMESTAMP (6), 
	"FHASTA" TIMESTAMP (6), 
	"FEMISI" TIMESTAMP (6), 
	"SWACTI" VARCHAR2(5 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_TSI_SUITE" ;
