--------------------------------------------------------
--  DDL for Table USUARIOS_ACTIVOS
--------------------------------------------------------

  CREATE TABLE "USR_TSI_SUITE"."USUARIOS_ACTIVOS" 
   (	"ID_CIA" NUMBER(*,0), 
	"ID" NUMBER(*,0), 
	"CODUSER" VARCHAR2(10 BYTE), 
	"IP" VARCHAR2(10 BYTE), 
	"ACTIVO" VARCHAR2(1 BYTE), 
	"FCREAC" TIMESTAMP (6), 
	"FACTUA" TIMESTAMP (6), 
	"TOKEN" VARCHAR2(200 CHAR), 
	"TOKENTIPO" NUMBER(38,0), 
	"CODPRO" VARCHAR2(10 CHAR) DEFAULT 'ERP'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_TSI_SUITE" ;
