--------------------------------------------------------
--  DDL for Table VEHICULOS
--------------------------------------------------------

  CREATE TABLE "USR_TSI_SUITE"."VEHICULOS" 
   (	"ID_CIA" NUMBER(*,0), 
	"CODVEH" NUMBER(*,0), 
	"DESCRI" VARCHAR2(50 BYTE), 
	"TIPO" VARCHAR2(20 BYTE), 
	"MARCA" VARCHAR2(50 BYTE), 
	"PLACA" VARCHAR2(20 BYTE), 
	"CERTIF" VARCHAR2(30 BYTE), 
	"OBSERV" VARCHAR2(1000 BYTE), 
	"SWACTI" VARCHAR2(1 BYTE), 
	"SWTRANSP" CHAR(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_TSI_SUITE" ;
