--------------------------------------------------------
--  Constraints for Table VENDEDOR_METAS
--------------------------------------------------------

  ALTER TABLE "USR_TSI_SUITE"."VENDEDOR_METAS" MODIFY ("ID_CIA" NOT NULL ENABLE);
  ALTER TABLE "USR_TSI_SUITE"."VENDEDOR_METAS" MODIFY ("CODVEN" NOT NULL ENABLE);
  ALTER TABLE "USR_TSI_SUITE"."VENDEDOR_METAS" MODIFY ("PERIODO" NOT NULL ENABLE);
  ALTER TABLE "USR_TSI_SUITE"."VENDEDOR_METAS" MODIFY ("MES" NOT NULL ENABLE);
  ALTER TABLE "USR_TSI_SUITE"."VENDEDOR_METAS" ADD PRIMARY KEY ("ID_CIA", "CODVEN", "PERIODO", "MES")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_TSI_SUITE"  ENABLE;
