--------------------------------------------------------
--  DDL for Table VENDEDOR
--------------------------------------------------------

  CREATE TABLE "USR_TSI_SUITE"."VENDEDOR" 
   (	"ID_CIA" NUMBER(*,0), 
	"CODVEN" NUMBER(*,0), 
	"DESVEN" VARCHAR2(50 BYTE), 
	"CARGO" VARCHAR2(30 CHAR), 
	"EMAIL" VARCHAR2(50 BYTE), 
	"CELULAR" VARCHAR2(20 BYTE), 
	"TELEFO" VARCHAR2(20 BYTE), 
	"COMISI" NUMBER(9,2), 
	"ABREVI" VARCHAR2(10 BYTE), 
	"FCREAC" TIMESTAMP (6), 
	"FACTUA" TIMESTAMP (6), 
	"USUARI" VARCHAR2(10 BYTE), 
	"SWACTI" CHAR(1 BYTE), 
	"FIRMA" BLOB, 
	"FORMFIRMA" VARCHAR2(4 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_TSI_SUITE" 
 LOB ("FIRMA") STORE AS SECUREFILE (
  TABLESPACE "TBS_TSI_SUITE" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
