--------------------------------------------------------
--  Constraints for Table WASIENHEA
--------------------------------------------------------

  ALTER TABLE "USR_TSI_SUITE"."WASIENHEA" MODIFY ("ID_CIA" NOT NULL ENABLE);
  ALTER TABLE "USR_TSI_SUITE"."WASIENHEA" MODIFY ("PERIODO" NOT NULL ENABLE);
  ALTER TABLE "USR_TSI_SUITE"."WASIENHEA" MODIFY ("MES" NOT NULL ENABLE);
  ALTER TABLE "USR_TSI_SUITE"."WASIENHEA" MODIFY ("LIBRO" NOT NULL ENABLE);
  ALTER TABLE "USR_TSI_SUITE"."WASIENHEA" MODIFY ("ASIENTO" NOT NULL ENABLE);
  ALTER TABLE "USR_TSI_SUITE"."WASIENHEA" MODIFY ("USUARI" NOT NULL ENABLE);
  ALTER TABLE "USR_TSI_SUITE"."WASIENHEA" ADD CONSTRAINT "PK_WASIENHEA" PRIMARY KEY ("ID_CIA", "PERIODO", "MES", "LIBRO", "ASIENTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_TSI_SUITE"  ENABLE;
