--------------------------------------------------------
--  DDL for Table WASIENHEA
--------------------------------------------------------

  CREATE TABLE "USR_TSI_SUITE"."WASIENHEA" 
   (	"ID_CIA" NUMBER(*,0), 
	"PERIODO" NUMBER(*,0), 
	"MES" NUMBER(*,0), 
	"LIBRO" VARCHAR2(3 BYTE), 
	"ASIENTO" NUMBER(*,0), 
	"CONCEP" VARCHAR2(150 BYTE), 
	"CODIGO" VARCHAR2(20 BYTE), 
	"NOMBRE" VARCHAR2(120 BYTE), 
	"MOTIVO" CHAR(3 BYTE), 
	"TASIEN" NUMBER(*,0), 
	"MONEDA" VARCHAR2(3 BYTE), 
	"FECHA" TIMESTAMP (6), 
	"TCAMB01" NUMBER(14,6), 
	"TCAMB02" NUMBER(14,6), 
	"NCONTAB" NUMBER(*,0), 
	"SITUAC" NUMBER(*,0), 
	"USUARI" VARCHAR2(10 BYTE), 
	"FCREAC" TIMESTAMP (6), 
	"FACTUA" TIMESTAMP (6), 
	"USRLCK" VARCHAR2(10 BYTE), 
	"CODBAN" VARCHAR2(3 BYTE), 
	"REFERENCIA" VARCHAR2(30 BYTE), 
	"GIRARA" VARCHAR2(70 BYTE), 
	"SERRET" VARCHAR2(5 BYTE), 
	"NUMRET" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_TSI_SUITE" ;
