--------------------------------------------------------
--  Constraints for Table WMOVIMIENTOS
--------------------------------------------------------

  ALTER TABLE "USR_TSI_SUITE"."WMOVIMIENTOS" MODIFY ("ID_CIA" NOT NULL ENABLE);
  ALTER TABLE "USR_TSI_SUITE"."WMOVIMIENTOS" MODIFY ("PERIODO" NOT NULL ENABLE);
  ALTER TABLE "USR_TSI_SUITE"."WMOVIMIENTOS" MODIFY ("MES" NOT NULL ENABLE);
  ALTER TABLE "USR_TSI_SUITE"."WMOVIMIENTOS" MODIFY ("LIBRO" NOT NULL ENABLE);
  ALTER TABLE "USR_TSI_SUITE"."WMOVIMIENTOS" MODIFY ("ASIENTO" NOT NULL ENABLE);
  ALTER TABLE "USR_TSI_SUITE"."WMOVIMIENTOS" MODIFY ("ITEM" NOT NULL ENABLE);
  ALTER TABLE "USR_TSI_SUITE"."WMOVIMIENTOS" MODIFY ("SITEM" NOT NULL ENABLE);
  ALTER TABLE "USR_TSI_SUITE"."WMOVIMIENTOS" MODIFY ("CUENTA" NOT NULL ENABLE);
  ALTER TABLE "USR_TSI_SUITE"."WMOVIMIENTOS" MODIFY ("DH" NOT NULL ENABLE);
  ALTER TABLE "USR_TSI_SUITE"."WMOVIMIENTOS" ADD CONSTRAINT "PK_WMOVIMIENTOS" PRIMARY KEY ("ID_CIA", "PERIODO", "MES", "LIBRO", "ASIENTO", "ITEM", "SITEM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_TSI_SUITE"  ENABLE;
