--------------------------------------------------------
--  DDL for Table WMOVIMIENTOS
--------------------------------------------------------

  CREATE TABLE "USR_TSI_SUITE"."WMOVIMIENTOS" 
   (	"ID_CIA" NUMBER(*,0), 
	"PERIODO" NUMBER(*,0), 
	"MES" NUMBER(*,0), 
	"LIBRO" VARCHAR2(3 BYTE), 
	"ASIENTO" NUMBER(*,0), 
	"ITEM" NUMBER(*,0), 
	"SITEM" NUMBER(*,0), 
	"CONCEP" VARCHAR2(75 BYTE), 
	"FECHA" DATE, 
	"TASIEN" NUMBER(*,0), 
	"TOPERA" VARCHAR2(3 BYTE), 
	"CUENTA" VARCHAR2(16 BYTE), 
	"DH" CHAR(1 BYTE), 
	"MONEDA" CHAR(3 BYTE), 
	"IMPORTE" NUMBER(16,2), 
	"IMPOR01" NUMBER(16,2), 
	"IMPOR02" NUMBER(16,2), 
	"DEBE" NUMBER(16,2), 
	"DEBE01" NUMBER(16,2), 
	"DEBE02" NUMBER(16,2), 
	"HABER" NUMBER(16,2), 
	"HABER01" NUMBER(16,2), 
	"HABER02" NUMBER(16,2), 
	"TCAMBIO01" NUMBER(14,6), 
	"TCAMBIO02" NUMBER(14,6), 
	"CCOSTO" VARCHAR2(16 BYTE), 
	"PROYEC" VARCHAR2(16 BYTE), 
	"SUBCCO" VARCHAR2(10 BYTE), 
	"TIPO" NUMBER(*,0), 
	"DOCUME" NUMBER(*,0), 
	"CODIGO" VARCHAR2(20 BYTE), 
	"RAZON" VARCHAR2(75 BYTE), 
	"TIDENT" CHAR(2 BYTE), 
	"DIDENT" VARCHAR2(16 BYTE), 
	"TDOCUM" CHAR(2 BYTE), 
	"SERIE" VARCHAR2(5 BYTE), 
	"NUMERO" VARCHAR2(20 BYTE), 
	"FDOCUM" TIMESTAMP (6), 
	"USUARI" VARCHAR2(10 BYTE), 
	"FCREAC" TIMESTAMP (6), 
	"FACTUA" TIMESTAMP (6), 
	"REGCOMCOL" NUMBER(*,0), 
	"SWPROVICION" VARCHAR2(1 BYTE), 
	"SALDO" NUMBER(16,2), 
	"SWGASOPER" NUMBER(*,0), 
	"CODPORRET" VARCHAR2(4 BYTE), 
	"SWCHKCONCILIA" VARCHAR2(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_TSI_SUITE" ;
